(() => {
  'use strict';
  const RI=globalThis.__RI,S=RI.state; let observer=null,mutation=null,bar=null,enabled=localStorage.getItem('ri:grid')!=='0';
  const css=()=>{if(document.getElementById('ri-grid-css'))return;const st=document.createElement('style');st.id='ri-grid-css';st.textContent=`.ri-card{position:relative!important}.ri-metrics{position:absolute;left:4px;bottom:4px;z-index:40;background:rgba(0,0,0,.66);color:#fff;border-radius:7px;padding:4px 6px;font:700 11px/1.25 system-ui;pointer-events:none;white-space:pre-line}.ri-actions{position:absolute;right:4px;top:4px;z-index:50;display:flex;flex-direction:column;gap:4px}.ri-action{width:38px;height:38px;border:0;border-radius:11px;background:rgba(0,0,0,.68);color:#fff;font:700 17px system-ui;display:grid;place-items:center}#ri-sortbar{position:fixed;left:8px;right:8px;top:52px;z-index:999990;display:flex;gap:6px;overflow-x:auto;padding:5px;background:rgba(20,20,20,.88);border-radius:12px}#ri-sortbar button{flex:0 0 auto;border:0;border-radius:9px;background:#333;color:#fff;padding:8px 10px;font:700 12px system-ui}#ri-sortbar button.ri-active{background:#fff;color:#111}`;document.documentElement.appendChild(st);};
  const anchors=()=>[...document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]')].filter(a=>a.querySelector('img')&&RI.visible(a)&&a.getBoundingClientRect().width>70&&a.getBoundingClientRect().height>70);
  const stop=e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();};
  const button=(txt,title,fn)=>{const b=document.createElement('button');b.className='ri-action';b.textContent=txt;b.title=title;['pointerdown','mousedown','touchstart'].forEach(ev=>b.addEventListener(ev,stop,{capture:true,passive:false}));b.addEventListener('click',e=>{stop(e);fn();},{capture:true});return b;};
  const render=item=>{const d=item.data||{},lines=[];if(d.views!=null)lines.push(`▶ ${RI.fmt(d.views)}`);const r=[];if(d.likes!=null)r.push(`♥ ${RI.fmt(d.likes)}`);if(d.comments!=null)r.push(`💬 ${RI.fmt(d.comments)}`);if(r.length)lines.push(r.join(' · '));const med=RI.median([...S.gridItems.values()].map(x=>x.data?.views).filter(Number.isFinite));if(med&&d.views!=null&&d.views/med>=1.5)lines.push(`🔥 ${(d.views/med).toFixed(1)}×`);item.metrics.textContent=lines.join('\n');item.metrics.style.display=lines.length?'block':'none';};
  const load=async item=>{if(item.loading)return;item.loading=true;try{item.data=RI.merge(item.data,await RI.data.grid(item.anchor));render(item);}finally{item.loading=false;}};
  const attach=(a,i)=>{const code=RI.codeFromUrl(a.href);if(!code)return;let item=S.gridItems.get(code);if(item?.anchor===a&&a.isConnected)return;a.classList.add('ri-card');const metrics=document.createElement('div');metrics.className='ri-metrics';const actions=document.createElement('div');actions.className='ri-actions';a.append(metrics,actions);item={code,anchor:a,wrap:a,index:i,metrics,actions,data:RI.merge(S.posts.get(code)||{},{thumbUrl:a.querySelector('img')?.currentSrc||a.querySelector('img')?.src||null,pageUrl:a.href})};actions.appendChild(button('▧','이미지 저장',async()=>{await load(item);const u=RI.first(a.querySelector('img')?.currentSrc,a.querySelector('img')?.src,item.data?.thumbUrl);if(!u)return RI.toast('이미지 URL 없음');try{await RI.download(u,`${code}-thumb.jpg`);RI.toast('이미지 저장 시작');}catch{RI.toast('이미지 저장 실패');}}));if(/\/(?:reel|reels)\//.test(a.pathname))actions.appendChild(button('▶','영상 저장',async()=>{await load(item);if(!item.data?.videoUrl)return RI.toast('영상 URL 없음');try{await RI.download(item.data.videoUrl,`${code}.mp4`);RI.toast('영상 저장 시작');}catch{RI.toast('영상 저장 실패');}}));S.gridItems.set(code,item);render(item);observer?.observe(a);};
  const sort=key=>{const items=[...S.gridItems.values()].filter(x=>x.anchor.isConnected),med=RI.median(items.map(x=>x.data?.views).filter(Number.isFinite));const val=i=>key==='outlier'?(med&&i.data?.views!=null?i.data.views/med:null):key==='latest'?(i.data?.takenAt||Date.parse(i.data?.postedAt)||null):(i.data?.[key]??null);items.sort((a,b)=>(val(b)??-Infinity)-(val(a)??-Infinity)).forEach((x,i)=>x.anchor.style.order=String(i));};
  const ensureBar=()=>{if(bar?.isConnected)return;bar=document.createElement('div');bar.id='ri-sortbar';[['views','조회수'],['outlier','Outlier'],['likes','좋아요'],['comments','댓글'],['latest','최신']].forEach(([k,t])=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>sort(k);bar.appendChild(b);});document.documentElement.appendChild(bar);};
  const clear=()=>{bar?.remove();bar=null;S.gridItems.forEach(i=>{i.metrics.remove();i.actions.remove();i.anchor.classList.remove('ri-card');i.anchor.style.order='';});S.gridItems.clear();};
  const scan=()=>{if(!enabled||RI.currentDetail()){clear();return;}css();const list=anchors();if(list.length<6){clear();return;}ensureBar();list.forEach(attach);for(const[c,i]of[...S.gridItems])if(!i.anchor.isConnected)S.gridItems.delete(c);};
  const start=()=>{css();observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=S.gridItems.get(RI.codeFromUrl(e.target.href));if(i)load(i);}}),{rootMargin:'250px'});mutation=new MutationObserver(RI.debounce(scan,350));mutation.observe(document.documentElement,{childList:true,subtree:true});RI.on('post',e=>{const i=S.gridItems.get(e.detail.code);if(i){i.data=RI.merge(i.data,e.detail.data);render(i);}});scan();};
  RI.grid={start,scan,clear,setEnabled:v=>{enabled=!!v;localStorage.setItem('ri:grid',enabled?'1':'0');enabled?scan():clear();},get enabled(){return enabled;},sort};
})();
