// ==UserScript==
// @name         Reels Inspector Mobile
// @namespace    dev-lab/reels-inspector
// @version      2.2.2
// @match        *://*.instagram.com/*
// @grant        none
// @run-at       document-start
// @require      https://raw.githubusercontent.com/sunsee83/dev-lab/20c293c807f6a8129cbae5df19ff0b53e8ce7664/reels-inspector/ri-retry.user.js
// @updateURL    https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// @downloadURL  https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// ==/UserScript==
(function(){
'use strict';
var VER='2.2.2',GRID_KEY='ri2:grid:v1',SNAP_KEY='ri2:snap:v1',lastUrl='',busy=false,lastFetch=0;
function codeFromUrl(u){var m=String(u||'').match(/\/(?:reel|reels|p)\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
function code(){return codeFromUrl(location.href)}
function detail(){return /^\/(?:reel|reels|p)\/[A-Za-z0-9_-]+\/?/.test(location.pathname)}
function read(k,d){try{var s=localStorage.getItem(k);return s?JSON.parse(s):d}catch(e){return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function parseCount(s){s=String(s||'').replace(/[▶♥●↻]/g,'').replace(/,/g,'').replace(/\s+/g,'');var m=s.match(/^([0-9]+(?:\.[0-9]+)?)(만|천|억|K|M|B|k|m|b)?$/),n,u;if(!m)return null;n=+m[1];u=m[2]||'';if(u==='천'||/[Kk]/.test(u))n*=1e3;else if(u==='만')n*=1e4;else if(u==='억')n*=1e8;else if(/[Mm]/.test(u))n*=1e6;else if(/[Bb]/.test(u))n*=1e9;return Math.round(n)}
function fmt(n){n=+n;if(!isFinite(n)||n<=0)return'';if(n>=1e8)return(n/1e8).toFixed(1).replace(/\.0$/,'')+'억';if(n>=1e4)return(n/1e4).toFixed(1).replace(/\.0$/,'')+'만';if(n>=1e3)return(n/1e3).toFixed(1).replace(/\.0$/,'')+'K';return''+Math.round(n)}
function pct(n){if(!isFinite(+n))return'';n=+n;return(n>=10?n.toFixed(1):n.toFixed(2)).replace(/0+$/,'').replace(/\.$/,'')+'%'}
function getGrid(){return read(GRID_KEY,{})}
function saveGrid(c,d){if(!c||!d||!d.views)return;var s=getGrid();d.t=Date.now();s[c]=Object.assign(s[c]||{},d);var ks=Object.keys(s);if(ks.length>600){ks.sort(function(a,b){return(s[b].t||0)-(s[a].t||0)});ks.slice(600).forEach(function(k){delete s[k]})}write(GRID_KEY,s);recordSnap(c,d.views)}
function recordSnap(c,v){if(!c||!v)return;var s=read(SNAP_KEY,{}),a=Array.isArray(s[c])?s[c]:[],now=Date.now(),last=a.length?a[a.length-1]:null;if(!last||now-last.t>30*60*1000||last.v!==v)a.push({t:now,v:v});a=a.filter(function(x){return now-x.t<14*86400000});if(a.length>80)a=a.slice(-80);s[c]=a;write(SNAP_KEY,s)}
function growth(c,v){if(!c||!v)return null;var a=read(SNAP_KEY,{})[c]||[],now=Date.now(),best=null,bd=1e30;a.forEach(function(x){var age=now-x.t;if(age<18*3600000||age>32*3600000)return;var d=Math.abs(age-86400000);if(d<bd){bd=d;best=x}});if(!best||!best.v||v<best.v)return null;return(v-best.v)/best.v*100}
function scanGrid(){var as=document.querySelectorAll('a[data-ri-code]'),i,a,c,d,v,l,cm,rp,dt;for(i=0;i<as.length;i++){a=as[i];c=a.getAttribute('data-ri-code')||codeFromUrl(a.href);if(!c)continue;v=parseCount((a.querySelector('.ri-p-view')||{}).textContent);if(!v)continue;l=parseCount((a.querySelector('.ri-p-like')||{}).textContent);cm=parseCount((a.querySelector('.ri-p-comment')||{}).textContent);rp=parseCount((a.querySelector('.ri-p-repost')||{}).textContent);dt=((a.querySelector('.ri-s-date')||{}).textContent||'').trim();d={views:v,likes:l,comments:cm,reposts:rp,date:dt};saveGrid(c,d)}}
function nativeMetric(labels){var es=document.querySelectorAll('button,[role="button"],a,svg[aria-label],svg[title]'),i,e,r,s,p,txt,n,j,m,parts;for(i=0;i<es.length;i++){e=es[i];r=e.getBoundingClientRect();if(r.width<2||r.height<2||r.bottom<0||r.top>innerHeight||r.left<innerWidth*.60)continue;s=[e.getAttribute&&e.getAttribute('aria-label')||'',e.getAttribute&&e.getAttribute('title')||'',e.textContent||''].join(' ').toLowerCase();if(!labels.some(function(x){return s.indexOf(x.toLowerCase())>=0}))continue;p=e.closest('button,[role="button"],a')||e.parentElement||e;parts=[p.textContent||''];if(p.parentElement)parts.push(p.parentElement.textContent||'');if(p.nextElementSibling)parts.push(p.nextElementSibling.textContent||'');if(p.previousElementSibling)parts.push(p.previousElementSibling.textContent||'');for(j=0;j<parts.length;j++){txt=String(parts[j]).trim();m=txt.match(/([0-9]+(?:[.,][0-9]+)?\s*(?:만|천|억|K|M|B|k|m|b)?)/);if(m){n=parseCount(m[1]);if(n!=null)return n}}}return null}
function dateDom(){var ts=document.querySelectorAll('time[datetime]'),i,r;for(i=0;i<ts.length;i++){r=ts[i].getBoundingClientRect();if(r.width>0&&r.height>0&&r.bottom>0&&r.top<innerHeight){return(ts[i].getAttribute('datetime')||'').slice(5,10).replace('-','/')}}return''}
function injectStyle(){if(document.getElementById('ri222-style'))return;var st=document.createElement('style');st.id='ri222-style';st.textContent='#ri-detail-metrics{display:none!important}';(document.head||document.documentElement).appendChild(st)}
function makeBox(){var b=document.getElementById('ri222-detail');if(b)return b;b=document.createElement('div');b.id='ri222-detail';b.style.cssText='position:fixed;right:62px;top:clamp(100px,15vh,145px);z-index:2147483599;width:78px;padding:7px 6px;border-radius:14px;background:rgba(0,0,0,.13);backdrop-filter:blur(9px);-webkit-backdrop-filter:blur(9px);pointer-events:none;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;display:flex;flex-direction:column;align-items:flex-end;gap:7px;';[['views','조회수'],['er','ER'],['growth','24h'],['multiple','배수'],['date','게시일']].forEach(function(x){var r=document.createElement('div'),v=document.createElement('div'),l=document.createElement('div');r.dataset.k=x[0];r.style.cssText='display:none;flex-direction:column;align-items:flex-end;gap:1px;min-height:27px';v.className='v';v.style.cssText='max-width:74px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:750 12.5px/1.05 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;letter-spacing:-.22px;color:#fff;text-shadow:0 1px 3px rgba(0,0,0,.95),0 0 2px rgba(0,0,0,.65)';l.textContent=x[1];l.style.cssText='font:650 8.7px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:rgba(255,255,255,.72);text-shadow:0 1px 3px rgba(0,0,0,.95)';r.appendChild(v);r.appendChild(l);b.appendChild(r)});document.documentElement.appendChild(b);return b}
function setVal(b,k,t){var r=b.querySelector('[data-k="'+k+'"]'),v=r&&r.querySelector('.v');if(!r||!v)return;if(!t){r.style.display='none';return}if(v.textContent!==t)v.textContent=t;r.style.display='flex'}
function render(){if(!detail()){var old=document.getElementById('ri222-detail');if(old)old.remove();return}var c=code(),d=getGrid()[c]||{},b=makeBox(),views=d.views||null,likes=d.likes,comments=d.comments,reposts=d.reposts,er=null,g=null,dt=d.date||dateDom();if(!likes)likes=nativeMetric(['좋아요','likes','like']);if(!comments)comments=nativeMetric(['댓글','comments','comment']);if(!reposts)reposts=nativeMetric(['리포스트','reposts','repost']);if(views&&(likes||comments||reposts))er=((likes||0)+(comments||0)+(reposts||0))/views*100;if(views)g=growth(c,views);setVal(b,'views',views?fmt(views):'');setVal(b,'er',er!=null?'ER '+pct(er):'');setVal(b,'growth',g!=null?(g>=0?'+':'')+pct(g):'');setVal(b,'multiple','');setVal(b,'date',dt||'');if(!views)fetchView(c)}
function nearView(t,c){if(!t||!c||t.length>9000000)return null;var p=t.indexOf(c),best=null,bd=1e30,keys=['play_count','ig_play_count','video_play_count','video_view_count','view_count','clips_play_count','reel_view_count','views','plays'];if(p<0)return null;var st=Math.max(0,p-45000),en=Math.min(t.length,p+70000),a=t.slice(st,en);keys.forEach(function(k){var re=new RegExp('(?:["\\\\])?'+k+'(?:["\\\\])?\\s*:\\s*["\\\\]?([0-9]+)["\\\\]?','ig'),m,g=0;while((m=re.exec(a))&&g++<30){var abs=st+m.index,d=Math.abs(abs-p);if(d<bd){bd=d;best=+m[1]}}});return best}
function fetchView(c){var now=Date.now();if(!c||busy||now-lastFetch<7000)return;busy=true;lastFetch=now;var html=document.documentElement?document.documentElement.innerHTML:'',v=nearView(html,c);if(v){saveGrid(c,{views:v});busy=false;render();return}var x=new XMLHttpRequest();x.open('GET',location.href.split('?')[0],true);x.withCredentials=true;x.onreadystatechange=function(){if(x.readyState!==4)return;var n=x.status>=200&&x.status<400?nearView(x.responseText||'',c):null;if(n)saveGrid(c,{views:n});busy=false;render()};try{x.send()}catch(e){busy=false}}
function patchVersion(){var p=document.getElementById('ri-panel'),ds,i;if(p){ds=p.querySelectorAll('div');for(i=0;i<ds.length;i++)if((ds[i].textContent||'').trim()==='v2.2.0')ds[i].textContent='v'+VER}document.querySelectorAll('div').forEach(function(d){if((d.textContent||'').trim()==='Reels Inspector 2.2.0')d.textContent='Reels Inspector '+VER})}
function tick(){injectStyle();scanGrid();if(location.href!==lastUrl){lastUrl=location.href;busy=false;lastFetch=0;var b=document.getElementById('ri222-detail');if(b)b.remove()}patchVersion();render()}
injectStyle();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){tick();setInterval(tick,1400)});else{tick();setInterval(tick,1400)}
})();
