// ==UserScript==
// @name         Reels Inspector Mobile
// @namespace    dev-lab/reels-inspector
// @version      2.2.3
// @match        *://*.instagram.com/*
// @grant        none
// @run-at       document-start
// @require      https://raw.githubusercontent.com/sunsee83/dev-lab/20c293c807f6a8129cbae5df19ff0b53e8ce7664/reels-inspector/ri-retry.user.js
// @updateURL    https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// @downloadURL  https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// ==/UserScript==
(function(){
'use strict';
var VER='2.2.3';
var GRID_KEY='ri2:grid:v1',SNAP_KEY='ri2:snap:v1';
var VIEW_KEYS=['play_count','ig_play_count','video_play_count','video_view_count','view_count','view_count_fb','clips_play_count','reel_view_count','media_view_count','views','plays'];
var currentCode='',currentUrl='',lastFetch=0,busy=false,net={};

function codeFromUrl(u){var m=String(u||'').match(/\/(?:reel|reels|p)\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
function read(k,d){try{var s=localStorage.getItem(k);return s?JSON.parse(s):d}catch(e){return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function parseCount(s){s=String(s||'').replace(/[▶♥●↻]/g,'').replace(/,/g,'').replace(/\s+/g,'');var m=s.match(/^([0-9]+(?:\.[0-9]+)?)(만|천|억|K|M|B|k|m|b)?$/),n,u;if(!m)return null;n=+m[1];u=m[2]||'';if(u==='천'||/[Kk]/.test(u))n*=1e3;else if(u==='만')n*=1e4;else if(u==='억')n*=1e8;else if(/[Mm]/.test(u))n*=1e6;else if(/[Bb]/.test(u))n*=1e9;return Math.round(n)}
function fmt(n){n=+n;if(!isFinite(n)||n<=0)return'';if(n>=1e8)return(n/1e8).toFixed(1).replace(/\.0$/,'')+'억';if(n>=1e4)return(n/1e4).toFixed(1).replace(/\.0$/,'')+'만';if(n>=1e3)return(n/1e3).toFixed(1).replace(/\.0$/,'')+'K';return''+Math.round(n)}
function pct(n){if(!isFinite(+n))return'';n=+n;return(n>=10?n.toFixed(1):n.toFixed(2)).replace(/0+$/,'').replace(/\.$/,'')+'%'}
function visibleRect(el){if(!el)return null;var r=el.getBoundingClientRect();var l=Math.max(0,r.left),t=Math.max(0,r.top),rr=Math.min(innerWidth,r.right),bb=Math.min(innerHeight,r.bottom);if(rr<=l||bb<=t)return null;return {r:r,area:(rr-l)*(bb-t),cx:(l+rr)/2,cy:(t+bb)/2}}
function activeVideo(){var vs=document.querySelectorAll('video'),best=null,bs=-1,i,x,center=innerHeight/2,score;for(i=0;i<vs.length;i++){x=visibleRect(vs[i]);if(!x||x.area<10000)continue;score=x.area-Math.abs(x.cy-center)*innerWidth*2;if(score>bs){bs=score;best=vs[i]}}return best}
function reelRoot(v){var e=v,best=v,i,r,links;for(i=0;i<12&&e;i++,e=e.parentElement){r=e.getBoundingClientRect();if(r.width>innerWidth*.55&&r.height>innerHeight*.52)best=e;links=e.querySelectorAll?e.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]'):[];if(r.width>innerWidth*.70&&r.height>innerHeight*.70&&links.length)return e}return best||document.querySelector('main')||document.body}
function hrefCode(root){var urlCode=codeFromUrl(location.href),as,i,a,r,vr,c;if(urlCode)return {code:urlCode,url:location.href.split('?')[0]};if(!root)return {code:'',url:''};as=root.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]');for(i=0;i<as.length;i++){a=as[i];c=codeFromUrl(a.href);if(c)return {code:c,url:a.href.split('?')[0]}}var v=activeVideo();vr=v&&v.getBoundingClientRect();as=document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]');for(i=0;i<as.length;i++){a=as[i];r=a.getBoundingClientRect();if(!vr||r.bottom<vr.top||r.top>vr.bottom)continue;c=codeFromUrl(a.href);if(c)return {code:c,url:a.href.split('?')[0]}}return {code:'',url:''}}
function context(){var v=activeVideo();if(!v)return null;var root=reelRoot(v),h=hrefCode(root);if(!h.code)return null;return {video:v,root:root,code:h.code,url:h.url||('https://www.instagram.com/reel/'+h.code+'/')}}

function saveGrid(c,d){if(!c||!d||!d.views)return;var s=read(GRID_KEY,{});d.t=Date.now();s[c]=Object.assign(s[c]||{},d);write(GRID_KEY,s);snap(c,d.views)}
function snap(c,v){if(!c||!v)return;var s=read(SNAP_KEY,{}),a=Array.isArray(s[c])?s[c]:[],now=Date.now(),last=a.length?a[a.length-1]:null;if(!last||now-last.t>1800000||last.v!==v)a.push({t:now,v:v});a=a.filter(function(x){return now-x.t<14*86400000});if(a.length>80)a=a.slice(-80);s[c]=a;write(SNAP_KEY,s)}
function growth(c,v){var a=read(SNAP_KEY,{})[c]||[],now=Date.now(),best=null,bd=1e30;if(!c||!v)return null;a.forEach(function(x){var age=now-x.t;if(age<18*3600000||age>32*3600000)return;var d=Math.abs(age-86400000);if(d<bd){bd=d;best=x}});if(!best||!best.v||v<best.v)return null;return(v-best.v)/best.v*100}
function scanGrid(){var as=document.querySelectorAll('a[data-ri-code]'),i,a,c,v,l,cm,rp,dt;for(i=0;i<as.length;i++){a=as[i];c=a.getAttribute('data-ri-code')||codeFromUrl(a.href);v=parseCount((a.querySelector('.ri-p-view')||{}).textContent);if(!c||!v)continue;l=parseCount((a.querySelector('.ri-p-like')||{}).textContent);cm=parseCount((a.querySelector('.ri-p-comment')||{}).textContent);rp=parseCount((a.querySelector('.ri-p-repost')||{}).textContent);dt=((a.querySelector('.ri-s-date')||{}).textContent||'').trim();saveGrid(c,{views:v,likes:l,comments:cm,reposts:rp,date:dt})}}

function metricFromRoot(root,labels){if(!root)return null;var es=root.querySelectorAll('button,[role="button"],a,[aria-label],[title],svg'),i,e,s,p,parts,j,m,n;for(i=0;i<es.length;i++){e=es[i];s=[e.getAttribute&&e.getAttribute('aria-label')||'',e.getAttribute&&e.getAttribute('title')||'',e.textContent||''].join(' ').toLowerCase();if(!labels.some(function(x){return s.indexOf(x.toLowerCase())>=0}))continue;p=e.closest('button,[role="button"],a')||e.parentElement||e;parts=[p.textContent||''];if(p.parentElement)parts.push(p.parentElement.textContent||'');if(p.nextElementSibling)parts.push(p.nextElementSibling.textContent||'');if(p.previousElementSibling)parts.push(p.previousElementSibling.textContent||'');for(j=0;j<parts.length;j++){m=String(parts[j]).match(/([0-9]+(?:[.,][0-9]+)?\s*(?:만|천|억|K|M|B|k|m|b)?)/);if(m){n=parseCount(m[1]);if(n!=null)return n}}}return null}
function dateFromRoot(root){var ts=root?root.querySelectorAll('time[datetime]'):[],i,r;for(i=0;i<ts.length;i++){r=ts[i].getBoundingClientRect();if(r.width>0&&r.height>0&&r.bottom>0&&r.top<innerHeight)return(ts[i].getAttribute('datetime')||'').slice(5,10).replace('-','/')}return''}
function nearMetric(text,c,keys){if(!text||!c||text.length>10000000)return null;var positions=[],p=0,i,k,st,en,a,re,m,g,abs,d,best=null,bd=1e30;while((p=text.indexOf(c,p))>=0&&positions.length<25){positions.push(p);p+=c.length}for(i=0;i<positions.length;i++){st=Math.max(0,positions[i]-22000);en=Math.min(text.length,positions[i]+36000);a=text.slice(st,en);for(k=0;k<keys.length;k++){re=new RegExp('(?:["\\\\])?'+keys[k]+'(?:["\\\\])?\\s*:\\s*["\\\\]?([0-9]+)["\\\\]?','ig');g=0;while((m=re.exec(a))&&g++<20){abs=st+m.index;d=Math.abs(abs-positions[i]);if(d<bd){bd=d;best=+m[1]}}}}return best}
function parseResponse(text,c){var d={};d.views=nearMetric(text,c,VIEW_KEYS);d.likes=nearMetric(text,c,['like_count','likes_count']);d.comments=nearMetric(text,c,['comment_count','comments_count']);d.reposts=nearMetric(text,c,['reshare_count','repost_count','reposts_count']);var t=nearMetric(text,c,['taken_at','taken_at_timestamp']);if(t){try{d.date=new Date(t*1000).toISOString().slice(5,10).replace('-','/')}catch(e){}}return d}
function mergeData(c,d){if(!c||!d)return;net[c]=Object.assign(net[c]||{},d);if(d.views)saveGrid(c,d)}
function scanNetworkText(text){var c=currentCode;if(!c||!text)return;var d=parseResponse(text,c);if(d.views||d.likes||d.comments||d.reposts)mergeData(c,d)}
function hookNetwork(){var of=window.fetch,OX=window.XMLHttpRequest;if(of&&!of.__ri223){window.fetch=function(){return of.apply(this,arguments).then(function(r){try{var u=r.url||'',ct=r.headers&&r.headers.get?r.headers.get('content-type')||'':'';if(ct.indexOf('json')>=0||/graphql|api|ajax|clips|reels|media/i.test(u))r.clone().text().then(scanNetworkText).catch(function(){})}catch(e){}return r})};window.fetch.__ri223=true}if(OX&&!OX.prototype.__ri223){var oo=OX.prototype.open,os=OX.prototype.send;OX.prototype.open=function(){this.__ri223url=arguments[1]||'';return oo.apply(this,arguments)};OX.prototype.send=function(){this.addEventListener('load',function(){try{var ct=this.getResponseHeader('content-type')||'';if((ct.indexOf('json')>=0||/graphql|api|ajax|clips|reels|media/i.test(this.__ri223url||''))&&typeof this.responseText==='string')scanNetworkText(this.responseText)}catch(e){}});return os.apply(this,arguments)};OX.prototype.__ri223=true}}

function injectStyle(){if(document.getElementById('ri223-style'))return;var st=document.createElement('style');st.id='ri223-style';st.textContent='#ri-detail-metrics,#ri222-detail{display:none!important} #ri223-detail{background:transparent!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;box-shadow:none!important;}';(document.head||document.documentElement).appendChild(st)}
function makeBox(){var b=document.getElementById('ri223-detail');if(b)return b;b=document.createElement('div');b.id='ri223-detail';b.style.cssText='position:fixed;right:88px;top:clamp(112px,16vh,165px);z-index:2147483599;width:82px;pointer-events:none;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;display:none;flex-direction:column;align-items:flex-end;gap:7px;text-align:right;';[['views','조회수'],['er','ER'],['growth','24h'],['multiple','배수'],['date','게시일']].forEach(function(x){var r=document.createElement('div'),v=document.createElement('div'),l=document.createElement('div');r.dataset.k=x[0];r.style.cssText='display:none;flex-direction:column;align-items:flex-end;gap:1px';v.className='v';v.style.cssText='max-width:82px;white-space:nowrap;font:760 12.5px/1.05 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;letter-spacing:-.2px;color:#fff;text-shadow:0 1px 3px rgba(0,0,0,.95),0 0 2px rgba(0,0,0,.7)';l.textContent=x[1];l.style.cssText='font:650 8.5px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:rgba(255,255,255,.82);text-shadow:0 1px 3px rgba(0,0,0,.95)';r.appendChild(v);r.appendChild(l);b.appendChild(r)});document.documentElement.appendChild(b);return b}
function setVal(b,k,t){var r=b.querySelector('[data-k="'+k+'"]'),v=r&&r.querySelector('.v');if(!r||!v)return false;if(!t){r.style.display='none';return false}if(v.textContent!==t)v.textContent=t;r.style.display='flex';return true}
function render(ctx){var old=document.getElementById('ri223-detail');if(!ctx){if(old)old.style.display='none';return}var c=ctx.code,grid=read(GRID_KEY,{})[c]||{},n=net[c]||{},views=grid.views||n.views||null,likes=metricFromRoot(ctx.root,['좋아요','likes','like'])||grid.likes||n.likes||null,comments=metricFromRoot(ctx.root,['댓글','comments','comment'])||grid.comments||n.comments||null,reposts=metricFromRoot(ctx.root,['리포스트','reposts','repost'])||grid.reposts||n.reposts||null,dt=dateFromRoot(ctx.root)||grid.date||n.date||'',er=null,g=null,b=makeBox(),any=false;if(views&&(likes||comments||reposts))er=((likes||0)+(comments||0)+(reposts||0))/views*100;if(views)g=growth(c,views);any=setVal(b,'views',views?fmt(views):'')||any;any=setVal(b,'er',er!=null?'ER '+pct(er):'')||any;any=setVal(b,'growth',g!=null?(g>=0?'+':'')+pct(g):'')||any;setVal(b,'multiple','');any=setVal(b,'date',dt)||any;b.style.display=any?'flex':'none';if(!views)fetchPermalink(ctx)}
function fetchPermalink(ctx){var now=Date.now();if(!ctx||!ctx.code||busy||now-lastFetch<5000)return;busy=true;lastFetch=now;var x=new XMLHttpRequest(),u=ctx.url||('https://www.instagram.com/reel/'+ctx.code+'/');x.open('GET',u,true);x.withCredentials=true;x.onreadystatechange=function(){if(x.readyState!==4)return;busy=false;if(x.status>=200&&x.status<400){var d=parseResponse(x.responseText||'',ctx.code);if(d.views||d.likes||d.comments||d.reposts)mergeData(ctx.code,d)}};try{x.send()}catch(e){busy=false}}
function patchVersion(){var p=document.getElementById('ri-panel'),ds,i;if(p){ds=p.querySelectorAll('div');for(i=0;i<ds.length;i++)if(/^v2\.2\.[0-9]+$/.test((ds[i].textContent||'').trim()))ds[i].textContent='v'+VER}document.querySelectorAll('div').forEach(function(d){if(/^Reels Inspector 2\.2\.[0-9]+$/.test((d.textContent||'').trim()))d.textContent='Reels Inspector '+VER})}
function tick(){injectStyle();scanGrid();var ctx=context(),c=ctx&&ctx.code||'';if(c!==currentCode){currentCode=c;currentUrl=ctx&&ctx.url||'';busy=false;lastFetch=0}patchVersion();render(ctx)}

injectStyle();hookNetwork();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){tick();setInterval(tick,1100)});else{tick();setInterval(tick,1100)}
})();
