// ==UserScript==
// @name         Reels Inspector Mobile
// @namespace    dev-lab/reels-inspector
// @version      2.2.1
// @match        *://*.instagram.com/*
// @grant        none
// @run-at       document-start
// @require      https://raw.githubusercontent.com/sunsee83/dev-lab/20c293c807f6a8129cbae5df19ff0b53e8ce7664/reels-inspector/ri-retry.user.js
// @updateURL    https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// @downloadURL  https://github.com/sunsee83/dev-lab/raw/refs/heads/main/reels-inspector/ri-retry.user.js
// ==/UserScript==
(function(){
'use strict';
var VER='2.2.1',VK=['play_count','ig_play_count','video_play_count','video_view_count','view_count','view_count_fb','play_count_fb','view_count_ig','clips_play_count','video_views','media_view_count','reel_view_count','view_count_v2','plays','views'],last='',view=null,busy=false,lastTry=0;
function code(){var m=location.pathname.match(/\/(?:reel|reels|p)\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
function detail(){return /^\/(?:reel|reels|p)\/[A-Za-z0-9_-]+\/?/.test(location.pathname)}
function fmt(n){n=+n;if(!isFinite(n)||n<=0)return'';if(n>=1e8)return(n/1e8).toFixed(1).replace(/\.0$/,'')+'억';if(n>=1e4)return(n/1e4).toFixed(1).replace(/\.0$/,'')+'만';if(n>=1e3)return(n/1e3).toFixed(1).replace(/\.0$/,'')+'K';return''+Math.round(n)}
function pct(n){if(!isFinite(+n))return'';n=+n;return(n>=10?n.toFixed(1):n.toFixed(2)).replace(/0+$/,'').replace(/\.$/,'')+'%'}
function parseCount(s){s=String(s||'').replace(/,/g,'').replace(/\s+/g,'');var m=s.match(/^([0-9]+(?:\.[0-9]+)?)(만|천|억|K|M|B|k|m|b)?$/),n,u;if(!m)return null;n=+m[1];u=m[2]||'';if(u==='천'||/[Kk]/.test(u))n*=1e3;else if(u==='만')n*=1e4;else if(u==='억')n*=1e8;else if(/[Mm]/.test(u))n*=1e6;else if(/[Bb]/.test(u))n*=1e9;return Math.round(n)}
function nearNum(s,c){s=String(s||'');if(!s||!c)return null;var p=0,pos=[],best=null,bd=1e30,i,k,st,en,a,re,m,abs,d,g;while((p=s.indexOf(c,p))>=0&&pos.length<30){pos.push(p);p+=c.length}for(i=0;i<pos.length;i++){st=Math.max(0,pos[i]-220000);en=Math.min(s.length,pos[i]+320000);a=s.slice(st,en);for(k=0;k<VK.length;k++){re=new RegExp('(?:["\\\\])?'+VK[k]+'(?:["\\\\])?\\s*:\\s*["\\\\]?([0-9]+)["\\\\]?','ig');g=0;while((m=re.exec(a))&&g++<35){abs=st+m.index;d=Math.abs(abs-pos[i]);if(d<bd){bd=d;best=+m[1]}}}}return best}
function owner(){var r=document.querySelector('main')||document,as=r.querySelectorAll('a[href^="/"]'),bad={accounts:1,explore:1,reels:1,reel:1,p:1,direct:1,stories:1},i,a,m,rr,sc,b='',bs=-1;for(i=0;i<as.length;i++){a=as[i];m=(a.getAttribute('href')||'').match(/^\/([A-Za-z0-9._]+)\/?(?:\?.*)?$/);if(!m||bad[m[1].toLowerCase()])continue;rr=a.getBoundingClientRect();if(rr.width<2||rr.height<2||rr.bottom<0||rr.top>innerHeight)continue;sc=(rr.top>innerHeight*.45?2:0)+(rr.left<innerWidth*.65?1:0)+((a.textContent||'').trim()?1:0);if(sc>bs){bs=sc;b=m[1]}}return b}
function metricNum(labels){var r=document.querySelector('main')||document,es=r.querySelectorAll('button,[role="button"],a,[aria-label],[title],svg'),i,e,s,m,n;for(i=0;i<es.length;i++){e=es[i];s=[e.getAttribute&&e.getAttribute('aria-label')||'',e.getAttribute&&e.getAttribute('title')||'',e.textContent||''].join(' ');if(!labels.some(function(x){return s.toLowerCase().indexOf(x.toLowerCase())>=0}))continue;for(var j=0;j<labels.length;j++){m=s.match(new RegExp(labels[j]+'\\s*[:：]?\\s*([0-9][0-9.,]*\\s*(?:만|천|억|K|M|B|k|m|b)?)','i'));if(m){n=parseCount(m[1]);if(n!=null)return n}}var p=e.closest('button,[role="button"],a')||e,x=[p.textContent||''];if(p.nextElementSibling)x.push(p.nextElementSibling.textContent||'');if(p.previousElementSibling)x.push(p.previousElementSibling.textContent||'');for(j=0;j<x.length;j++){n=parseCount(String(x[j]).trim());if(n!=null)return n}}return null}
function row(key){var b=document.getElementById('ri-detail-metrics');return b&&b.querySelector('[data-ri-metric="'+key+'"]')}
function setRow(key,text){var r=row(key);if(!r)return;if(text){r.textContent=text;r.style.display='block'}else{r.textContent='';r.style.display='none'}}
function patchBox(){if(!detail())return;var b=document.getElementById('ri-detail-metrics');if(!b)return;b.style.left='auto';b.style.right='62px';b.style.top='clamp(104px,15vh,150px)';b.style.alignItems='flex-end';b.style.maxWidth='104px';b.style.gap='7px';['likes','comments','reposts'].forEach(function(k){var r=row(k);if(r){r.style.display='none';r.textContent=''}});['views','er','growth','multiple','date'].forEach(function(k){var r=row(k);if(r){r.style.textAlign='right';r.style.fontSize='12px';r.style.lineHeight='1.12';r.style.letterSpacing='-.2px'}});if(view>0)setRow('views','▶ '+fmt(view));var likes=metricNum(['좋아요','likes','like']),comments=metricNum(['댓글','comments','comment']),reposts=metricNum(['리포스트','reposts','repost']);if(view>0&&(likes||comments||reposts))setRow('er','ER '+pct(((likes||0)+(comments||0)+(reposts||0))/view*100));}
function patchVersion(){var p=document.getElementById('ri-panel'),ds,i;if(p){ds=p.querySelectorAll('div');for(i=0;i<ds.length;i++)if((ds[i].textContent||'').trim()==='v2.2.0')ds[i].textContent='v'+VER}document.querySelectorAll('div').forEach(function(d){if((d.textContent||'').trim()==='Reels Inspector 2.2.0')d.textContent='Reels Inspector '+VER})}
function got(v){if(v>0){view=+v;patchBox()}}
function scanText(t){var c=code(),n;if(!c||!t||t.length>9000000)return;n=nearNum(t,c);if(n>0)got(n)}
function xhrGet(u,cb){var x=new XMLHttpRequest();x.open('GET',u,true);x.withCredentials=true;x.onreadystatechange=function(){if(x.readyState===4)cb(x.status>=200&&x.status<400?x.responseText||'':'')};try{x.send()}catch(e){cb('')}}
function fetchView(){var c=code(),now=Date.now();if(!detail()||!c||busy||now-lastTry<2500)return;busy=true;lastTry=now;var html=document.documentElement&&document.documentElement.innerHTML||'',n=nearNum(html,c);if(n>0){got(n);busy=false;return}xhrGet(location.href.split('?')[0],function(t){n=nearNum(t,c);if(n>0){got(n);busy=false;return}var o=owner();if(!o){busy=false;return}xhrGet('https://www.instagram.com/'+encodeURIComponent(o)+'/reels/',function(t2){n=nearNum(t2,c);if(n>0){got(n);busy=false;return}xhrGet('https://www.instagram.com/'+encodeURIComponent(o)+'/',function(t3){n=nearNum(t3,c);if(n>0)got(n);busy=false})})})}
function hook(){var of=window.fetch,OX=window.XMLHttpRequest;if(of&&!of.__ri221){window.fetch=function(){return of.apply(this,arguments).then(function(r){try{var ct=r.headers&&r.headers.get?r.headers.get('content-type')||'':'',u=r.url||'';if(ct.indexOf('json')>=0||/graphql|api|ajax|clips|reels|media/i.test(u))r.clone().text().then(scanText).catch(function(){})}catch(e){}return r})};window.fetch.__ri221=true}if(OX&&!OX.prototype.__ri221){var oo=OX.prototype.open,os=OX.prototype.send;OX.prototype.open=function(){this.__ri221url=arguments[1]||'';return oo.apply(this,arguments)};OX.prototype.send=function(){this.addEventListener('load',function(){try{var ct=this.getResponseHeader('content-type')||'';if((ct.indexOf('json')>=0||/graphql|api|ajax|clips|reels|media/i.test(this.__ri221url||''))&&typeof this.responseText==='string')scanText(this.responseText)}catch(e){}});return os.apply(this,arguments)};OX.prototype.__ri221=true}}
function tick(){var c=code();if(location.href!==last){last=location.href;view=null;busy=false;lastTry=0}if(!detail())return;patchBox();patchVersion();if(!view)fetchView()}
hook();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setInterval(tick,500)});else setInterval(tick,500);
})();
