(() => {
  'use strict';
  const RI=globalThis.__RI; let btn=null,sheet=null,body=null,currentTab='summary';
  const css=()=>{if(document.getElementById('ri-ui-css'))return;const st=document.createElement('style');st.id='ri-ui-css';st.textContent=`#ri-tool{position:fixed;right:14px;bottom:88px;z-index:999995;border:0;border-radius:999px;background:#111;color:#fff;padding:11px 14px;font:800 13px system-ui}#ri-sheet{position:fixed;left:0;right:0;bottom:0;z-index:1000000;background:#111;color:#fff;border-radius:20px 20px 0 0;max-height:58vh;min-height:38vh;display:flex;flex-direction:column;font-family:system-ui}#ri-sheet .ri-head{display:flex;align-items:center;justify-content:space-between;padding:13px 16px 9px;font-weight:800}#ri-sheet .ri-close{width:36px;height:36px;border:0;border-radius:50%;background:#2a2a2a;color:#fff;font-size:20px}#ri-sheet .ri-tabs{display:flex;gap:5px;padding:0 12px 9px;overflow-x:auto}#ri-sheet .ri-tabs button{flex:1 0 auto;border:0;border-radius:10px;background:#262626;color:#ccc;padding:9px 10px;font:700 12px system-ui}#ri-sheet .ri-tabs button.on{background:#fff;color:#111}#ri-sheet .ri-body{overflow:auto;padding:2px 14px 18px}#ri-sheet .ri-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}#ri-sheet .ri-card2{background:#1d1d1d;border-radius:12px;padding:11px}#ri-sheet .ri-k{font-size:11px;color:#999}.ri-v{font-size:16px;font-weight:800;word-break:break-word}#ri-sheet .ri-row{display:flex;gap:8px;margin:8px 0;flex-wrap:wrap}#ri-sheet .ri-btn{border:0;border-radius:10px;background:#2b2b2b;color:#fff;padding:10px 12px;font:700 12px system-ui}#ri-sheet pre{background:#181818;border-radius:10px;padding:10px;font-size:10px;white-space:pre-wrap;word-break:break-all;max-height:180px;overflow:auto}`;document.documentElement.appendChild(st);};
  const card=(k,v,fmt=true)=>v==null||v===''?'':`<div class="ri-card2"><div class="ri-k">${k}</div><div class="ri-v">${fmt?RI.fmt(v):String(v)}</div></div>`;
  const close=()=>{sheet?.remove();sheet=null;body=null;};
  const show=async t=>{currentTab=t;sheet?.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===t));if(!body)return;body.innerHTML='불러오는 중…';if(t==='summary'){const d=await RI.data.current();body.innerHTML=`<div class="ri-grid">${card('조회수',d.views)}${card('좋아요',d.likes)}${card('댓글',d.comments)}${card('리포스트',d.reposts)}${card('게시일',d.postedAt||RI.dateLabel(d.takenAt),false)}${card('길이',d.duration!=null?`${d.duration.toFixed(2)}초`:'',false)}${card('해상도',d.width&&d.height?`${d.width}×${d.height}`:'',false)}${card('오디오',d.audioName,false)}</div>`;}else if(t==='grid'){body.innerHTML=`<div class="ri-row"><button class="ri-btn" id="ri-grid-toggle">오버레이 ${RI.grid.enabled?'끄기':'켜기'}</button><button class="ri-btn" id="ri-grid-scan">다시 스캔</button></div>`;body.querySelector('#ri-grid-toggle').onclick=()=>{RI.grid.setEnabled(!RI.grid.enabled);show('grid');};body.querySelector('#ri-grid-scan').onclick=()=>RI.grid.scan();}else if(t==='media'){const d=await RI.data.current();body.innerHTML=`<div class="ri-row"><button class="ri-btn" id="ri-video">영상 저장</button><button class="ri-btn" id="ri-thumb">썸네일 저장</button><button class="ri-btn" id="ri-copy">영상 URL 복사</button></div>`;body.querySelector('#ri-video').onclick=async()=>{if(!d.videoUrl)return RI.toast('영상 URL 없음');try{await RI.download(d.videoUrl,`${d.code||'instagram'}.mp4`);RI.toast('영상 저장 시작');}catch{RI.toast('영상 저장 실패');}};body.querySelector('#ri-thumb').onclick=async()=>{if(!d.thumbUrl)return RI.toast('썸네일 URL 없음');try{await RI.download(d.thumbUrl,`${d.code||'instagram'}-thumb.jpg`);RI.toast('썸네일 저장 시작');}catch{RI.toast('썸네일 저장 실패');}};body.querySelector('#ri-copy').onclick=()=>RI.copy(d.videoUrl||'');}else{const d=await RI.data.current();body.innerHTML=`<div class="ri-row"><button class="ri-btn" id="ri-copy-json">JSON 복사</button></div><pre>${JSON.stringify(d,null,2).replace(/</g,'&lt;')}</pre>`;body.querySelector('#ri-copy-json').onclick=()=>RI.copy(JSON.stringify(d,null,2));}};
  const open=()=>{if(sheet?.isConnected)return;css();sheet=document.createElement('div');sheet.id='ri-sheet';sheet.innerHTML=`<div class="ri-head"><span>Reels Inspector</span><button class="ri-close">×</button></div><div class="ri-tabs"><button data-tab="summary">요약</button><button data-tab="grid">그리드</button><button data-tab="media">미디어</button><button data-tab="more">더보기</button></div><div class="ri-body"></div>`;document.documentElement.appendChild(sheet);body=sheet.querySelector('.ri-body');sheet.querySelector('.ri-close').onclick=close;sheet.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));show(currentTab);};
  const sync=()=>{const should=RI.currentDetail();if(should&&!btn){css();btn=document.createElement('button');btn.id='ri-tool';btn.textContent='도구';btn.onclick=open;document.documentElement.appendChild(btn);}if(!should&&btn){btn.remove();btn=null;close();}};
  RI.ui={start:()=>{css();sync();},sync,open,close,show};
})();
