(()=>{
'use strict';
const K='__RISAVE098',V='0.9.8';
const DB='ri-bookmarklet',STORE='handles',DIRKEY='instagram-download-dir',MODEKEY='riSaveMode',DATAKEY='riMetricsV1';
for(const k of ['__RISAVE097','__RISAVE096','__RISAVE095','__RISAVE094','__RISAVE093','__RISAVE092','__RISAVE091','__RISAVE090','__RISAVE089','__RISAVE088','__RISAVE087','__RISAVE086','__RISAVE085','__RISAVE084','__RISAVE083'])try{window[k]?.destroy?.()}catch{}
let sheet,launcher,toast,menu,obs,reelMetrics,dirHandle=null,current=null;
let saveMode=localStorage.getItem(MODEKEY)||'default',sheetMode='compact',sheetView='content',detailTab='summary',ensureQueued=false,routeTick='';
const cache=new Map(),metricStore=readJson(DATAKEY,{}),queue=[],pending=new Set();
let workers=0;
const activity={kind:'',state:'idle',message:'',detail:''};
const safe=s=>String(s||'x').normalize('NFKC').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,40)||'x';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const err=e=>`${e?.name||'Error'}: ${e?.message||e||''}`;
const dlIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 18v2h14v-2"/></svg>';
const metricDefs=[['views','조회'],['likes','좋아요'],['comments','댓글'],['reposts','재게시'],['er','ER'],['growth','24h'],['multiple','계정대비'],['date','게시일']];
function readJson(k,f){try{const x=JSON.parse(localStorage.getItem(k)||'');return x&&typeof x==='object'?x:f}catch{return f}}
function writeMetrics(){try{localStorage.setItem(DATAKEY,JSON.stringify(metricStore))}catch{}}
function parseHref(h){const m=String(h||'').match(/\/(reels?|p|tv)\/([^/?#]+)/i);return m?{kind:/reels?/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}:null}
function routeId(){try{return parseHref(location.pathname)}catch{return null}}
function currentId(){return routeId()||feedTargetId()||gridTargetId()}
function appId(){for(const s of document.querySelectorAll('script[type="application/json"]')){const m=(s.textContent||'').match(/"APP_ID":"?(\d+)"?/i);if(m)return m[1]}return'936619743392459'}
async function sameOriginJson(url){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{'X-IG-App-ID':appId(),'Accept':'*/*'}});if(!r.ok)throw Error(`Instagram API ${r.status}`);return r.json()}
function normalizeItem(x){if(!x)return null;if(x.xdt_api__v1__media__shortcode__web_info?.items?.[0])return x.xdt_api__v1__media__shortcode__web_info.items[0];if(x.items?.[0])return x.items[0];if(x.shortcode_media)return x.shortcode_media;return x}
function usernameOf(i){return i?.user?.username||i?.owner?.username||i?.owner?.user?.username||i?.username||'unknown'}
function childItems(i){if(Array.isArray(i?.carousel_media))return i.carousel_media;if(Array.isArray(i?.edge_sidecar_to_children?.edges))return i.edge_sidecar_to_children.edges.map(e=>e?.node).filter(Boolean);if(Array.isArray(i?.children))return i.children;return[]}
function videoVersions(i){const a=Array.isArray(i?.video_versions)?i.video_versions:[],b=Array.isArray(i?.video_resources)?i.video_resources.map(x=>({url:x.src,width:x.config_width||x.width,height:x.config_height||x.height})):[];return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function videoUrl(i){return videoVersions(i)[0]?.url||i?.video_url||''}
function imageCandidates(i){const a=Array.isArray(i?.image_versions2?.candidates)?i.image_versions2.candidates:[],b=[];if(i?.display_url)b.push({url:i.display_url,width:i.dimensions?.width,height:i.dimensions?.height});if(i?.display_resources)for(const x of i.display_resources)b.push({url:x.src,width:x.config_width,height:x.config_height});return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function imageUrl(i){return imageCandidates(i)[0]?.url||''}
function explicitCover(i){return i?.cover_frame_url||i?.cover_url||i?.clips_metadata?.cover_frame_url||i?.clips_metadata?.cover_media?.image_versions2?.candidates?.[0]?.url||''}
function isVideo(i){return !!(videoUrl(i)||i?.is_video||Number(i?.media_type)===2||/video|clips|reel/i.test(String(i?.product_type||i?.__typename||'')))}
function mediaType(i){const ch=childItems(i);if(ch.length>1||Number(i?.media_type)===8||/sidecar/i.test(String(i?.__typename||'')))return'carousel';return isVideo(i)?'video':'photo'}
function dash(i){return i?.video_dash_manifest||i?.dash_info?.video_dash_manifest||''}
function dashAudio(xml){if(!xml)return'';try{const doc=new DOMParser().parseFromString(xml,'application/xml'),xs=[...doc.querySelectorAll('Representation')].map(rep=>{const a=rep.closest('AdaptationSet'),mime=rep.getAttribute('mimeType')||a?.getAttribute('mimeType')||'',type=a?.getAttribute('contentType')||'',bw=+(rep.getAttribute('bandwidth')||0),url=rep.querySelector('BaseURL')?.textContent?.trim()||'';return{mime,type,bw,url}}).filter(x=>x.url&&(x.mime.startsWith('audio')||x.type==='audio'));return xs.sort((a,b)=>b.bw-a.bw)[0]?.url||''}catch{return''}}
function scalarNum(x){if(x==null||x==='')return undefined;const v=typeof x==='object'?(x.count??x.value):x,n=Number(v);return Number.isFinite(n)&&n>=0?n:undefined}
function metricDeep(root,keys,code){const q=[{v:root,d:0}],seen=new Set();while(q.length){const {v,d}=q.shift();if(!v||typeof v!=='object'||seen.has(v)||d>3)continue;seen.add(v);for(const k of keys){const n=scalarNum(v[k]);if(n!==undefined)return n}for(const [k,ch] of Object.entries(v).slice(0,120)){if(!ch||typeof ch!=='object')continue;if(Array.isArray(ch)){if(d<2)for(const z of ch.slice(0,30))if(z&&typeof z==='object')q.push({v:z,d:d+1});continue}const childCode=String(ch.code||ch.shortcode||ch.short_code||'');if(code&&childCode&&childCode!==code)continue;if(!/caption|text|accessibility|image_versions/i.test(k)||d<1)q.push({v:ch,d:d+1})}}return undefined}
function itemDate(item,code){const raw=item?.taken_at||item?.taken_at_timestamp||item?.date||item?.created_at||metricDeep(item,['taken_at','taken_at_timestamp','takenAt'],code);if(!raw)return'';if(typeof raw==='string'&&/^\d{4}-\d{2}-\d{2}/.test(raw))return raw.slice(0,10);const n=Number(raw),d=new Date(Number.isFinite(n)&&n<1e12?n*1000:raw);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
function metricFromItem(item,code,kind){return{shortcode:code,username:usernameOf(item),type:mediaType(item),kind,postedAt:itemDate(item,code),apiAt:Date.now(),views:metricDeep(item,['play_count','ig_play_count','video_play_count','video_view_count','view_count','clips_play_count','reel_view_count','media_view_count','views','plays'],code),likes:metricDeep(item,['like_count','likes_count','likes','likeCount'],code),comments:metricDeep(item,['comment_count','comments_count','comments','commentCount'],code),reposts:metricDeep(item,['repost_count','reshare_count','reposts_count','reposts','repostCount'],code),updatedAt:Date.now()}}
function persistMetric(rec){if(!rec?.shortcode)return null;const old=metricStore[rec.shortcode]||{shortcode:rec.shortcode,history:[]},next={...old};for(const k of ['username','type','kind','postedAt','views','likes','comments','reposts','updatedAt','apiAt','nativeAt'])if(rec[k]!==undefined&&rec[k]!==''&&rec[k]!=='unknown')next[k]=rec[k];next.history=Array.isArray(old.history)?old.history:[];if(Number.isFinite(Number(next.views))&&Number(next.views)>0){const now=Date.now(),last=next.history.at(-1);if(!last||now-Number(last.t||0)>=1800000||Number(last.v)!==Number(next.views))next.history.push({t:now,v:Number(next.views)});next.history=next.history.filter(x=>now-Number(x.t||0)<=1209600000).slice(-80)}metricStore[rec.shortcode]=next;writeMetrics();return next}
function deriveMetric(rec){if(!rec)return{};const views=Number(rec.views),likes=rec.likes,comments=rec.comments,reposts=rec.reposts;let er;if(Number.isFinite(views)&&views>0&&[likes,comments,reposts].every(x=>x!==undefined&&Number.isFinite(Number(x))&&Number(x)>=0))er=(Number(likes)+Number(comments)+Number(reposts))/views*100;let growth;const now=Date.now();let best=null,delta=Infinity;for(const x of rec.history||[]){const age=now-Number(x.t||0);if(age<18*3600000||age>32*3600000||!Number(x.v))continue;const d=Math.abs(age-24*3600000);if(d<delta){delta=d;best=x}}if(best&&views>=Number(best.v))growth=(views-Number(best.v))/Number(best.v)*100;let multiple;const owner=String(rec.username||'').toLowerCase();if(owner&&views>0){const list=Object.values(metricStore).filter(x=>x&&x.shortcode!==rec.shortcode&&String(x.username||'').toLowerCase()===owner&&Number(x.views)>0).sort((a,b)=>Number(b.apiAt||b.updatedAt||0)-Number(a.apiAt||a.updatedAt||0)).slice(0,20);if(list.length>=5){const vals=list.map(x=>Number(x.views)).sort((a,b)=>a-b),mid=Math.floor(vals.length/2),median=vals.length%2?vals[mid]:(vals[mid-1]+vals[mid])/2;if(median>0)multiple=views/median}}return{er,growth,multiple}}
function fmtCount(v){if(v===undefined||v===null||v==='')return'';const n=Number(v);if(!Number.isFinite(n)||n<0)return'';if(n>=1e8)return`${(n/1e8).toFixed(n>=1e9?0:1).replace(/\.0$/,'')}억`;if(n>=1e4)return`${(n/1e4).toFixed(n>=1e5?0:1).replace(/\.0$/,'')}만`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e4?0:1).replace(/\.0$/,'')}K`;return String(Math.round(n))}
function fmtPct(v,sign=false){if(v===undefined||!Number.isFinite(Number(v)))return'';const n=Number(v),s=(sign&&n>0)?'+':'';return`${s}${(Math.abs(n)>=10?n.toFixed(1):n.toFixed(2)).replace(/0+$/,'').replace(/\.$/,'')}%`}
function fmtMul(v){return v!==undefined&&Number.isFinite(Number(v))&&Number(v)>0?`×${Number(v).toFixed(Number(v)>=10?1:2).replace(/0+$/,'').replace(/\.$/,'')}`:''}
function shortDate(v){return /^\d{4}-\d{2}-\d{2}/.test(String(v||''))?String(v).slice(5,10).replace('-','/'):''}
function parseCompactCount(text){let s=String(text||'').trim().replace(/,/g,'');const m=s.match(/(\d+(?:\.\d+)?)\s*(억|만|천|[KkMm])?/);if(!m)return undefined;let n=Number(m[1]);if(!Number.isFinite(n))return undefined;const u=m[2];if(u==='억')n*=1e8;else if(u==='만')n*=1e4;else if(u==='천'||u==='K'||u==='k')n*=1e3;else if(u==='M'||u==='m')n*=1e6;return Math.round(n)}
function buttonMetric(root,terms){if(!root)return undefined;const all=[...root.querySelectorAll('button,[role="button"]')];for(const b of all){const label=(b.getAttribute('aria-label')||'')+' '+[...b.querySelectorAll('svg')].map(x=>x.getAttribute('aria-label')||'').join(' ');if(!terms.some(t=>label.toLowerCase().includes(t)))continue;const ps=[b.parentElement,b.parentElement?.parentElement,b];for(const p of ps){const n=parseCompactCount(p?.textContent||'');if(n!==undefined)return n}}return undefined}
function textMetric(root,patterns){const txt=String(root?.textContent||'');for(const re of patterns){const m=txt.match(re);if(m){const n=parseCompactCount(m[1]);if(n!==undefined)return n}}return undefined}
function nativeMetrics(root){if(!root)return{};const likes=buttonMetric(root,['좋아요','like','unlike'])??textMetric(root,[/좋아요\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*likes?/i]);const comments=buttonMetric(root,['댓글','comment'])??textMetric(root,[/댓글\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*comments?/i]);const reposts=buttonMetric(root,['재게시','repost'])??textMetric(root,[/재게시\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*reposts?/i]);const time=root.querySelector('time[datetime]')?.getAttribute('datetime')||'';let postedAt='';if(time){const d=new Date(time);if(!Number.isNaN(d.getTime()))postedAt=d.toISOString().slice(0,10)}return{likes,comments,reposts,postedAt}}
function mergeNative(code,root){if(!code||!root)return;const n=nativeMetrics(root),old=metricStore[code]||{shortcode:code,history:[]},patch={shortcode:code,nativeAt:Date.now()};for(const k of ['likes','comments','reposts','postedAt'])if(n[k]!==undefined&&n[k]!=='')patch[k]=n[k];if(Object.keys(patch).length>2)persistMetric({...old,...patch})}
async function resolve(code,kind='p',force=false){if(!code)throw Error('shortcode 없음');if(!force&&cache.has(code))return cache.get(code);let item=null,last=null;try{const vars=encodeURIComponent(JSON.stringify({shortcode:code,__relay_internal__pv__PolarisFeedShareMenurelayprovider:true,__relay_internal__pv__PolarisIsLoggedInrelayprovider:true}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_id=9496392173716084&variables=${vars}`))?.data)}catch(e){last=e}if(!item)try{const vars=encodeURIComponent(JSON.stringify({shortcode:code}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=${vars}`))?.data)}catch(e){last=e}if(!item)try{const j=await sameOriginJson(`/${kind==='reel'?'reel':'p'}/${encodeURIComponent(code)}/?__a=1&__d=dis`);item=normalizeItem(j?.graphql||j)}catch(e){last=e}if(!item)throw last||Error('콘텐츠 원본 정보 없음');const m={code:item?.code||item?.shortcode||code,kind,item,username:usernameOf(item),type:mediaType(item),children:childItems(item)};cache.set(code,m);persistMetric(metricFromItem(item,m.code,kind));refreshVisibleMetrics();return m}
async function resolveCurrent(force=false){const id=currentId();if(!id?.code)throw Error('현재 콘텐츠 shortcode를 찾지 못함');current=await resolve(id.code,id.kind,force);renderSheet();refreshVisibleMetrics();return current}
function base(m){return`IG_${safe(m?.code)}`}
function ext(type,url=''){type=String(type||'').toLowerCase();if(type.includes('png')||/\.png(?:[?#]|$)/i.test(url))return'png';if(type.includes('webp')||/\.webp(?:[?#]|$)/i.test(url))return'webp';if(type.includes('avif')||/\.avif(?:[?#]|$)/i.test(url))return'avif';return'jpg'}
function names(m){return{video:`${base(m)}.mp4`,audio:`${base(m)}_a.m4a`,frame:`${base(m)}_f.jpg`}}
async function fetchMedia(url,min=3000){if(!url)throw Error('원본 URL 없음');const r=await fetch(url,{credentials:'omit',mode:'cors',cache:'force-cache'});if(!r.ok)throw Error(`미디어 HTTP ${r.status}`);const blob=await r.blob();if(blob.size<min)throw Error(`파일이 너무 작음 ${blob.size}B`);return{blob,type:blob.type||r.headers.get('content-type')||'',url}}
function openDb(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function idbPut(k,v){const db=await openDb();try{await new Promise((ok,no)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);q.onsuccess=ok;q.onerror=()=>no(q.error)})}finally{db.close()}}
async function idbGet(k){const db=await openDb();try{return await new Promise((ok,no)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(k);q.onsuccess=()=>ok(q.result||null);q.onerror=()=>no(q.error)})}finally{db.close()}}
async function restoreDir(){try{dirHandle=await idbGet(DIRKEY);renderSheet()}catch{}}
async function chooseDir(){if(typeof showDirectoryPicker!=='function')throw Error('지정 폴더 저장 미지원');dirHandle=await showDirectoryPicker({mode:'readwrite'});await idbPut(DIRKEY,dirHandle);saveMode='folder';localStorage.setItem(MODEKEY,saveMode);renderSheet()}
function setMode(mode){if(mode==='prompt'&&typeof showSaveFilePicker!=='function')throw Error('매번 선택 저장 미지원');saveMode=mode;localStorage.setItem(MODEKEY,mode);renderSheet()}
async function writableDir(){if(!dirHandle)throw Error('저장 폴더를 먼저 지정하세요');let p=typeof dirHandle.queryPermission==='function'?await dirHandle.queryPermission({mode:'readwrite'}):'granted';if(p!=='granted'&&typeof dirHandle.requestPermission==='function')p=await dirHandle.requestPermission({mode:'readwrite'});if(p!=='granted')throw Error('폴더 쓰기 권한 필요');return dirHandle}
async function destination(name){if(saveMode==='folder'){const h=await writableDir();return{kind:'folder',handle:h,label:`지정 폴더/${h.name||''}`}}if(saveMode==='prompt'){const h=await showSaveFilePicker({suggestedName:name});return{kind:'file',handle:h,label:'직접 선택'}}return{kind:'default',label:'기본 다운로드'}}
async function saveBlob(blob,name,dest){dest=dest||await destination(name);if(dest.kind==='folder'){const f=await dest.handle.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(blob);await w.close();return dest.label}if(dest.kind==='file'){const w=await dest.handle.createWritable();await w.write(blob);await w.close();return dest.label}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),12000);return dest.label}
async function firstFrame(url){const x=await fetchMedia(url,50000),u=URL.createObjectURL(x.blob),v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src=u;v.style='position:fixed;left:-9999px;top:-9999px;width:2px;height:2px';document.body.appendChild(v);try{await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('첫 프레임 로드 시간초과')),12000);v.addEventListener('loadeddata',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('영상 로드 실패'))},{once:true})});v.pause();if((v.currentTime||0)!==0){v.currentTime=0;await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('0초 이동 시간초과')),4000);v.addEventListener('seeked',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('0초 이동 실패'))},{once:true})})}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error('JPG 생성 실패')),'image/jpeg',.95))}finally{v.remove();URL.revokeObjectURL(u)}}
async function model(m){return m||current||resolveCurrent()}
function activitySet(kind,state,message,detail=''){activity.kind=kind;activity.state=state;activity.message=message;activity.detail=detail;renderSheet()}
function activityClear(){activity.kind='';activity.state='idle';activity.message='';activity.detail='';renderSheet()}
async function saveVideo(m,dest){const t=performance.now();activitySet('video','running','영상 저장 중');try{m=await model(m);const url=videoUrl(m.item);if(!url)throw Error('소리 포함 원본 영상 URL 없음');const name=names(m).video,d=dest||await destination(name),x=await fetchMedia(url,50000),where=await saveBlob(x.blob,name,d);activitySet('video','success','영상 저장 완료',`${name} · ${((performance.now()-t)/1000).toFixed(1)}초 · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('video','error','영상 저장 실패',err(e));throw e}}
async function saveAudio(m,dest){activitySet('audio','running','음원 저장 중');try{m=await model(m);const url=dashAudio(dash(m.item));if(!url)throw Error('별도 음원 URL 없음');const name=names(m).audio,d=dest||await destination(name),x=await fetchMedia(url,4000),where=await saveBlob(x.blob,name,d);activitySet('audio','success','음원 저장 완료',`${name} · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('audio','error','음원 저장 실패',err(e));throw e}}
async function saveImage(m,dest){activitySet('image','running','이미지 저장 중');try{m=await model(m);const cover=explicitCover(m.item);if(cover){const name=`${base(m)}_c.${ext('',cover)}`,d=dest||await destination(name),x=await fetchMedia(cover,3000),where=await saveBlob(x.blob,name,d);activitySet('image','success','이미지 저장 완료',`${name} · 실제 표지 · ${where}`);return name}const url=videoUrl(m.item);if(!url)throw Error('영상 URL 없음');const name=names(m).frame,d=dest||await destination(name),blob=await firstFrame(url),where=await saveBlob(blob,name,d);activitySet('image','success','이미지 저장 완료',`${name} · 0.000초 · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('image','error','이미지 저장 실패',err(e));throw e}}
async function savePhoto(m,dest){activitySet('photo','running','사진 저장 중');try{m=await model(m);const url=imageUrl(m.item);if(!url)throw Error('원본 사진 URL 없음');const x=await fetchMedia(url,3000),name=`${base(m)}.${ext(x.type,url)}`,d=dest||await destination(name),where=await saveBlob(x.blob,name,d);activitySet('photo','success','사진 저장 완료',`${name} · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('photo','error','사진 저장 실패',err(e));throw e}}
async function saveCarousel(m){activitySet('carousel','running','슬라이드 저장 중');try{m=await model(m);const ch=m.children?.length?m.children:childItems(m.item);if(!ch.length)throw Error('슬라이드 항목 없음');if(saveMode==='prompt')throw Error('슬라이드 전체 저장은 기본 다운로드 또는 지정 폴더를 사용하세요');const dest=saveMode==='folder'?await destination(`${base(m)}_01.jpg`):{kind:'default',label:'기본 다운로드'};let done=0,failed=0,cursor=0;async function worker(){while(true){const i=cursor++;if(i>=ch.length)return;const item=ch[i],n=String(i+1).padStart(2,'0'),vid=isVideo(item),url=vid?videoUrl(item):imageUrl(item);try{const x=await fetchMedia(url,vid?50000:3000),name=vid?`${base(m)}_${n}.mp4`:`${base(m)}_${n}.${ext(x.type,url)}`;await saveBlob(x.blob,name,dest);done++;activitySet('carousel','running',`슬라이드 저장 ${done}/${ch.length}`)}catch{failed++}}}await Promise.all(Array.from({length:Math.min(3,ch.length)},worker));activitySet('carousel',failed?'error':'success',failed?`슬라이드 ${done}/${ch.length}`:`슬라이드 ${done}개 완료`,failed?`실패 ${failed}`:'');return{done,failed}}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('carousel','error','슬라이드 저장 실패',err(e));throw e}}
async function saveVideoSet(m){m=await model(m);let dest=null;if(saveMode==='folder')dest=await destination(names(m).video);const jobs=[['video',()=>saveVideo(m,dest)],['audio',()=>saveAudio(m,dest)],['image',()=>saveImage(m,dest)]],out=[];for(const [name,fn] of jobs){try{out.push({name,status:'fulfilled',value:await fn()})}catch(e){if(e?.name==='AbortError')throw e;out.push({name,status:'rejected',reason:e})}}const ok=out.filter(x=>x.status==='fulfilled').length;activitySet('all3',ok===3?'success':'error',`3개 저장 ${ok}/3`,ok===3?'완료':`실패 ${3-ok}`);return out}
function metricValues(rec){const d=deriveMetric(rec||{});return{views:fmtCount(rec?.views),likes:fmtCount(rec?.likes),comments:fmtCount(rec?.comments),reposts:fmtCount(rec?.reposts),er:fmtPct(d.er),growth:fmtPct(d.growth,true),multiple:fmtMul(d.multiple),date:shortDate(rec?.postedAt)}}
function gridRows(code){const rec=metricStore[code];if(!rec)return{row1:['','','',''],row2:['','','','']};const v=metricValues(rec);return{row1:[v.views?`▶${v.views}`:'',v.likes?`♥${v.likes}`:'',v.comments?`●${v.comments}`:'',v.reposts?`↻${v.reposts}`:''],row2:[v.er?`ER ${v.er}`:'',v.growth?`24h ${v.growth}`:'',v.multiple||'',v.date||'']}}
function gridAnchors(){return [...document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"],a[href*="/tv/"]')].map(a=>{const id=parseHref(a.getAttribute('href')||''),img=a.querySelector('img');if(!id||!img)return null;const w=a.offsetWidth||img.offsetWidth||0,h=a.offsetHeight||img.offsetHeight||0;if(w<70||h<70||w>innerWidth*.52||h>w*1.7)return null;return{a,id}}).filter(Boolean)}
function gridTargetId(){const xs=gridAnchors().map(x=>({...x,r:x.a.getBoundingClientRect()})).filter(x=>x.r.bottom>0&&x.r.top<innerHeight&&x.r.right>0&&x.r.left<innerWidth);if(!xs.length)return null;const cy=innerHeight/2;xs.sort((a,b)=>Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy));return xs[0]?.id||null}
function renderCardMetrics(ui,code){const rows=gridRows(code),box=ui?.querySelector('.ri98-metrics');if(!box)return;box.hidden=false;const els=box.querySelectorAll('.ri98-row');[rows.row1,rows.row2].forEach((vals,j)=>[...els[j].children].forEach((sp,i)=>{sp.textContent=vals[i]||'';sp.classList.toggle('empty',!vals[i])}))}
function removeCardUi(a){a.querySelector(':scope > .ri98-card-ui')?.remove();a.classList.remove('ri98-host')}
function ensureCard(a,id){a.classList.add('ri98-host');let ui=a.querySelector(':scope > .ri98-card-ui');if(!ui){ui=document.createElement('div');ui.className='ri98-card-ui';ui.innerHTML=`<button class="ri98-save" type="button" aria-label="저장">${dlIcon}</button><div class="ri98-metrics"><div class="ri98-row r1"><span></span><span></span><span></span><span></span></div><div class="ri98-row r2"><span></span><span></span><span></span><span></span></div></div>`;a.appendChild(ui);ui.querySelector('.ri98-save').addEventListener('click',onGridSave)}ui.dataset.code=id.code;ui.dataset.kind=id.kind;renderCardMetrics(ui,id.code);const r=a.getBoundingClientRect();if(r.bottom>-innerHeight*.5&&r.top<innerHeight*1.5)queueResolve(id)}
function feedItems(){const out=[];for(const article of document.querySelectorAll('article')){const link=article.querySelector('a[href*="/reel/"],a[href*="/p/"],a[href*="/tv/"]'),id=parseHref(link?.getAttribute('href')||'');if(!id)continue;const media=[...article.querySelectorAll('video,img')].sort((a,b)=>(b.clientWidth*b.clientHeight)-(a.clientWidth*a.clientHeight))[0];if(!media||media.clientWidth<180)continue;out.push({article,id,media})}return out}
function feedTargetId(){const xs=feedItems().map(x=>({...x,r:x.article.getBoundingClientRect()})).filter(x=>x.r.bottom>0&&x.r.top<innerHeight);if(!xs.length)return null;const cy=innerHeight/2;xs.sort((a,b)=>Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy));return xs[0]?.id||null}
function ensureFeed(){const valid=new Set();for(const {article,id,media} of feedItems()){valid.add(article);article.classList.add('ri98-feed-article');mergeNative(id.code,article);let bar=article.querySelector('.ri98-feed');if(!bar){bar=document.createElement('div');bar.className='ri98-feed';bar.innerHTML='<div class="ri98-feed-title">RI</div><div class="ri98-feed-grid"></div>';const host=media.parentElement||article;host.classList.add('ri98-feed-host');host.appendChild(bar)}bar.dataset.code=id.code;renderResearchGrid(bar.querySelector('.ri98-feed-grid'),metricStore[id.code],true);queueResolve(id)}document.querySelectorAll('article.ri98-feed-article').forEach(a=>{if(!valid.has(a))a.querySelector('.ri98-feed')?.remove()})}
function ensureCards(){ensureQueued=false;const xs=gridAnchors(),valid=new Set(xs.map(x=>x.a));document.querySelectorAll('a.ri98-host').forEach(a=>{if(!valid.has(a))removeCardUi(a)});for(const {a,id} of xs)ensureCard(a,id);ensureFeed();syncSurface()}
function scheduleEnsure(){if(ensureQueued)return;ensureQueued=true;requestAnimationFrame(ensureCards)}
function queueResolve(id){if(!id?.code||cache.has(id.code)||pending.has(id.code))return;const rec=metricStore[id.code];if(rec&&Date.now()-Number(rec.apiAt||0)<10*60*1000)return;pending.add(id.code);queue.push(id);pump()}
function pump(){while(workers<2&&queue.length){const id=queue.shift();workers++;resolve(id.code,id.kind).catch(()=>{}).finally(()=>{pending.delete(id.code);workers--;document.querySelectorAll(`.ri98-card-ui[data-code="${id.code}"]`).forEach(ui=>renderCardMetrics(ui,id.code));document.querySelectorAll(`.ri98-feed[data-code="${id.code}"] .ri98-feed-grid`).forEach(g=>renderResearchGrid(g,metricStore[id.code],true));pump()})}}
function onGridSave(e){e.preventDefault();e.stopImmediatePropagation();const b=e.currentTarget,a=b.closest('a'),id=parseHref(a?.getAttribute('href')||'');if(id)openGridMenu(id,b)}
function positionMenu(trigger){if(!menu)return;const r=trigger.getBoundingClientRect(),mr=menu.getBoundingClientRect(),bottomLimit=Math.max(120,innerHeight-78);let left=Math.max(6,Math.min(innerWidth-mr.width-6,r.left)),top=r.bottom+6;if(top+mr.height>bottomLimit)top=Math.max(8,r.top-mr.height-6);menu.style.left=`${left}px`;menu.style.top=`${top}px`}
function addMenuButton(label,fn,wide=false){const b=document.createElement('button');b.textContent=label;if(wide)b.className='wide';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const trigger=menu?.__trigger;closeMenu();try{if(trigger){trigger.innerHTML='<span class="ri98-spinner"></span>';trigger.disabled=true}await fn();if(trigger){trigger.textContent='✓';setTimeout(()=>{trigger.innerHTML=dlIcon;trigger.disabled=false},850)}}catch(x){if(trigger){trigger.textContent=x?.name==='AbortError'?'':'!';if(x?.name==='AbortError')trigger.innerHTML=dlIcon;setTimeout(()=>{trigger.innerHTML=dlIcon;trigger.disabled=false},950)}if(x?.name!=='AbortError')notify('저장에 실패했습니다.')}};menu.appendChild(b)}
function openGridMenu(id,trigger){closeMenu();menu=document.createElement('div');menu.id='ri98-menu';menu.__trigger=trigger;document.documentElement.appendChild(menu);const build=m=>{if(!menu||menu.__trigger!==trigger)return;menu.innerHTML='';current=m;if(m.type==='carousel')addMenuButton('슬라이드 전체',()=>saveCarousel(m),true);else if(m.type==='photo')addMenuButton('원본 사진',()=>savePhoto(m),true);else{addMenuButton('영상',()=>saveVideo(m));addMenuButton('음원',()=>saveAudio(m));addMenuButton('이미지',()=>saveImage(m));addMenuButton('3개 모두',()=>saveVideoSet(m))}positionMenu(trigger)};if(cache.has(id.code)){build(cache.get(id.code));return}const wait=document.createElement('button');wait.className='wide';wait.disabled=true;wait.textContent='콘텐츠 확인 중';menu.appendChild(wait);positionMenu(trigger);resolve(id.code,id.kind).then(build).catch(()=>{if(menu&&menu.__trigger===trigger)wait.textContent='확인할 수 없음'})}
function closeMenu(){menu?.remove();menu=null}
function modeLabel(){return saveMode==='folder'?(dirHandle?.name?`지정 폴더 · ${dirHandle.name}`:'지정 폴더'):saveMode==='prompt'?'매번 선택':'기본 다운로드'}
function currentRecord(){const id=current?.code||routeId()?.code;return id?metricStore[id]||null:null}
function researchCells(rec,placeholder='확인중'){const v=metricValues(rec||{});return metricDefs.map(([key,label])=>({key,label,value:v[key]||placeholder,known:!!v[key]}))}
function renderResearchGrid(el,rec,compact=false){if(!el)return;el.innerHTML=researchCells(rec,compact?'·':'확인중').map(x=>`<div class="${x.known?'known':'pending'}"><span>${x.label}</span><b>${esc(x.value)}</b></div>`).join('')}
function researchGridHtml(rec,cls=''){return`<div class="ri98-research-grid ${cls}">${researchCells(rec).map(x=>`<div class="${x.known?'known':'pending'}"><span>${x.label}</span><b>${esc(x.value)}</b></div>`).join('')}</div>`}
function activityHtml(){if(activity.state==='idle')return'';return`<div class="ri98-activity ${activity.state==='error'?'error':''}"><span class="dot"></span><div><b>${esc(activity.message)}</b>${activity.detail?`<small>${esc(activity.detail)}</small>`:''}</div></div>`}
function typeLabel(){return current?.type==='video'?'Reel/영상':current?.type==='photo'?'사진':current?.type==='carousel'?'슬라이드':'콘텐츠'}
function headHtml(title,back=false){return`<div class="ri98-head">${back?'<button data-a="back" class="icon">‹</button>':''}<div class="ri98-title">${esc(title)}</div><button data-a="close" class="icon">×</button></div>`}
function contentCompactHtml(){const title=current?`${current.username!=='unknown'?'@'+current.username:'RI'} · ${typeLabel()}`:'RI Research';return`${headHtml(title)}<div class="ri98-compact-body">${researchGridHtml(currentRecord(),'compact')}<div class="ri98-command"><button class="primary" data-a="save">저장</button><span class="mode">${esc(modeLabel())}</span><button data-a="detail">상세</button><button data-a="global" class="icon">•••</button></div>${activityHtml()}</div>`}
function tabBar(){const tabs=[['summary','요약'],['content','콘텐츠'],['comments','댓글'],['analysis','분석'],['media','미디어']];return`<div class="ri98-tabs">${tabs.map(([k,l])=>`<button data-tab="${k}" class="${detailTab===k?'active':''}">${l}</button>`).join('')}</div>`}
function summaryTab(){const r=currentRecord();return`<section class="ri98-section"><h3>성과 지표</h3>${researchGridHtml(r,'summary')}</section><section class="ri98-section"><h3>콘텐츠 정보</h3><div class="ri98-info"><div><span>계정</span><b>${esc(current?.username&&current.username!=='unknown'?'@'+current.username:'확인 중')}</b></div><div><span>유형</span><b>${esc(typeLabel())}</b></div><div><span>Shortcode</span><b>${esc(current?.code||'확인 중')}</b></div><div><span>저장 방식</span><b>${esc(modeLabel())}</b></div></div></section>`}
function stateCard(title,status,desc,items=[]){return`<div class="ri98-research-card"><div class="top"><b>${title}</b><span>${status}</span></div>${desc?`<p>${desc}</p>`:''}${items.length?`<div class="ri98-tags">${items.map(x=>`<span>${x}</span>`).join('')}</div>`:''}</div>`}
function contentTab(){return`${researchGridHtml(currentRecord(),'tabtop')}${stateCard('본문','미수집','캡션, 해시태그, 언급 계정을 정리합니다.',['본문','해시태그','언급'])}${stateCard('음성','미수집','STT 전체 문장과 시간대별 문장을 표시합니다.',['전체 STT','타임라인'])}${stateCard('화면 글자','미수집','OCR 문구와 노출 시간·화면 위치를 연결합니다.',['OCR','시간','위치'])}`}
function commentsTab(){return`${researchGridHtml(currentRecord(),'tabtop')}${stateCard('댓글 리서치','미수집','댓글 수집 후 질문·구매의도·긍정·불만·반론·팁을 분류합니다.',['질문','구매의도','긍정','불만','반론','팁/정보'])}${stateCard('원문 / 답글','미수집','댓글 원문과 답글을 스레드 단위로 확인합니다.')}`}
function analysisTab(){return`${researchGridHtml(currentRecord(),'tabtop')}${stateCard('시작부','분석 전','첫 1~3초의 훅과 첫 핵심 메시지를 정리합니다.',['시작 훅','첫 메시지'])}${stateCard('구성','분석 전','도입→전개→핵심→마무리 흐름을 구조화합니다.',['도입','전개','핵심','마무리'])}${stateCard('표현 / 전환','분석 전','CTA, 강조 문구, 숫자·가격과 반응 특징을 묶습니다.',['CTA','강조','숫자','가격'])}`}
function mediaTab(){const metrics=researchGridHtml(currentRecord(),'tabtop');if(!current)return metrics+'<div class="ri98-empty">현재 콘텐츠를 확인하고 있습니다.</div>';if(current.type==='video')return metrics+`<div class="ri98-media-card"><div><b>영상</b><span>원본 MP4</span></div><button data-a="video">저장</button></div><div class="ri98-media-card"><div><b>음원</b><span>분리 오디오</span></div><button data-a="audio">저장</button></div><div class="ri98-media-card"><div><b>이미지</b><span>실제 표지 / 0.000초 프레임</span></div><button data-a="image">저장</button></div>`;if(current.type==='photo')return metrics+`<div class="ri98-media-card"><div><b>원본 사진</b><span>최대 해상도</span></div><button data-a="photo">저장</button></div>`;return metrics+`<div class="ri98-media-card"><div><b>슬라이드 전체</b><span>${current.children?.length||''}개 원본 개별 저장</span></div><button data-a="carousel">저장</button></div>`}
function detailBody(){return detailTab==='summary'?summaryTab():detailTab==='content'?contentTab():detailTab==='comments'?commentsTab():detailTab==='analysis'?analysisTab():mediaTab()}
function detailHtml(){const title=current?`${current.username!=='unknown'?'@'+current.username:'RI'} · ${typeLabel()}`:'RI Research';return`${headHtml(title,true)}${tabBar()}<div class="ri98-detail-body">${detailBody()}${activityHtml()}</div>`}
function listRow(icon,title,sub,value,action,disabled=false){return`<button ${disabled?'disabled':''} data-a="${action||''}" class="ri98-list-row"><span class="ri98-row-icon">${icon}</span><span class="ri98-row-copy"><b>${title}</b><small>${sub||''}</small></span>${value?`<span class="ri98-row-value">${esc(value)}</span>`:''}${!disabled&&action?'<span class="ri98-chevron">›</span>':''}</button>`}
function globalHtml(){return`${headHtml('RI 관리',true)}<div class="ri98-list"><div class="ri98-list-label">관리</div>${listRow('⇩','저장','다운로드 위치와 저장 방식',modeLabel(),'storage')}${listRow('▤','데이터','수집된 성과 기록과 history',`${Object.keys(metricStore).length}개`,'data')}${listRow('◎','리서치 설정','댓글 · STT · OCR · 분석','준비','research')}${listRow('↻','업데이트',`현재 v${V}`,'','update')}<div class="ri98-list-label">시스템</div>${listRow('⎘','진단 복사','현재 상태를 클립보드로','','copy')}${listRow('×','RI 종료','현재 페이지에서 RI 제거','','destroy')}</div>`}
function storageHtml(){return`${headHtml('저장 방식',true)}<div class="ri98-choice-list"><button data-a="default" class="${saveMode==='default'?'active':''}"><div><b>기본 다운로드</b><small>브라우저 기본 다운로드 위치</small></div><span>${saveMode==='default'?'✓':''}</span></button><button data-a="folder" class="${saveMode==='folder'?'active':''}"><div><b>지정 폴더</b><small>${esc(dirHandle?.name||'한 번 지정하면 다시 사용')}</small></div><span>${saveMode==='folder'?'✓':''}</span></button><button data-a="prompt" class="${saveMode==='prompt'?'active':''}" ${typeof showSaveFilePicker!=='function'?'disabled':''}><div><b>매번 선택</b><small>저장할 때 파일 위치 선택</small></div><span>${saveMode==='prompt'?'✓':''}</span></button></div>`}
function dataHtml(){const recs=Object.values(metricStore),snaps=recs.reduce((s,x)=>s+(x.history?.length||0),0),accounts=new Set(recs.map(x=>x.username).filter(Boolean)).size;return`${headHtml('데이터',true)}<div class="ri98-data-summary"><div><b>${recs.length}</b><span>콘텐츠</span></div><div><b>${snaps}</b><span>Snapshots</span></div><div><b>${accounts}</b><span>계정</span></div></div><div class="ri98-note">북마클릿 전용 저장공간입니다. 확장프로그램 데이터와 공유하지 않습니다.</div>`}
function researchHtml(){return`${headHtml('리서치 설정',true)}<div class="ri98-list">${listRow('C','댓글','댓글·답글 수집과 반응 분류','향후','',true)}${listRow('S','STT','음성 전체 및 시간대별 문장','향후','',true)}${listRow('O','OCR','화면 문구·시간·위치','향후','',true)}${listRow('A','분석','훅·구성·CTA·반응','향후','',true)}</div>`}
function renderSheet(){if(!sheet||sheet.hidden)return;sheet.dataset.mode=sheetMode;sheet.dataset.view=sheetView;if(sheetView==='content'&&sheetMode==='compact')sheet.innerHTML=contentCompactHtml();else if(sheetView==='detail')sheet.innerHTML=detailHtml();else if(sheetView==='global')sheet.innerHTML=globalHtml();else if(sheetView==='storage')sheet.innerHTML=storageHtml();else if(sheetView==='data')sheet.innerHTML=dataHtml();else if(sheetView==='research')sheet.innerHTML=researchHtml()}
function openSheet(view='content',mode='compact'){sheetView=view;sheetMode=mode;sheet.hidden=false;if(launcher)launcher.hidden=true;closeMenu();renderSheet();scanQuiet()}
function closeSheet(){sheet.hidden=true;if(launcher){launcher.hidden=false;syncSurface()}}
function backSheet(){if(['storage','data','research'].includes(sheetView)){sheetView='global';sheetMode='panel'}else if(sheetView==='global'||sheetView==='detail'){sheetView='content';sheetMode='compact'}renderSheet()}
function openSaveMenu(trigger){const id=currentId();if(id?.code)openGridMenu(id,trigger)}
async function copyDiag(){const text=JSON.stringify({version:V,url:location.href,current:current?{code:current.code,type:current.type,username:current.username}:null,saveMode,activity,metricCount:Object.keys(metricStore).length},null,2);await navigator.clipboard?.writeText?.(text);notify('진단을 복사했습니다.')}
async function sheetAct(a,target){try{if(a==='close')closeSheet();else if(a==='back')backSheet();else if(a==='detail'){sheetView='detail';sheetMode='expanded';detailTab='summary';renderSheet()}else if(a==='global'){sheetView='global';sheetMode='panel';renderSheet()}else if(a==='save')openSaveMenu(target);else if(a==='storage'){sheetView='storage';renderSheet()}else if(a==='data'){sheetView='data';renderSheet()}else if(a==='research'){sheetView='research';renderSheet()}else if(a==='video')await saveVideo();else if(a==='audio')await saveAudio();else if(a==='image')await saveImage();else if(a==='photo')await savePhoto();else if(a==='carousel')await saveCarousel();else if(a==='default')setMode('default');else if(a==='folder')await chooseDir();else if(a==='prompt')setMode('prompt');else if(a==='update'){if(typeof window.__RI_LOADER_REFRESH==='function')window.__RI_LOADER_REFRESH();else notify('업데이트 기능을 찾지 못했습니다.')}else if(a==='copy')await copyDiag();else if(a==='destroy')destroy()}catch(e){if(e?.name!=='AbortError')notify('작업을 완료하지 못했습니다.')}}
function notify(msg){if(!msg)return;toast?.remove();toast=document.createElement('div');toast.id='ri98-toast';toast.textContent=msg;document.documentElement.appendChild(toast);setTimeout(()=>{toast?.remove();toast=null},1900)}
function currentReelRoot(){const videos=[...document.querySelectorAll('video')].map(v=>({v,r:v.getBoundingClientRect()})).filter(x=>x.r.width>150&&x.r.height>200&&x.r.bottom>0&&x.r.top<innerHeight).sort((a,b)=>(b.r.width*b.r.height)-(a.r.width*a.r.height));let n=videos[0]?.v||null;for(let i=0;n&&i<6;i++,n=n.parentElement){if(n.querySelectorAll?.('button,[role="button"]').length>=3)return n}return videos[0]?.v?.parentElement||document.body}
function renderReelMetrics(){if(!reelMetrics)return;const id=routeId();if(!id||id.kind!=='reel'){reelMetrics.hidden=true;return}const root=currentReelRoot();mergeNative(id.code,root);const rec=metricStore[id.code];if(!rec){reelMetrics.hidden=false;renderResearchGrid(reelMetrics,null,true);queueResolve(id);return}reelMetrics.hidden=false;renderResearchGrid(reelMetrics,rec,true)}
function refreshVisibleMetrics(){document.querySelectorAll('.ri98-card-ui').forEach(ui=>renderCardMetrics(ui,ui.dataset.code));document.querySelectorAll('.ri98-feed').forEach(bar=>renderResearchGrid(bar.querySelector('.ri98-feed-grid'),metricStore[bar.dataset.code],true));renderReelMetrics();if(!sheet?.hidden)renderSheet()}
function syncSurface(){if(!launcher)return;const reel=/^\/reels?(?:\/|$)/i.test(location.pathname);launcher.classList.toggle('reel',reel);renderReelMetrics();const sig=location.pathname+location.search;if(sig!==routeTick){routeTick=sig;const id=routeId();if(id)queueResolve(id);if(!sheet?.hidden)scanQuiet()}}
function scanQuiet(){const id=currentId();if(!id?.code){current=null;if(!sheet?.hidden)renderSheet();return}if(id.kind==='reel')mergeNative(id.code,currentReelRoot());resolveCurrent(false).catch(()=>{current=cache.get(id.code)||current;if(!sheet?.hidden)renderSheet()})}
function injectCss(){if(document.getElementById('ri98-style'))return;const s=document.createElement('style');s.id='ri98-style';s.textContent=`
.ri98-host{position:relative!important}.ri98-card-ui{position:absolute;inset:0;pointer-events:none;overflow:hidden}.ri98-save{position:absolute;left:4px;top:4px;width:25px;height:25px;padding:0;border:1px solid rgba(255,255,255,.48);border-radius:50%;background:rgba(0,0,0,.32);color:#fff;display:grid;place-items:center;pointer-events:auto;box-shadow:0 1px 3px rgba(0,0,0,.32);-webkit-tap-highlight-color:transparent}.ri98-save svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.ri98-save:active{transform:scale(.94);background:rgba(0,0,0,.58)}.ri98-spinner{width:11px;height:11px;border:2px solid rgba(255,255,255,.35);border-top-color:#fff;border-radius:50%;animation:ri98spin .7s linear infinite}@keyframes ri98spin{to{transform:rotate(360deg)}}
.ri98-metrics{position:absolute;left:0;right:0;bottom:0;padding:17px 4px 4px;background:linear-gradient(to bottom,transparent,rgba(0,0,0,.62));pointer-events:none}.ri98-row{position:relative;width:100%;height:11px;white-space:nowrap}.ri98-row span{position:absolute;top:0;height:11px;line-height:11px;overflow:hidden;text-align:center;font-variant-numeric:tabular-nums;letter-spacing:-.45px;padding:0 1px;box-sizing:border-box}.ri98-row.r1 span{color:#fff;font:800 9.5px/11px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;text-shadow:0 1px 2px #000,0 0 3px #000}.ri98-row.r2 span{color:#fff;font:760 8.2px/11px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;text-shadow:0 1px 2px #000,0 0 2px #000}.ri98-row span:nth-child(1){left:0;width:31%;text-align:left}.ri98-row span:nth-child(2){left:31%;width:27%}.ri98-row span:nth-child(3){left:58%;width:21%}.ri98-row span:nth-child(4){left:79%;width:21%;text-align:right}.ri98-row.r2 span:nth-child(1){left:0;width:27%}.ri98-row.r2 span:nth-child(2){left:27%;width:25%}.ri98-row.r2 span:nth-child(3){left:52%;width:24%}.ri98-row.r2 span:nth-child(4){left:76%;width:24%}.ri98-row span.empty{opacity:0}
#ri98-menu{position:fixed;z-index:2147483646;width:172px;padding:5px;border:1px solid rgba(255,255,255,.15);border-radius:14px;background:rgba(18,18,20,.95);box-shadow:0 8px 22px rgba(0,0,0,.34);display:grid;grid-template-columns:1fr 1fr;gap:4px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}#ri98-menu button{height:35px;border:0;border-radius:9px;background:rgba(255,255,255,.07);color:#fff;font:700 10.5px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}#ri98-menu .wide{grid-column:1/-1}
#ri98-launcher{position:fixed;right:12px;bottom:max(88px,calc(env(safe-area-inset-bottom) + 78px));z-index:2147483643;width:36px;height:36px;border:1px solid rgba(255,255,255,.32);border-radius:50%;background:rgba(15,15,16,.56);color:#fff;display:grid;place-items:center;font:850 10px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;box-shadow:0 2px 7px rgba(0,0,0,.34)}#ri98-launcher[hidden]{display:none}#ri98-launcher.reel{left:12px;right:auto;bottom:max(142px,calc(env(safe-area-inset-bottom) + 132px))}
#ri98-reel-metrics{position:fixed;left:10px;right:72px;top:max(10px,env(safe-area-inset-top));z-index:2147483500;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-radius:11px;background:linear-gradient(90deg,rgba(0,0,0,.42),rgba(0,0,0,.20));backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);pointer-events:none;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;font-variant-numeric:tabular-nums;overflow:hidden}#ri98-reel-metrics[hidden]{display:none}#ri98-reel-metrics>div{height:31px;padding:4px 5px;box-sizing:border-box;display:grid;align-content:center;gap:1px;border-right:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.07)}#ri98-reel-metrics span{font-size:7.2px;font-weight:680;color:rgba(255,255,255,.62)}#ri98-reel-metrics b{font-size:10px;line-height:1;font-weight:820;text-shadow:0 1px 2px #000;white-space:nowrap;overflow:hidden;text-overflow:clip}#ri98-reel-metrics .pending b{opacity:.35}
.ri98-feed-host{position:relative!important}.ri98-feed{position:absolute;left:7px;right:7px;bottom:7px;z-index:7;padding:5px 6px 6px;border-radius:11px;background:rgba(0,0,0,.46);backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);pointer-events:none;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-feed-title{font-size:7px;font-weight:850;opacity:.65;margin-bottom:3px}.ri98-feed-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:3px 6px}.ri98-feed-grid div{min-width:0;display:flex;gap:3px;align-items:baseline}.ri98-feed-grid span{font-size:7px;opacity:.55;white-space:nowrap}.ri98-feed-grid b{font-size:9.2px;white-space:nowrap;overflow:hidden;text-overflow:clip}.ri98-feed-grid .pending b{opacity:.25}
#ri98-sheet{position:fixed;z-index:2147483646;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;overflow:hidden;box-shadow:0 -8px 28px rgba(0,0,0,.30);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}#ri98-sheet[hidden]{display:none}#ri98-sheet[data-mode="compact"]{left:6px;right:6px;bottom:max(6px,env(safe-area-inset-bottom));max-height:146px;border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(18,18,20,.94)}#ri98-sheet[data-mode="expanded"]{left:0;right:0;bottom:0;height:auto;max-height:min(78vh,680px);border-top:1px solid rgba(255,255,255,.12);border-radius:20px 20px 0 0;background:rgba(18,18,20,.96);padding-bottom:env(safe-area-inset-bottom)}#ri98-sheet[data-mode="panel"]{left:6px;right:6px;bottom:max(6px,env(safe-area-inset-bottom));height:auto;max-height:min(70vh,600px);border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(18,18,20,.96)}.ri98-head{height:36px;display:flex;align-items:center;gap:4px;padding:0 7px 0 11px;border-bottom:1px solid rgba(255,255,255,.07)}.ri98-title{flex:1;min-width:0;font-size:12px;font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ri98-head button,.ri98-command button{border:0;background:transparent;color:#fff}.ri98-head .icon,.ri98-command .icon{min-width:32px;height:32px;border-radius:10px;font-size:16px}.ri98-compact-body{padding:6px 9px 8px}.ri98-research-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.ri98-research-grid>div{min-width:0;padding:6px 5px;border-radius:9px;background:rgba(255,255,255,.052);display:grid;gap:2px}.ri98-research-grid span{font-size:7.4px;color:rgba(255,255,255,.48);white-space:nowrap}.ri98-research-grid b{font-size:10.2px;line-height:1.05;font-weight:820;white-space:nowrap;overflow:hidden;text-overflow:clip}.ri98-research-grid .pending b{font-size:8px;font-weight:650;color:rgba(255,255,255,.28)}.ri98-research-grid.compact>div{padding:4px 4px}.ri98-research-grid.compact b{font-size:9.5px}.ri98-command{display:flex;align-items:center;gap:5px;margin-top:6px}.ri98-command .mode{flex:1;min-width:0;font-size:8px;color:rgba(255,255,255,.40);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ri98-command button{height:32px;padding:0 10px;border-radius:10px;background:rgba(255,255,255,.07);font:720 10.2px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-command .primary{background:#fff;color:#111;font-weight:840;min-width:70px}.ri98-activity{display:flex;align-items:center;gap:7px;margin-top:5px;padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.055)}.ri98-activity .dot{width:5px;height:5px;border-radius:50%;background:#fff}.ri98-activity div{display:grid}.ri98-activity b{font-size:9px}.ri98-activity small{font-size:8px;color:rgba(255,255,255,.46)}
.ri98-tabs{height:38px;display:flex;align-items:flex-end;gap:1px;padding:0 7px;border-bottom:1px solid rgba(255,255,255,.07);overflow-x:auto}.ri98-tabs button{height:35px;padding:0 10px;border:0;border-bottom:2px solid transparent;background:transparent;color:rgba(255,255,255,.50);font:720 10.5px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-tabs button.active{color:#fff;border-bottom-color:#fff}.ri98-detail-body{max-height:calc(78vh - 78px);overflow:auto;padding:9px 11px 14px;overscroll-behavior:contain}.ri98-section+.ri98-section{margin-top:12px}.ri98-section h3{margin:0 0 7px;font-size:9px;color:rgba(255,255,255,.46);letter-spacing:.2px}.ri98-research-grid.summary>div{padding:8px 6px}.ri98-research-grid.summary b{font-size:11px}.ri98-research-grid.tabtop{margin-bottom:10px}.ri98-info{border-top:1px solid rgba(255,255,255,.065)}.ri98-info div{min-height:34px;display:flex;align-items:center;border-bottom:1px solid rgba(255,255,255,.055)}.ri98-info span{flex:1;font-size:9.2px;color:rgba(255,255,255,.44)}.ri98-info b{font-size:10.3px}.ri98-empty{padding:10px 2px;color:rgba(255,255,255,.44);font-size:9.7px}.ri98-research-card{padding:10px 11px;margin-bottom:7px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.03)}.ri98-research-card .top{display:flex;align-items:center}.ri98-research-card .top b{flex:1;font-size:10.8px}.ri98-research-card .top span{font-size:8.7px;color:rgba(255,255,255,.40)}.ri98-research-card p{margin:6px 0 0;color:rgba(255,255,255,.48);font-size:9.2px;line-height:1.45}.ri98-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.ri98-tags span{padding:4px 7px;border-radius:8px;background:rgba(255,255,255,.052);font-size:8.2px;color:rgba(255,255,255,.58)}.ri98-media-card{min-height:48px;display:flex;align-items:center;gap:8px;border-bottom:1px solid rgba(255,255,255,.06)}.ri98-media-card div{flex:1;display:grid;gap:2px}.ri98-media-card b{font-size:10.8px}.ri98-media-card span{font-size:8.8px;color:rgba(255,255,255,.42)}.ri98-media-card button{height:31px;padding:0 10px;border:1px solid rgba(255,255,255,.10);border-radius:9px;background:rgba(255,255,255,.06);color:#fff;font:700 9.8px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}
.ri98-list{max-height:calc(70vh - 42px);overflow:auto;padding:2px 10px 11px}.ri98-list-label{padding:8px 2px 4px;color:rgba(255,255,255,.34);font-size:8.3px;font-weight:750}.ri98-list-row{width:100%;min-height:46px;padding:0 2px;border:0;border-bottom:1px solid rgba(255,255,255,.055);background:transparent;color:#fff;display:flex;align-items:center;text-align:left;font-family:inherit}.ri98-list-row:disabled{opacity:.40}.ri98-row-icon{width:28px;height:28px;margin-right:9px;border-radius:9px;background:rgba(255,255,255,.052);display:grid;place-items:center;font-size:10.5px;font-weight:800}.ri98-row-copy{flex:1;min-width:0;display:grid;gap:2px}.ri98-row-copy b{font-size:10.8px}.ri98-row-copy small{font-size:8.5px;color:rgba(255,255,255,.41);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri98-row-value{font-size:9.2px;color:rgba(255,255,255,.46);max-width:100px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri98-chevron{font-size:18px;color:rgba(255,255,255,.27);margin-left:8px}.ri98-choice-list{padding:6px 10px 11px}.ri98-choice-list button{width:100%;min-height:49px;margin-bottom:6px;padding:0 11px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.028);color:#fff;display:flex;align-items:center;text-align:left}.ri98-choice-list button.active{border-color:rgba(255,255,255,.26);background:rgba(255,255,255,.07)}.ri98-choice-list button div{flex:1;display:grid;gap:2px}.ri98-choice-list b{font-size:10.8px}.ri98-choice-list small{font-size:8.7px;color:rgba(255,255,255,.41)}.ri98-choice-list span{font-size:13px}.ri98-data-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:8px 10px}.ri98-data-summary div{padding:9px 5px;border-radius:10px;background:rgba(255,255,255,.05);display:grid;gap:2px;text-align:center}.ri98-data-summary b{font-size:12px}.ri98-data-summary span{font-size:7.8px;color:rgba(255,255,255,.43)}.ri98-note{margin:0 10px 11px;padding:9px 10px;border-radius:10px;background:rgba(255,255,255,.032);color:rgba(255,255,255,.46);font-size:9.2px;line-height:1.5}
#ri98-toast{position:fixed;left:50%;top:max(12px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;max-width:82vw;padding:7px 11px;border-radius:13px;background:rgba(20,20,20,.94);color:#fff;font:700 10px/1.3 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;box-shadow:0 4px 14px rgba(0,0,0,.28);pointer-events:none}
`;document.documentElement.appendChild(s)}
function onScroll(){closeMenu();scheduleEnsure();syncSurface()}function onResize(){closeMenu();scheduleEnsure();syncSurface()}
function ui(){injectCss();launcher=document.createElement('button');launcher.id='ri98-launcher';launcher.textContent='RI';launcher.setAttribute('aria-label','RI Research');launcher.onclick=()=>openSheet('content','compact');document.documentElement.appendChild(launcher);reelMetrics=document.createElement('div');reelMetrics.id='ri98-reel-metrics';reelMetrics.hidden=true;document.documentElement.appendChild(reelMetrics);sheet=document.createElement('div');sheet.id='ri98-sheet';sheet.hidden=true;sheet.addEventListener('click',e=>{const tab=e.target?.closest?.('[data-tab]')?.dataset?.tab;if(tab){detailTab=tab;renderSheet();return}const el=e.target?.closest?.('[data-a]');if(el)sheetAct(el.dataset.a,el)});document.documentElement.appendChild(sheet);syncSurface()}
function destroy(){try{obs?.disconnect();closeMenu();sheet?.remove();launcher?.remove();toast?.remove();reelMetrics?.remove();document.getElementById('ri98-style')?.remove();document.querySelectorAll('a.ri98-host').forEach(removeCardUi);document.querySelectorAll('.ri98-feed').forEach(x=>x.remove());window.removeEventListener('scroll',onScroll,true);window.removeEventListener('resize',onResize,true)}catch{}delete window[K]}
ui();restoreDir();ensureCards();scanQuiet();obs=new MutationObserver(scheduleEnsure);obs.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['href','datetime']});window.addEventListener('scroll',onScroll,true);window.addEventListener('resize',onResize,true);try{document.getElementById('__ri_update_btn')?.style.setProperty('display','none','important')}catch{}
window[K]={version:V,scan:resolveCurrent,open:openSheet,close:closeSheet,destroy,saveVideo,saveAudio,saveImage,savePhoto,saveCarousel,saveVideoSet,metrics:()=>metricStore};
})();