(()=>{
const K='__RISAVE095',V='0.9.5',DB='ri-bookmarklet',STORE='handles',DIRKEY='instagram-download-dir',MODEKEY='riSaveMode';
for(const k of ['__RISAVE094','__RISAVE093','__RISAVE092','__RISAVE091','__RISAVE090','__RISAVE089','__RISAVE088','__RISAVE087','__RISAVE086','__RISAVE085','__RISAVE084','__RISAVE083'])try{window[k]?.destroy?.()}catch{}
let sheet,launcher,toast,menu,obs,dirHandle=null,current=null,saveMode=localStorage.getItem(MODEKEY)||'default',sheetMode='compact',sheetView='content',sheetBack='content',detailTab='summary',ensureQueued=false;
const cache=new Map(),activity={kind:'',state:'idle',message:'',detail:''};
const safe=s=>String(s||'x').normalize('NFKC').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,40)||'x';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const err=e=>`${e?.name||'Error'}: ${e?.message||e||''}`;
const dlIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 18v2h14v-2"/></svg>';
function parseHref(h){const m=String(h||'').match(/\/(reels?|p|tv)\/([^/?#]+)/i);return m?{kind:/reels?/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}:null}
function routeId(){try{return parseHref(location.pathname)}catch{return null}}
function currentId(){return routeId()||gridTargetId()}
function appId(){for(const s of document.querySelectorAll('script[type="application/json"]')){const m=(s.textContent||'').match(/"APP_ID":"?(\d+)"?/i);if(m)return m[1]}return'936619743392459'}
async function sameOriginJson(url){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{'X-IG-App-ID':appId(),'Accept':'*/*'}});if(!r.ok)throw Error(`Instagram API ${r.status}`);return r.json()}
function normalizeItem(x){if(!x)return null;if(x.xdt_api__v1__media__shortcode__web_info?.items?.[0])return x.xdt_api__v1__media__shortcode__web_info.items[0];if(x.items?.[0])return x.items[0];if(x.shortcode_media)return x.shortcode_media;return x}
function usernameOf(i){return i?.user?.username||i?.owner?.username||i?.owner?.user?.username||i?.username||'unknown'}
function childItems(i){if(Array.isArray(i?.carousel_media))return i.carousel_media;if(Array.isArray(i?.edge_sidecar_to_children?.edges))return i.edge_sidecar_to_children.edges.map(e=>e?.node).filter(Boolean);if(Array.isArray(i?.children))return i.children;return[]}
function videoVersions(i){const a=Array.isArray(i?.video_versions)?i.video_versions:[],b=Array.isArray(i?.video_resources)?i.video_resources.map(x=>({url:x.src,width:x.config_width||x.width,height:x.config_height||x.height})):[];return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function videoUrl(i){return videoVersions(i)[0]?.url||i?.video_url||''}
function imageCandidates(i){const a=Array.isArray(i?.image_versions2?.candidates)?i.image_versions2.candidates:[],b=[];if(i?.display_url)b.push({url:i.display_url,width:i.dimensions?.width,height:i.dimensions?.height});if(i?.display_resources)for(const x of i.display_resources)b.push({url:x.src,width:x.config_width,height:x.config_height});return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function imageUrl(i){return imageCandidates(i)[0]?.url||''}
function explicitCover(i){return i?.cover_frame_url||i?.cover_url||i?.clips_metadata?.cover_frame_url||i?.clips_metadata?.cover_media?.image_versions2?.candidates?.[0]?.url||''}
function isVideo(i){return !!(videoUrl(i)||i?.is_video||Number(i?.media_type)===2||/video|clips|reel/i.test(String(i?.product_type||i?.__typename||'')))}
function mediaType(i){const ch=childItems(i);if(ch.length>1||Number(i?.media_type)===8||/sidecar/i.test(String(i?.__typename||'')))return'carousel';return isVideo(i)?'video':'photo'}
function dash(i){return i?.video_dash_manifest||i?.dash_info?.video_dash_manifest||''}
function dashAudio(xml){if(!xml)return'';try{const doc=new DOMParser().parseFromString(xml,'application/xml'),xs=[...doc.querySelectorAll('Representation')].map(rep=>{const a=rep.closest('AdaptationSet'),mime=rep.getAttribute('mimeType')||a?.getAttribute('mimeType')||'',type=a?.getAttribute('contentType')||'',bw=+(rep.getAttribute('bandwidth')||0),url=rep.querySelector('BaseURL')?.textContent?.trim()||'';return{mime,type,bw,url}}).filter(x=>x.url&&(x.mime.startsWith('audio')||x.type==='audio'));return xs.sort((a,b)=>b.bw-a.bw)[0]?.url||''}catch{return''}}
async function resolve(code,kind='p',force=false){if(!code)throw Error('shortcode 없음');if(!force&&cache.has(code))return cache.get(code);let item=null,last=null;try{const vars=encodeURIComponent(JSON.stringify({shortcode:code,__relay_internal__pv__PolarisFeedShareMenurelayprovider:true,__relay_internal__pv__PolarisIsLoggedInrelayprovider:true}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_id=9496392173716084&variables=${vars}`))?.data)}catch(e){last=e}if(!item)try{const vars=encodeURIComponent(JSON.stringify({shortcode:code}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=${vars}`))?.data)}catch(e){last=e}if(!item)try{const j=await sameOriginJson(`/${kind==='reel'?'reel':'p'}/${encodeURIComponent(code)}/?__a=1&__d=dis`);item=normalizeItem(j?.graphql||j)}catch(e){last=e}if(!item)throw last||Error('콘텐츠 원본 정보 없음');const m={code:item?.code||item?.shortcode||code,kind,item,username:usernameOf(item),type:mediaType(item),children:childItems(item)};cache.set(code,m);return m}
async function resolveCurrent(force=false){const id=currentId();if(!id?.code)throw Error('현재 콘텐츠 shortcode를 찾지 못함');current=await resolve(id.code,id.kind,force);renderSheet();return current}
function base(m){return`IG_${safe(m?.code)}`}
function ext(type,url=''){type=String(type||'').toLowerCase();if(type.includes('png')||/\.png(?:[?#]|$)/i.test(url))return'png';if(type.includes('webp')||/\.webp(?:[?#]|$)/i.test(url))return'webp';if(type.includes('avif')||/\.avif(?:[?#]|$)/i.test(url))return'avif';return'jpg'}
function names(m){return{video:`${base(m)}.mp4`,audio:`${base(m)}_a.m4a`,frame:`${base(m)}_f.jpg`}}
async function fetchMedia(url,min=3000){if(!url)throw Error('원본 URL 없음');const r=await fetch(url,{credentials:'omit',mode:'cors',cache:'force-cache'});if(!r.ok)throw Error(`미디어 HTTP ${r.status}`);const blob=await r.blob();if(blob.size<min)throw Error(`파일이 너무 작음 ${blob.size}B`);return{blob,type:blob.type||r.headers.get('content-type')||'',url}}
function openDb(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function idbPut(k,v){const db=await openDb();try{await new Promise((ok,no)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);q.onsuccess=ok;q.onerror=()=>no(q.error)})}finally{db.close()}}
async function idbGet(k){const db=await openDb();try{return await new Promise((ok,no)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(k);q.onsuccess=()=>ok(q.result||null);q.onerror=()=>no(q.error)})}finally{db.close()}}
async function restoreDir(){try{dirHandle=await idbGet(DIRKEY);renderSheet()}catch{}}
async function chooseDir(){if(typeof showDirectoryPicker!=='function')throw Error('지정 폴더 저장 미지원');dirHandle=await showDirectoryPicker({mode:'readwrite'});await idbPut(DIRKEY,dirHandle);saveMode='folder';localStorage.setItem(MODEKEY,saveMode);renderSheet()}
function setMode(mode){if(mode==='prompt'&&typeof showSaveFilePicker!=='function')throw Error('매번 선택 저장 미지원');saveMode=mode;localStorage.setItem(MODEKEY,mode);renderSheet()}
async function writableDir(){if(!dirHandle)throw Error('저장 폴더를 먼저 지정하세요');let p=typeof dirHandle.queryPermission==='function'?await dirHandle.queryPermission({mode:'readwrite'}):'granted';if(p!=='granted'&&typeof dirHandle.requestPermission==='function')p=await dirHandle.requestPermission({mode:'readwrite'});if(p!=='granted')throw Error('폴더 쓰기 권한 필요');return dirHandle}
async function destination(name){if(saveMode==='folder'){const h=await writableDir();return{kind:'folder',handle:h,label:`지정 폴더/${h.name||''}`}}if(saveMode==='prompt'){const h=await showSaveFilePicker({suggestedName:name});return{kind:'file',handle:h,label:'직접 선택'}}return{kind:'default',label:'기본 다운로드'}}
async function saveBlob(blob,name,dest){dest=dest||await destination(name);if(dest.kind==='folder'){const f=await dest.handle.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(blob);await w.close();return dest.label}if(dest.kind==='file'){const w=await dest.handle.createWritable();await w.write(blob);await w.close();return dest.label}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),12000);return dest.label}
async function firstFrame(url){const x=await fetchMedia(url,50000),u=URL.createObjectURL(x.blob),v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src=u;v.style='position:fixed;left:-9999px;top:-9999px;width:2px;height:2px';document.body.appendChild(v);try{await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('첫 프레임 로드 시간초과')),12000);v.addEventListener('loadeddata',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('영상 로드 실패'))},{once:true})});v.pause();if((v.currentTime||0)!==0){v.currentTime=0;await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('0초 이동 시간초과')),4000);v.addEventListener('seeked',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('0초 이동 실패'))},{once:true})})}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error('JPG 생성 실패')),'image/jpeg',.95))}finally{v.remove();URL.revokeObjectURL(u)}}
async function model(m){return m||current||resolveCurrent()}
function activitySet(kind,state,message,detail=''){activity.kind=kind;activity.state=state;activity.message=message;activity.detail=detail;renderSheet()}
function activityClear(){activity.kind='';activity.state='idle';activity.message='';activity.detail='';renderSheet()}
async function saveVideo(m,dest){const t=performance.now();activitySet('video','running','영상 저장 중');try{m=await model(m);const url=videoUrl(m.item);if(!url)throw Error('소리 포함 원본 영상 URL 없음');const name=names(m).video,d=dest||await destination(name),x=await fetchMedia(url,50000),where=await saveBlob(x.blob,name,d);activitySet('video','success','영상 저장 완료',`${name} · ${((performance.now()-t)/1000).toFixed(1)}초 · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('video','error','영상 저장 실패',err(e));throw e}}
async function saveAudio(m,dest){activitySet('audio','running','음원 저장 중');try{m=await model(m);const url=dashAudio(dash(m.item));if(!url)throw Error('별도 음원 URL 없음');const name=names(m).audio,d=dest||await destination(name),x=await fetchMedia(url,4000),where=await saveBlob(x.blob,name,d);activitySet('audio','success','음원 저장 완료',`${name} · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('audio','error','음원 저장 실패',err(e));throw e}}
async function saveImage(m,dest){activitySet('image','running','이미지 저장 중');try{m=await model(m);const cover=explicitCover(m.item);if(cover){const name=`${base(m)}_c.${ext('',cover)}`,d=dest||await destination(name),x=await fetchMedia(cover,3000),where=await saveBlob(x.blob,name,d);activitySet('image','success','이미지 저장 완료',`${name} · 실제 표지 · ${where}`);return name}const url=videoUrl(m.item);if(!url)throw Error('영상 URL 없음');const name=names(m).frame,d=dest||await destination(name),blob=await firstFrame(url),where=await saveBlob(blob,name,d);activitySet('image','success','이미지 저장 완료',`${name} · 0.000초 · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('image','error','이미지 저장 실패',err(e));throw e}}
async function savePhoto(m,dest){activitySet('photo','running','사진 저장 중');try{m=await model(m);const url=imageUrl(m.item);if(!url)throw Error('원본 사진 URL 없음');const x=await fetchMedia(url,3000),name=`${base(m)}.${ext(x.type,url)}`,d=dest||await destination(name),where=await saveBlob(x.blob,name,d);activitySet('photo','success','사진 저장 완료',`${name} · ${where}`);return name}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('photo','error','사진 저장 실패',err(e));throw e}}
async function saveCarousel(m){activitySet('carousel','running','슬라이드 저장 중');try{m=await model(m);const ch=m.children?.length?m.children:childItems(m.item);if(!ch.length)throw Error('슬라이드 항목 없음');if(saveMode==='prompt')throw Error('슬라이드 전체 저장은 기본 다운로드 또는 지정 폴더를 사용하세요');const dest=saveMode==='folder'?await destination(`${base(m)}_01.jpg`):{kind:'default',label:'기본 다운로드'};let done=0,failed=0,cursor=0;async function worker(){while(true){const i=cursor++;if(i>=ch.length)return;const item=ch[i],n=String(i+1).padStart(2,'0'),vid=isVideo(item),url=vid?videoUrl(item):imageUrl(item);try{const x=await fetchMedia(url,vid?50000:3000),name=vid?`${base(m)}_${n}.mp4`:`${base(m)}_${n}.${ext(x.type,url)}`;await saveBlob(x.blob,name,dest);done++;activitySet('carousel','running',`슬라이드 저장 중 ${done}/${ch.length}`)}catch{failed++}}}await Promise.all(Array.from({length:Math.min(3,ch.length)},worker));activitySet('carousel',failed?'error':'success',failed?`슬라이드 ${done}/${ch.length} 저장`:`슬라이드 ${done}개 저장 완료`,failed?`실패 ${failed}`:'');return{done,failed}}catch(e){if(e?.name==='AbortError'){activityClear();throw e}activitySet('carousel','error','슬라이드 저장 실패',err(e));throw e}}
async function saveVideoSet(m){m=await model(m);let dest=null;if(saveMode==='folder')dest=await destination(names(m).video);const jobs=[['video',()=>saveVideo(m,dest)],['audio',()=>saveAudio(m,dest)],['image',()=>saveImage(m,dest)]];const out=[];for(const [name,fn] of jobs){try{out.push({name,status:'fulfilled',value:await fn()})}catch(e){if(e?.name==='AbortError')throw e;out.push({name,status:'rejected',reason:e})}}const ok=out.filter(x=>x.status==='fulfilled').length;activitySet('all3',ok===3?'success':'error',`3개 저장 ${ok}/3`,ok===3?'완료':`실패 ${3-ok}`);return out}
function gridAnchors(){return [...document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"],a[href*="/tv/"]')].map(a=>{const id=parseHref(a.getAttribute('href')||''),img=a.querySelector('img');if(!id||!img)return null;const w=a.offsetWidth||img.offsetWidth||0,h=a.offsetHeight||img.offsetHeight||0;if(w<70||h<70||w>innerWidth*.52||h>w*1.7)return null;return{a,id}}).filter(Boolean)}
function gridTargetId(){const xs=gridAnchors().map(x=>({...x,r:x.a.getBoundingClientRect()})).filter(x=>x.r.bottom>0&&x.r.top<innerHeight&&x.r.right>0&&x.r.left<innerWidth);if(!xs.length)return null;const cy=innerHeight/2;xs.sort((a,b)=>Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy)||a.r.left-b.r.left);return xs[0]?.id||null}
function injectCss(){if(document.getElementById('ri95-style'))return;const s=document.createElement('style');s.id='ri95-style';s.textContent=`
.ri95-host{position:relative!important}.ri95-card-ui{position:absolute;inset:0;pointer-events:none;overflow:hidden}.ri95-save{position:absolute;left:5px;top:5px;width:29px;height:29px;border:1px solid rgba(255,255,255,.42);border-radius:50%;background:rgba(12,12,12,.24);backdrop-filter:blur(5px);-webkit-backdrop-filter:blur(5px);color:#fff;display:grid;place-items:center;padding:0;pointer-events:auto;box-shadow:0 1px 4px rgba(0,0,0,.22);-webkit-tap-highlight-color:transparent;opacity:.88}.ri95-save:active{transform:scale(.94);background:rgba(12,12,12,.5)}.ri95-save svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.ri95-metrics{position:absolute;left:0;right:0;bottom:0;padding:15px 5px 5px;background:linear-gradient(to bottom,transparent,rgba(0,0,0,.58));pointer-events:none}.ri95-metrics[hidden]{display:none}.ri95-row{position:relative;height:11px;width:100%;font-variant-numeric:tabular-nums;white-space:nowrap}.ri95-row span{position:absolute;top:0;height:11px;line-height:11px;overflow:hidden;text-align:center;color:#fff;font:760 9.5px/11px system-ui;letter-spacing:-.35px;text-shadow:0 1px 2px #000,0 0 2px #000}.ri95-row.r2 span{font-size:9px}.ri95-row span:nth-child(1){left:0;width:30%;text-align:left}.ri95-row span:nth-child(2){left:30%;width:27%}.ri95-row span:nth-child(3){left:57%;width:21%}.ri95-row span:nth-child(4){left:78%;width:22%;text-align:right}
#ri95-menu{position:fixed;z-index:2147483646;width:184px;padding:6px;border:1px solid rgba(255,255,255,.12);border-radius:16px;background:rgba(22,22,24,.94);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 12px 34px rgba(0,0,0,.34);display:grid;grid-template-columns:1fr 1fr;gap:5px;font-family:system-ui;color:#fff}#ri95-menu button{height:39px;border:0;border-radius:11px;background:rgba(255,255,255,.075);color:#fff;font:700 11px/1 system-ui;-webkit-tap-highlight-color:transparent}#ri95-menu button:active{background:rgba(255,255,255,.16)}#ri95-menu button:disabled{opacity:.45}#ri95-menu .wide{grid-column:1/-1}
#ri95-launcher{position:fixed;right:13px;bottom:max(88px,calc(env(safe-area-inset-bottom) + 78px));z-index:2147483643;width:38px;height:38px;border:1px solid rgba(255,255,255,.38);border-radius:50%;background:rgba(20,20,22,.24);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);color:#fff;padding:0;font:800 10.5px/1 system-ui;letter-spacing:.2px;box-shadow:0 2px 10px rgba(0,0,0,.18);-webkit-tap-highlight-color:transparent;opacity:.82}#ri95-launcher:active{transform:scale(.95);opacity:1}#ri95-launcher[hidden]{display:none}#ri95-launcher.reel{left:13px;right:auto;bottom:max(198px,calc(env(safe-area-inset-bottom) + 186px));width:36px;height:36px}
#ri95-sheet{position:fixed;left:8px;right:8px;bottom:max(8px,env(safe-area-inset-bottom));z-index:2147483646;border:1px solid rgba(255,255,255,.11);border-radius:20px;background:rgba(22,22,24,.95);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px);color:#fff;box-shadow:0 -6px 30px rgba(0,0,0,.32);font-family:system-ui;overflow:hidden}#ri95-sheet[hidden]{display:none}#ri95-sheet.compact{height:auto;max-height:152px}#ri95-sheet.expanded{height:auto;max-height:min(70vh,620px)}#ri95-sheet.menuview{height:auto;max-height:min(58vh,500px)}.ri95-head{height:42px;display:flex;align-items:center;gap:4px;padding:0 8px 0 13px;border-bottom:1px solid rgba(255,255,255,.07)}.ri95-title{flex:1;min-width:0;font-size:12.5px;font-weight:760;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;letter-spacing:-.1px}.ri95-sub{margin-left:5px;color:rgba(255,255,255,.52);font-size:10px;font-weight:600}.ri95-head button{height:32px;min-width:32px;padding:0 8px;border:0;border-radius:9px;background:transparent;color:rgba(255,255,255,.84);font:700 11px system-ui;-webkit-tap-highlight-color:transparent}.ri95-head button:active{background:rgba(255,255,255,.08)}.ri95-body{padding:9px 11px 11px;max-height:calc(70vh - 43px);overflow:auto;overscroll-behavior:contain}.ri95-command{display:flex;align-items:center;gap:7px}.ri95-primary{height:39px;min-width:92px;padding:0 15px;border:0;border-radius:13px;background:#fff;color:#111;font:800 11.5px system-ui}.ri95-secondary{height:39px;padding:0 13px;border:1px solid rgba(255,255,255,.10);border-radius:13px;background:rgba(255,255,255,.06);color:#fff;font:700 11px system-ui}.ri95-spacer{flex:1}.ri95-state{min-width:0;color:rgba(255,255,255,.58);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri95-activity{display:flex;align-items:center;gap:7px;margin-top:7px;padding:7px 9px;border-radius:10px;background:rgba(255,255,255,.055);font-size:10px;line-height:1.3}.ri95-activity[hidden]{display:none}.ri95-activity .dot{width:6px;height:6px;border-radius:50%;background:rgba(255,255,255,.7);flex:0 0 auto}.ri95-activity.error{border:1px solid rgba(255,255,255,.18)}
.ri95-list{display:flex;flex-direction:column}.ri95-list button{width:100%;min-height:46px;border:0;border-bottom:1px solid rgba(255,255,255,.065);background:transparent;color:#fff;padding:0 3px;display:flex;align-items:center;text-align:left;font-family:system-ui}.ri95-list button:last-child{border-bottom:0}.ri95-list button:active{background:rgba(255,255,255,.05)}.ri95-list button:disabled{opacity:.46}.ri95-rowicon{width:30px;height:30px;border-radius:10px;background:rgba(255,255,255,.065);display:grid;place-items:center;margin-right:10px;font-size:11px;font-weight:800}.ri95-rowtext{flex:1;min-width:0}.ri95-rowtext b{display:block;font-size:11.5px}.ri95-rowtext small{display:block;margin-top:2px;color:rgba(255,255,255,.47);font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri95-value{margin-left:8px;color:rgba(255,255,255,.54);font-size:10px}.ri95-chevron{margin-left:8px;color:rgba(255,255,255,.34);font-size:19px;font-weight:300}.ri95-section{margin:8px 3px 4px;color:rgba(255,255,255,.4);font-size:9px;font-weight:700;letter-spacing:.4px}.ri95-savechoices{display:grid;grid-template-columns:1fr;gap:6px}.ri95-savechoices button{min-height:44px;border:1px solid rgba(255,255,255,.09);border-radius:13px;background:rgba(255,255,255,.055);color:#fff;padding:0 12px;display:flex;align-items:center;justify-content:space-between;font:700 11px system-ui}.ri95-savechoices button.active{background:rgba(255,255,255,.12)}
.ri95-tabs{display:flex;gap:4px;overflow-x:auto;padding:0 0 8px;scrollbar-width:none}.ri95-tabs::-webkit-scrollbar{display:none}.ri95-tabs button{flex:0 0 auto;height:32px;padding:0 11px;border:0;border-radius:10px;background:transparent;color:rgba(255,255,255,.5);font:700 10.5px system-ui}.ri95-tabs button.active{background:rgba(255,255,255,.10);color:#fff}.ri95-card{border:1px solid rgba(255,255,255,.075);border-radius:14px;background:rgba(255,255,255,.035);padding:11px 12px;margin-bottom:7px}.ri95-card:last-child{margin-bottom:0}.ri95-card h4{margin:0 0 7px;font-size:11px}.ri95-meta{display:flex;gap:7px;flex-wrap:wrap}.ri95-chip{display:inline-flex;align-items:center;height:25px;padding:0 9px;border-radius:9px;background:rgba(255,255,255,.065);color:rgba(255,255,255,.78);font-size:9.5px;font-weight:700}.ri95-empty{padding:2px 0;color:rgba(255,255,255,.48);font-size:10px;line-height:1.55}.ri95-mediaactions{display:flex;gap:6px;flex-wrap:wrap}.ri95-mediaactions button{height:35px;padding:0 12px;border:1px solid rgba(255,255,255,.09);border-radius:11px;background:rgba(255,255,255,.06);color:#fff;font:700 10px system-ui}
#ri95-toast{position:fixed;left:50%;top:max(12px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;max-width:82vw;padding:8px 12px;border-radius:14px;background:rgba(22,22,24,.94);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);color:#fff;font:700 10px/1.3 system-ui;box-shadow:0 5px 18px rgba(0,0,0,.25);pointer-events:none}
`;document.documentElement.appendChild(s)}
function notify(msg){if(!msg)return;toast?.remove();toast=document.createElement('div');toast.id='ri95-toast';toast.textContent=msg;document.documentElement.appendChild(toast);setTimeout(()=>{toast?.remove();toast=null},2200)}
function metricValues(){return null}
function removeCardUi(a){a.querySelector(':scope > .ri95-card-ui')?.remove();a.classList.remove('ri95-host')}
function ensureCard(a,id){a.classList.add('ri95-host');let ui=a.querySelector(':scope > .ri95-card-ui');if(!ui){ui=document.createElement('div');ui.className='ri95-card-ui';ui.innerHTML=`<button class="ri95-save" type="button" aria-label="저장">${dlIcon}</button><div class="ri95-metrics" hidden><div class="ri95-row r1"><span></span><span></span><span></span><span></span></div><div class="ri95-row r2"><span></span><span></span><span></span><span></span></div></div>`;a.appendChild(ui);ui.querySelector('.ri95-save').addEventListener('click',onGridSave)}ui.dataset.code=id.code;ui.dataset.kind=id.kind;const m=metricValues(id);const box=ui.querySelector('.ri95-metrics');if(m){box.hidden=false;const rs=box.querySelectorAll('.ri95-row');[m.row1,m.row2].forEach((vals,j)=>[...rs[j].children].forEach((sp,i)=>sp.textContent=vals[i]??''))}else box.hidden=true}
function ensureCards(){ensureQueued=false;const xs=gridAnchors(),valid=new Set(xs.map(x=>x.a));document.querySelectorAll('a.ri95-host').forEach(a=>{if(!valid.has(a))removeCardUi(a)});for(const {a,id} of xs)ensureCard(a,id);syncSurface()}
function scheduleEnsure(){if(ensureQueued)return;ensureQueued=true;requestAnimationFrame(ensureCards)}
function onGridSave(e){e.preventDefault();e.stopImmediatePropagation();const b=e.currentTarget,a=b.closest('a'),id=parseHref(a?.getAttribute('href')||'');if(!id)return;openGridMenu(id,b)}
function positionMenu(trigger){if(!menu)return;const r=trigger.getBoundingClientRect(),mr=menu.getBoundingClientRect(),bottomLimit=Math.max(120,innerHeight-82);let left=Math.max(7,Math.min(innerWidth-mr.width-7,r.left));let top=r.bottom+7;if(top+mr.height>bottomLimit)top=Math.max(8,r.top-mr.height-7);menu.style.left=`${left}px`;menu.style.top=`${top}px`}
function buttonBusy(trigger,busy=true){if(!trigger)return;if(busy){trigger.dataset.old=trigger.innerHTML;trigger.textContent='…';trigger.disabled=true}else{trigger.innerHTML=trigger.dataset.old||dlIcon;trigger.disabled=false;delete trigger.dataset.old}}
function addMenuButton(label,fn,wide=false){const b=document.createElement('button');b.textContent=label;if(wide)b.className='wide';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const trigger=menu?.__trigger;closeMenu();try{buttonBusy(trigger,true);await fn();if(trigger){trigger.textContent='✓';setTimeout(()=>buttonBusy(trigger,false),850)}}catch(x){if(trigger){if(x?.name==='AbortError')buttonBusy(trigger,false);else{trigger.textContent='!';setTimeout(()=>buttonBusy(trigger,false),950)}}if(x?.name!=='AbortError')notify('저장에 실패했습니다.')}};menu.appendChild(b)}
function openGridMenu(id,trigger){closeMenu();menu=document.createElement('div');menu.id='ri95-menu';menu.__trigger=trigger;document.documentElement.appendChild(menu);if(id.kind==='reel'){addMenuButton('영상',()=>resolve(id.code,id.kind).then(m=>{current=m;return saveVideo(m)}));addMenuButton('음원',()=>resolve(id.code,id.kind).then(m=>{current=m;return saveAudio(m)}));addMenuButton('이미지',()=>resolve(id.code,id.kind).then(m=>{current=m;return saveImage(m)}));addMenuButton('3개 모두',()=>resolve(id.code,id.kind).then(m=>{current=m;return saveVideoSet(m)}));positionMenu(trigger);return}const wait=document.createElement('button');wait.className='wide';wait.disabled=true;wait.textContent='콘텐츠 확인 중';menu.appendChild(wait);positionMenu(trigger);resolve(id.code,id.kind).then(m=>{if(!menu||menu.__trigger!==trigger)return;current=m;menu.innerHTML='';if(m.type==='carousel')addMenuButton('슬라이드 전체',()=>saveCarousel(m),true);else if(m.type==='photo')addMenuButton('원본 사진',()=>savePhoto(m),true);else{addMenuButton('영상',()=>saveVideo(m));addMenuButton('음원',()=>saveAudio(m));addMenuButton('이미지',()=>saveImage(m));addMenuButton('3개 모두',()=>saveVideoSet(m))}positionMenu(trigger)}).catch(()=>{if(menu&&menu.__trigger===trigger){menu.innerHTML='';const x=document.createElement('button');x.className='wide';x.disabled=true;x.textContent='확인할 수 없음';menu.appendChild(x);positionMenu(trigger)}})}
function closeMenu(){menu?.remove();menu=null}
function typeLabel(t){return t==='video'?'영상':t==='photo'?'사진':t==='carousel'?'슬라이드':'콘텐츠'}
function modeLabel(){return saveMode==='folder'?(dirHandle?.name?`지정 폴더 · ${dirHandle.name}`:'지정 폴더'):saveMode==='prompt'?'매번 선택':'기본 다운로드'}
function syncSurface(){if(!launcher)return;launcher.classList.toggle('reel',/^\/reels?(?:\/|$)/i.test(location.pathname))}
function openSheet(view='content',mode='compact'){sheetView=view;sheetMode=mode;sheet.hidden=false;if(launcher)launcher.hidden=true;renderSheet()}
function closeSheet(){sheet.hidden=true;closeMenu();if(launcher){launcher.hidden=false;syncSurface()}}
function activityHtml(){if(activity.state==='idle')return'';return`<div class="ri95-activity ${activity.state==='error'?'error':''}"><span class="dot"></span><div><b>${esc(activity.message)}</b>${activity.detail?`<div class="ri95-state">${esc(activity.detail)}</div>`:''}</div></div>`}
function identity(){if(!current)return{title:'RI',sub:'현재 콘텐츠를 확인합니다'};return{title:current.username!=='unknown'?`@${current.username}`:current.code,sub:typeLabel(current.type)}}
function contentCommandHtml(){const info=identity();return`<div class="ri95-head"><div class="ri95-title">${esc(info.title)}<span class="ri95-sub">${esc(info.sub)}</span></div><button data-a="global" aria-label="메뉴">•••</button><button data-a="detail">상세</button><button data-a="close" aria-label="닫기">×</button></div><div class="ri95-body"><div class="ri95-command"><button class="ri95-primary" data-a="save">저장</button><div class="ri95-spacer"></div><div class="ri95-state">${esc(modeLabel())}</div></div>${activityHtml()}</div>`}
function globalMenuHtml(){return`<div class="ri95-head"><button data-a="back">‹</button><div class="ri95-title">RI</div><button data-a="close">×</button></div><div class="ri95-body"><div class="ri95-section">관리</div><div class="ri95-list"><button data-a="save-settings"><span class="ri95-rowicon">↓</span><span class="ri95-rowtext"><b>저장</b><small>다운로드 위치와 방식</small></span><span class="ri95-value">${esc(modeLabel())}</span><span class="ri95-chevron">›</span></button><button data-a="data" disabled><span class="ri95-rowicon">D</span><span class="ri95-rowtext"><b>데이터</b><small>수집 기록 · History · 내보내기</small></span><span class="ri95-value">준비 중</span></button><button data-a="research-settings" disabled><span class="ri95-rowicon">R</span><span class="ri95-rowtext"><b>리서치 설정</b><small>댓글 · STT · OCR · 분석</small></span><span class="ri95-value">준비 중</span></button></div><div class="ri95-section">시스템</div><div class="ri95-list"><button data-a="update"><span class="ri95-rowicon">↻</span><span class="ri95-rowtext"><b>업데이트</b><small>현재 v${V}</small></span><span class="ri95-chevron">›</span></button><button data-a="copy"><span class="ri95-rowicon">i</span><span class="ri95-rowtext"><b>진단 복사</b><small>문제 확인용 정보만 복사</small></span></button><button data-a="destroy"><span class="ri95-rowicon">×</span><span class="ri95-rowtext"><b>RI 종료</b><small>현재 페이지에서 RI 제거</small></span></button></div></div>`}
function saveSettingsHtml(){return`<div class="ri95-head"><button data-a="global">‹</button><div class="ri95-title">저장 방식</div><button data-a="close">×</button></div><div class="ri95-body"><div class="ri95-savechoices"><button data-a="default" class="${saveMode==='default'?'active':''}"><span>기본 다운로드</span><span>${saveMode==='default'?'✓':''}</span></button><button data-a="folder" class="${saveMode==='folder'?'active':''}"><span>지정 폴더${dirHandle?.name?` · ${esc(dirHandle.name)}`:''}</span><span>${saveMode==='folder'?'✓':''}</span></button>${typeof showSaveFilePicker==='function'?`<button data-a="prompt" class="${saveMode==='prompt'?'active':''}"><span>매번 선택</span><span>${saveMode==='prompt'?'✓':''}</span></button>`:''}</div></div>`}
function detailNav(){const tabs=[['summary','요약'],['content-tab','콘텐츠'],['comments','댓글'],['analysis','분석'],['media','미디어']];return`<div class="ri95-tabs">${tabs.map(([a,l])=>`<button data-a="tab:${a}" class="${detailTab===a?'active':''}">${l}</button>`).join('')}</div>`}
function detailBody(){if(detailTab==='summary'){const info=identity();return`<div class="ri95-card"><h4>현재 콘텐츠</h4><div class="ri95-meta"><span class="ri95-chip">${esc(info.title)}</span><span class="ri95-chip">${esc(info.sub)}</span>${current?.code?`<span class="ri95-chip">${esc(current.code)}</span>`:''}</div></div><div class="ri95-card"><h4>성과 데이터</h4><div class="ri95-empty">수치 수집을 시작하기 전에는 빈 값이나 0을 표시하지 않습니다. 실제 데이터가 연결되면 조회수·참여율·24시간·계정대비가 이 영역에 표시됩니다.</div></div><div class="ri95-card"><h4>상태</h4><div class="ri95-meta"><span class="ri95-chip">저장 · ${esc(modeLabel())}</span><span class="ri95-chip">리서치 데이터 · 미수집</span></div></div>`}if(detailTab==='content-tab')return`<div class="ri95-card"><h4>본문</h4><div class="ri95-empty">본문, 해시태그, 언급 계정이 수집되면 이곳에 정리됩니다.</div></div><div class="ri95-card"><h4>음성 · 화면 글자</h4><div class="ri95-empty">STT와 OCR은 아직 수집하지 않았습니다. 기능 연결 전에는 빈 결과를 만들지 않습니다.</div></div>`;if(detailTab==='comments')return`<div class="ri95-card"><h4>댓글 리서치</h4><div class="ri95-empty">댓글과 답글이 수집되면 질문·구매의도·긍정·불만·반론·팁으로 분류해 표시합니다.</div></div>`;if(detailTab==='analysis')return`<div class="ri95-card"><h4>콘텐츠 분석</h4><div class="ri95-empty">훅, 도입, 전개, 핵심 메시지, CTA와 댓글 반응 분석이 이 영역에 표시됩니다.</div></div>`;const t=current?.type||'';let actions='';if(t==='video')actions='<button data-a="video">영상</button><button data-a="audio">음원</button><button data-a="image">이미지</button>';else if(t==='photo')actions='<button data-a="photo">원본 사진</button>';else if(t==='carousel')actions='<button data-a="carousel">슬라이드 전체</button>';else actions='<button data-a="refresh">현재 콘텐츠 확인</button>';return`<div class="ri95-card"><h4>미디어</h4><div class="ri95-mediaactions">${actions}</div></div><div class="ri95-card"><h4>저장 방식</h4><div class="ri95-empty">${esc(modeLabel())}</div></div>`}
function detailHtml(){const info=identity();return`<div class="ri95-head"><button data-a="content">‹</button><div class="ri95-title">${esc(info.title)}<span class="ri95-sub">${esc(info.sub)}</span></div><button data-a="global">•••</button><button data-a="close">×</button></div><div class="ri95-body">${detailNav()}${detailBody()}${activityHtml()}</div>`}
function renderSheet(){if(!sheet)return;sheet.className=sheetMode+(sheetView==='global'||sheetView==='save-settings'?' menuview':'');if(sheetView==='global'){sheet.innerHTML=globalMenuHtml();return}if(sheetView==='save-settings'){sheet.innerHTML=saveSettingsHtml();return}if(sheetView==='detail'){sheet.innerHTML=detailHtml();return}sheet.innerHTML=contentCommandHtml()}
function openCurrentSave(trigger){if(!current){resolveCurrent(false).then(()=>openCurrentSave(trigger)).catch(()=>notify('현재 콘텐츠를 확인할 수 없습니다.'));return}closeMenu();menu=document.createElement('div');menu.id='ri95-menu';menu.__trigger=trigger;document.documentElement.appendChild(menu);if(current.type==='video'){addMenuButton('영상',()=>saveVideo(current));addMenuButton('음원',()=>saveAudio(current));addMenuButton('이미지',()=>saveImage(current));addMenuButton('3개 모두',()=>saveVideoSet(current))}else if(current.type==='photo')addMenuButton('원본 사진',()=>savePhoto(current),true);else if(current.type==='carousel')addMenuButton('슬라이드 전체',()=>saveCarousel(current),true);else addMenuButton('다시 확인',()=>resolveCurrent(true),true);positionMenu(trigger)}
async function sheetAct(a,target){try{if(a==='close')closeSheet();else if(a==='detail'){sheetView='detail';sheetMode='expanded';detailTab='summary';renderSheet()}else if(a==='global'){sheetBack=sheetView==='detail'?'detail':'content';sheetView='global';sheetMode='compact';renderSheet()}else if(a==='back'){sheetView=sheetBack;sheetMode=sheetBack==='detail'?'expanded':'compact';renderSheet()}else if(a==='content'){sheetView='content';sheetMode='compact';renderSheet()}else if(a==='save-settings'){sheetView='save-settings';sheetMode='compact';renderSheet()}else if(a==='save')openCurrentSave(target);else if(a?.startsWith('tab:')){detailTab=a.slice(4);renderSheet()}else if(a==='refresh')await resolveCurrent(true);else if(a==='video')await saveVideo();else if(a==='audio')await saveAudio();else if(a==='image')await saveImage();else if(a==='photo')await savePhoto();else if(a==='carousel')await saveCarousel();else if(a==='default'){setMode('default');sheetView='content';sheetMode='compact';renderSheet()}else if(a==='folder'){await chooseDir();sheetView='content';sheetMode='compact';renderSheet()}else if(a==='prompt'){setMode('prompt');sheetView='content';sheetMode='compact';renderSheet()}else if(a==='update'){if(typeof window.__RI_LOADER_REFRESH==='function')window.__RI_LOADER_REFRESH();else notify('업데이트 기능을 찾지 못했습니다.')}else if(a==='copy'){const text=JSON.stringify({version:V,url:location.href,current:current?{code:current.code,type:current.type,username:current.username}:null,saveMode,activity},null,2);await navigator.clipboard?.writeText?.(text)}else if(a==='destroy')destroy()}catch(e){if(e?.name!=='AbortError')notify('작업을 완료하지 못했습니다.')}}
function scanQuiet(){resolveCurrent(false).catch(()=>{current=null;renderSheet()})}
function destroy(){try{obs?.disconnect();closeMenu();sheet?.remove();launcher?.remove();toast?.remove();document.getElementById('ri95-style')?.remove();document.querySelectorAll('a.ri95-host').forEach(removeCardUi);window.removeEventListener('scroll',onScroll,true);window.removeEventListener('resize',onResize,true)}catch{}delete window[K]}
function onScroll(){closeMenu();scheduleEnsure()}function onResize(){closeMenu();scheduleEnsure()}
function ui(){injectCss();launcher=document.createElement('button');launcher.id='ri95-launcher';launcher.textContent='RI';launcher.onclick=()=>{openSheet('content','compact');if(!current)scanQuiet()};document.documentElement.appendChild(launcher);sheet=document.createElement('div');sheet.id='ri95-sheet';sheet.hidden=true;sheet.addEventListener('click',e=>{const a=e.target?.closest?.('[data-a]')?.dataset?.a;if(a)sheetAct(a,e.target.closest('[data-a]'))});document.documentElement.appendChild(sheet);syncSurface()}
ui();restoreDir();scanQuiet();ensureCards();obs=new MutationObserver(scheduleEnsure);obs.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['href']});window.addEventListener('scroll',onScroll,true);window.addEventListener('resize',onResize,true);try{document.getElementById('__ri_update_btn')?.style.setProperty('display','none','important')}catch{}
window[K]={version:V,scan:resolveCurrent,open:openSheet,close:closeSheet,destroy,saveVideo,saveAudio,saveImage,savePhoto,saveCarousel,saveVideoSet};
})();