(()=> {
  const K='__RIMEDIA06', V='0.6.0';
  if(window[K]?.toggle){window[K].toggle();return}
  let box,body,mark=performance.now(),selected=null,lockedId=null;
  const captured=new Map(), R={version:V,tests:{},probe:[]};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const err=e=>`${e?.name||'Error'}: ${e?.message||e||''}`;
  const set=(k,s,d,x)=>{R.tests[k]={status:s,detail:d,extra:x||null,at:new Date().toISOString()};render()};
  function routeId(){try{const m=location.pathname.match(/\/(reels?|p|tv)\/([^/?#]+)/i);return m?{kind:/reels?/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}:null}catch{return null}}
  function nearbyId(){let best=null,score=-1;for(const a of document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]')){const r=a.getBoundingClientRect(),x=Math.max(0,Math.min(r.right,innerWidth)-Math.max(r.left,0)),y=Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0)),s=x*y;if(s>score){const m=a.pathname.match(/\/(reels?|p|tv)\/([^/?#]+)/i);if(m){score=s;best={kind:/reels?/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}}}}return best}
  function currentId(){return routeId()||nearbyId()}
  function visibleVideo(){return [...document.querySelectorAll('video')].map(v=>{const r=v.getBoundingClientRect(),x=Math.max(0,Math.min(r.right,innerWidth)-Math.max(r.left,0)),y=Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0));return[v,x*y]}).sort((a,b)=>b[1]-a[1])[0]?.[0]||null}
  function b64json(s){try{let x=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';const bin=atob(x),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return JSON.parse(new TextDecoder().decode(u))}catch{return null}}
  function meta(url){try{return b64json(new URL(url).searchParams.get('efg'))||{}}catch{return {}}}
  function canon(url){try{const u=new URL(url);u.searchParams.delete('bytestart');u.searchParams.delete('byteend');return u.href}catch{return String(url||'')}}
  function captureUrl(url,source){if(!/^https?:/i.test(url)||!/(cdninstagram|fbcdn)/i.test(url)||!/\.mp4(?:[?#]|$)/i.test(url))return;const u=canon(url),old=captured.get(u);captured.set(u,{url:u,source:source||old?.source||'capture',at:performance.now(),meta:meta(u)})}
  function captureText(t,source){try{let s=String(t||'').replace(/\\u0026/gi,'&').replace(/\\u003d/gi,'=').replace(/\\u0025/gi,'%').replace(/\\\//g,'/');const re=/https:\/\/[^"'\\\s<>]+?\.mp4(?:\?[^"'\\\s<>]*)?/gi;let m,n=0;while((m=re.exec(s))&&n<100){captureUrl(m[0],source);n++}}catch{}}
  const OF=window.fetch;window.fetch=async function(...args){const r=await OF.apply(this,args);try{const ct=r.headers.get('content-type')||'',cl=Number(r.headers.get('content-length')||0);if(/json|text|graphql|javascript/i.test(ct)&&(!cl||cl<6e6))r.clone().text().then(t=>captureText(t,'fetch-body')).catch(()=>{})}catch{}return r};
  const XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u,...rest){this.__ri06url=u;return XO.call(this,m,u,...rest)};XMLHttpRequest.prototype.send=function(...args){if(!this.__ri06hook){this.__ri06hook=1;this.addEventListener('load',()=>{try{const ct=this.getResponseHeader('content-type')||'';if(/json|text|graphql/i.test(ct)){let t='';if(!this.responseType||this.responseType==='text')t=this.responseText;else if(this.responseType==='json')t=JSON.stringify(this.response);if(t&&t.length<6e6)captureText(t,'xhr-body')}}catch{}})}return XS.apply(this,args)};
  function seedPerformance(){for(const e of performance.getEntriesByType?.('resource')||[]){if(e.startTime<mark)continue;captureUrl(e.name,e.initiatorType?`performance:${e.initiatorType}`:'performance')}}
  function tagType(m){const t=String(m?.vencode_tag||'').toLowerCase();if(/audio|aac|heaac/.test(t))return'audio';if(/baseline|video|clips|xpvds/.test(t))return'video';return'unknown'}
  function assetId(m){return String(m?.xpv_asset_id||m?.asset_id||'')}
  function groupCandidates(){seedPerformance();const gm=new Map();for(const c of captured.values()){const m=c.meta||meta(c.url),asset=assetId(m)||'unknown',type=tagType(m),bitrate=Number(m.bitrate||0),duration=Number(m.duration_s||0);if(!gm.has(asset))gm.set(asset,{asset,video:[],audio:[],unknown:[],latest:0,duration:0});const g=gm.get(asset),t={...c,meta:m,type,bitrate,duration};g.latest=Math.max(g.latest,c.at||0);g.duration=Math.max(g.duration,duration||0);(g[type]||g.unknown).push(t)}for(const g of gm.values()){g.video.sort((a,b)=>b.bitrate-a.bitrate);g.audio.sort((a,b)=>b.bitrate-a.bitrate);g.unknown.sort((a,b)=>b.at-a.at)}return [...gm.values()].sort((a,b)=>b.latest-a.latest)}
  function chooseGroup(){const gs=groupCandidates(),vv=visibleVideo(),vd=Number(vv?.duration||0);let g=null;if(vd>0&&Number.isFinite(vd))g=gs.filter(x=>x.video.length).sort((a,b)=>Math.abs((a.duration||9999)-vd)-Math.abs((b.duration||9999)-vd)||b.latest-a.latest)[0];if(!g)g=gs.find(x=>x.video.length&&x.audio.length)||gs.find(x=>x.video.length)||gs[0]||null;selected=g;if(g&&!lockedId)lockedId=currentId();return g}
  function code(){return lockedId?.code||(selected?.asset&&selected.asset!=='unknown'?`asset_${selected.asset}`:'media')}
  async function fetchBlob(c,min=5000){const r=await OF(c.url,{credentials:'omit',mode:'cors',cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const b=await r.blob();if(b.size<min)throw Error('파일이 너무 작음 '+b.size+'B');return{...c,blob:b,mime:b.type||r.headers.get('content-type')||''}}
  function mp4Kinds(ab){const dv=new DataView(ab),out=new Set(),containers=new Set(['moov','trak','mdia','minf','stbl','edts','dinf','moof','traf','mvex','udta','meta']);const typ=p=>String.fromCharCode(dv.getUint8(p),dv.getUint8(p+1),dv.getUint8(p+2),dv.getUint8(p+3));function walk(a,b,depth){let p=a,n=0;while(p+8<=b&&n++<5000){let size=dv.getUint32(p),head=8;if(size===1&&p+16<=b){const hi=dv.getUint32(p+8),lo=dv.getUint32(p+12);size=hi*4294967296+lo;head=16}else if(size===0)size=b-p;if(!Number.isFinite(size)||size<head||p+size>b)break;const t=typ(p+4);if(t==='hdlr'&&p+head+12<=p+size){const h=typ(p+head+8);if(h==='vide'||h==='soun')out.add(h)}if(containers.has(t)&&depth<8){let st=p+head;if(t==='meta')st+=4;walk(st,p+size,depth+1)}p+=size}}walk(0,dv.byteLength,0);return[...out]}
  async function mediaMeta(blob){const u=URL.createObjectURL(blob),v=document.createElement('video');v.preload='metadata';v.muted=true;v.playsInline=true;v.src=u;try{return await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('metadata timeout')),10000);v.onloadedmetadata=()=>{clearTimeout(to);ok({duration:Number(v.duration||0),w:v.videoWidth||0,h:v.videoHeight||0})};v.onerror=()=>{clearTimeout(to);no(Error('metadata load fail'))}})}finally{URL.revokeObjectURL(u)}}
  async function inspectCandidate(c){const x=await fetchBlob(c,10000),ab=await x.blob.arrayBuffer(),kinds=mp4Kinds(ab);let mm={duration:0,w:0,h:0};try{mm=await mediaMeta(x.blob)}catch{}return{...x,kinds,...mm}}
  async function findCombined(){set('합본 원본','WAIT','응답/네트워크 MP4 내부 트랙 검사 중');seedPerformance();const g=selected||chooseGroup(),vd=Number(visibleVideo()?.duration||g?.duration||0);const all=[...(g?.unknown||[]),...(g?.video||[]),...captured.values()].filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i);all.sort((a,b)=>{const at=tagType(a.meta||meta(a.url)),bt=tagType(b.meta||meta(b.url));return(at==='unknown'?-2:0)-(bt==='unknown'?-2:0)||(b.at||0)-(a.at||0)});R.probe=[];let best=null;for(const c of all.slice(0,14)){try{const x=await inspectCandidate(c),ok=x.kinds.includes('vide')&&x.kinds.includes('soun'),delta=vd&&x.duration?Math.abs(vd-x.duration):0;R.probe.push({url:c.url,source:c.source,kinds:x.kinds,duration:x.duration,w:x.w,h:x.h,size:x.blob.size});if(ok&&(!vd||delta<2.5)){best=x;break}}catch(e){R.probe.push({url:c.url,source:c.source,error:err(e)})}}if(best){R.combined=best;set('합본 원본','PASS',`영상+음원 포함 · ${(best.blob.size/1048576).toFixed(1)}MB · ${best.w}x${best.h} · ${best.duration.toFixed(1)}s`);return best}R.combined=null;set('합본 원본','PARTIAL','합본 원본 미발견 → 별도 영상+음원 mux 필요');return null}
  async function sharpThumb(){const g=selected||chooseGroup();if(!g?.video?.length)throw Error('영상 트랙 없음');const x=await fetchBlob(g.video[0],50000),u=URL.createObjectURL(x.blob),v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src=u;v.style='position:fixed;left:-9999px;top:-9999px;width:2px;height:2px';document.body.appendChild(v);try{await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('영상 로드 시간초과')),12000);v.onloadedmetadata=()=>{clearTimeout(to);ok()};v.onerror=()=>{clearTimeout(to);no(Error('영상 로드 실패'))}});const dur=Number(v.duration||0),lim=Math.max(.25,Math.min(2.2,dur*.12||2.2)),raw=[.12,.25,.45,.7,1.05,1.5,2.0].filter(t=>t<dur-.05&&t<=lim+.05);if(!raw.length)raw.push(Math.min(.05,dur/4));const sw=160,sh=Math.max(90,Math.round(sw*(v.videoHeight||1280)/(v.videoWidth||720))),c=document.createElement('canvas');c.width=sw;c.height=sh;const ctx=c.getContext('2d',{willReadFrequently:true});let best=null;async function seek(t){v.currentTime=t;await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('seek timeout')),4000);v.onseeked=()=>{clearTimeout(to);ok()};v.onerror=()=>{clearTimeout(to);no(Error('seek fail'))}})}for(const t of raw){try{await seek(t);ctx.drawImage(v,0,0,sw,sh);const d=ctx.getImageData(0,0,sw,sh).data;let score=0,mean=0,cnt=0;for(let y=1;y<sh-1;y+=2)for(let x0=1;x0<sw-1;x0+=2){const i=(y*sw+x0)*4,l=.299*d[i]+.587*d[i+1]+.114*d[i+2],ir=i+4,ib=i+sw*4,lr=.299*d[ir]+.587*d[ir+1]+.114*d[ir+2],lb=.299*d[ib]+.587*d[ib+1]+.114*d[ib+2];score+=Math.abs(l-lr)+Math.abs(l-lb);mean+=l;cnt++}mean/=cnt||1;if(mean<24||mean>232)score*=.55;if(!best||score>best.score)best={t,score}}catch{}}if(!best)throw Error('선명 프레임 선택 실패');await seek(best.t);const full=document.createElement('canvas');full.width=v.videoWidth;full.height=v.videoHeight;full.getContext('2d').drawImage(v,0,0);const b=await new Promise((ok,no)=>full.toBlob(z=>z?ok(z):no(Error('JPG 생성 실패')),'image/jpeg',.93));return{blob:b,type:'image/jpeg',source:'bestEarlyFrame',time:best.t}}finally{v.remove();URL.revokeObjectURL(u)}}
  function coverUrl(){const v=visibleVideo();if(v&&/^https?:/i.test(v.poster||''))return{url:v.poster,source:'video.poster'};if(!v)return null;const vr=v.getBoundingClientRect(),va=Math.max(1,vr.width*vr.height);let best=null,sc=0;for(const img of document.querySelectorAll('img')){const r=img.getBoundingClientRect(),ow=Math.max(0,Math.min(vr.right,r.right)-Math.max(vr.left,r.left)),oh=Math.max(0,Math.min(vr.bottom,r.bottom)-Math.max(vr.top,r.top)),cv=ow*oh/va;if(cv<.55)continue;const u=img.currentSrc||img.src||'';if(!/^https?:/i.test(u))continue;const s=cv*1e6+(img.naturalWidth||r.width)*(img.naturalHeight||r.height);if(s>sc){sc=s;best={url:u,source:'overlap-image'}}}return best}
  async function thumbBlob(){const c=coverUrl();if(c){try{const r=await OF(c.url,{credentials:'omit',mode:'cors',cache:'no-store'}),b=await r.blob();if(r.ok&&/^image\//i.test(b.type)&&b.size>5000)return{blob:b,type:b.type,source:c.source,time:null}}catch{}}return sharpThumb()}
  function dl(b,n){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000)}
  async function saveCombined(){set('합본 저장','WAIT','영상+음원 포함 MP4 찾는 중');try{const x=R.combined||await findCombined();if(!x)throw Error('합본 원본 없음 — mux 단계 필요');const n=`Instagram_${code()}_merged.mp4`;dl(x.blob,n);set('합본 저장','PASS',`${n} · ${(x.blob.size/1048576).toFixed(1)}MB · 영상+음원`)}catch(e){set('합본 저장','PARTIAL',err(e))}}
  async function saveVideo(){set('영상 저장','WAIT','영상 전용 받는 중');try{const g=selected||chooseGroup();const x=await fetchBlob(g.video[0],50000),n=`Instagram_${code()}_video.mp4`;dl(x.blob,n);set('영상 저장','PASS',`${n} · ${(x.blob.size/1048576).toFixed(1)}MB · 영상 전용`)}catch(e){set('영상 저장','FAIL',err(e))}}
  async function saveAudio(){set('음원 저장','WAIT','음원 받는 중');try{const g=selected||chooseGroup();if(!g?.audio?.length)throw Error('음원 트랙 없음');const x=await fetchBlob(g.audio[0],5000),n=`Instagram_${code()}_audio.m4a`;dl(x.blob,n);set('음원 저장','PASS',`${n} · ${Math.round(x.blob.size/1024)}KB`)}catch(e){set('음원 저장','FAIL',err(e))}}
  async function saveThumb(){set('이미지 저장','WAIT','실제 표지/초반 선명 프레임 생성 중');try{const x=await thumbBlob(),n=`Instagram_${code()}_thumb.jpg`;dl(x.blob,n);set('이미지 저장','PASS',`${n} · ${x.source}${x.time!=null?` @ ${x.time.toFixed(2)}s`:''} · ${Math.round(x.blob.size/1024)}KB`)}catch(e){set('이미지 저장','FAIL',err(e))}}
  function scan(){const g=chooseGroup(),v=visibleVideo(),id=lockedId||currentId();if(!lockedId&&id)lockedId=id;set('콘텐츠 고정',lockedId?.code?'PASS':'PARTIAL',lockedId?`${lockedId.kind}/${lockedId.code}`:'shortcode 미확정');set('현재 Video',v?'PASS':'PARTIAL',v?`${v.videoWidth||0}x${v.videoHeight||0} · ${Number(v.duration||0).toFixed(1)}s`:'보이는 video 없음');set('미디어 그룹',g?'PASS':'FAIL',g?`asset …${String(g.asset).slice(-8)} · ${g.duration||'?'}s · 영상 ${g.video.length} · 음원 ${g.audio.length} · 기타 ${g.unknown.length}`:'그룹 없음');set('영상 트랙',g?.video?.length?'PASS':'FAIL',g?.video?.length?`${Math.round((g.video[0].bitrate||0)/1000)}kbps · 영상 전용`:'없음');set('음원 트랙',g?.audio?.length?'PASS':'PARTIAL',g?.audio?.length?`${Math.round((g.audio[0].bitrate||0)/1000)}kbps · 음원 전용`:'없음');set('대표 이미지',coverUrl()?'PASS':'PARTIAL',coverUrl()?'실제 표지 후보':'실제 표지 없음 → 초반 선명 프레임 선택')}
  function resetCapture(){mark=performance.now();captured.clear();selected=null;lockedId=null;R.combined=null;set('새 Reel 포착','WAIT','이제 Reel을 하나 넘긴 뒤 재탐지/합본 탐색');setTimeout(()=>scan(),300)}
  async function copy(){try{await navigator.clipboard.writeText(JSON.stringify({...R,url:location.href,lockedId,captured:[...captured.values()]},null,2));set('결과 복사','PASS','JSON 복사 완료')}catch(e){set('결과 복사','FAIL',err(e))}}
  function ui(){box=document.createElement('div');box.style='position:fixed;z-index:2147483647;left:8px;right:8px;bottom:8px;max-height:80vh;overflow:auto;background:#111;color:#eee;border:1px solid #555;border-radius:14px;padding:10px;font:12px/1.45 system-ui;box-shadow:0 8px 30px #0009';box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><b>RI 합본/대표이미지 검증 v${V}</b><button data-a="toggle">숨김</button></div><div style="opacity:.75;margin:6px 0">합본 원본 탐색 + 영상/음원 분리 유지 + 초반 선명 프레임</div><div id="ri06b"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px"><button data-a="reset">새 Reel 포착</button><button data-a="scan">재탐지</button><button data-a="find">합본 원본 탐색</button><button data-a="merged">합본 저장</button><button data-a="video">영상만 저장</button><button data-a="audio">음원만 저장</button><button data-a="thumb">대표 이미지 저장</button><button data-a="copy">결과 복사</button><button data-a="destroy">종료</button></div>`;document.documentElement.appendChild(box);body=box.querySelector('#ri06b');box.querySelectorAll('button').forEach(b=>b.onclick=()=>act(b.dataset.a));render()}
  function render(){if(!body)return;body.innerHTML=Object.entries(R.tests).map(([k,v])=>`<div style="border-top:1px solid #292929;padding:5px 0"><b style="display:inline-block;width:76px;color:${v.status==='PASS'?'#8ee6a8':v.status==='FAIL'?'#ff9b9b':v.status==='WAIT'?'#ddd':'#ffd979'}">${v.status}</b><b>${esc(k)}</b><div style="margin-left:76px;word-break:break-word;opacity:.9">${esc(v.detail)}</div></div>`).join('')}
  async function act(a){if(a==='toggle')toggle();else if(a==='reset')resetCapture();else if(a==='scan')scan();else if(a==='find')await findCombined();else if(a==='merged')await saveCombined();else if(a==='video')await saveVideo();else if(a==='audio')await saveAudio();else if(a==='thumb')await saveThumb();else if(a==='copy')await copy();else if(a==='destroy')destroy()}
  function toggle(){box.style.display=box.style.display==='none'?'':'none'}
  function destroy(){try{window.fetch=OF;XMLHttpRequest.prototype.open=XO;XMLHttpRequest.prototype.send=XS}catch{}box?.remove();delete window[K]}
  window[K]={toggle,destroy,report:R};ui();set('외부본체/Blob','PASS','v0.6 실행 성공');scan();
})();