(()=>{
const K='__RISAVE084',V='0.8.4',DB='ri-bookmarklet',STORE='handles',DIRKEY='instagram-download-dir',MODEKEY='riSaveMode';
for(const k of ['__RISAVE083','__RISAVEUI081','__RISAVECORE081','__RIMEDIA080','__RIMEDIA074','__RIMEDIA071','__RIMEDIA070','__RIMEDIA062'])try{window[k]?.destroy?.()}catch{}
try{window[K]?.destroy?.()}catch{}
let panel,mini,statusEl,buttonsEl,moreEl,obs,dirHandle=null,current=null,saveMode=localStorage.getItem(MODEKEY)||'default';
const cache=new Map(),S={};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safe=s=>String(s||'x').normalize('NFKC').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,40)||'x';
const err=e=>`${e?.name||'Error'}: ${e?.message||e||''}`;
function set(k,state,detail){S[k]={status:state,detail,at:new Date().toISOString()};render()}
function parseHref(h){const m=String(h||'').match(/\/(reels?|p|tv)\/([^/?#]+)/i);return m?{kind:/reels?/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}:null}
function routeId(){try{return parseHref(location.pathname)}catch{return null}}
function gridAnchors(){
  return [...document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"],a[href*="/tv/"]')].map(a=>{
    const id=parseHref(a.getAttribute('href')||''),r=a.getBoundingClientRect();
    if(!id||r.width<50||r.height<50||r.width>innerWidth*.6||r.height>innerHeight*.65||!a.querySelector('img'))return null;
    const ix=Math.max(0,Math.min(r.right,innerWidth)-Math.max(r.left,0)),iy=Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0));
    return {a,id,r,area:ix*iy,full:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight};
  }).filter(Boolean)
}
function gridTargetId(){
  const xs=gridAnchors(),full=xs.filter(x=>x.full);
  if(full.length){
    const cy=innerHeight/2;
    const d=Math.min(...full.map(x=>Math.abs((x.r.top+x.r.bottom)/2-cy)));
    const row=full.filter(x=>Math.abs((x.r.top+x.r.bottom)/2-cy)<=d+Math.max(16,x.r.height*.22));
    row.sort((a,b)=>a.r.left-b.r.left||Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy));
    if(row[0])return row[0].id;
  }
  const vis=xs.filter(x=>x.area>0).sort((a,b)=>b.area-a.area||a.r.left-b.r.left);
  return vis[0]?.id||null
}
function currentId(){return routeId()||gridTargetId()}
function appId(){for(const s of document.querySelectorAll('script[type="application/json"]')){const m=(s.textContent||'').match(/"APP_ID":"?(\d+)"?/i);if(m)return m[1]}return'936619743392459'}
async function sameOriginJson(url){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{'X-IG-App-ID':appId(),'Accept':'*/*'}});if(!r.ok)throw Error(`Instagram API ${r.status}`);return r.json()}
function normalizeItem(x){if(!x)return null;if(x.xdt_api__v1__media__shortcode__web_info?.items?.[0])return x.xdt_api__v1__media__shortcode__web_info.items[0];if(x.items?.[0])return x.items[0];if(x.shortcode_media)return x.shortcode_media;return x}
function usernameOf(i){return i?.user?.username||i?.owner?.username||i?.owner?.user?.username||i?.username||'unknown'}
function childItems(i){if(Array.isArray(i?.carousel_media))return i.carousel_media;if(Array.isArray(i?.edge_sidecar_to_children?.edges))return i.edge_sidecar_to_children.edges.map(e=>e?.node).filter(Boolean);if(Array.isArray(i?.children))return i.children;return[]}
function videoVersions(i){const a=Array.isArray(i?.video_versions)?i.video_versions:[],b=Array.isArray(i?.video_resources)?i.video_resources.map(x=>({url:x.src,width:x.config_width||x.width,height:x.config_height||x.height})):[];return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function videoUrl(i){return videoVersions(i)[0]?.url||i?.video_url||''}
function imageCandidates(i){const a=Array.isArray(i?.image_versions2?.candidates)?i.image_versions2.candidates:[],b=[];if(i?.display_url)b.push({url:i.display_url,width:i.dimensions?.width,height:i.dimensions?.height});if(i?.display_resources)for(const x of i.display_resources)b.push({url:x.src,width:x.config_width,height:x.config_height});return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function imageUrl(i){return imageCandidates(i)[0]?.url||''}
function explicitCover(i){return i?.cover_frame_url||i?.cover_url||i?.clips_metadata?.cover_frame_url||i?.clips_metadata?.cover_media?.image_versions2?.candidates?.[0]?.url||''}
function isVideo(i){return !!(videoUrl(i)||i?.is_video||Number(i?.media_type)===2||/video|clips|reel/i.test(String(i?.product_type||i?.__typename||'')))}
function mediaType(i){const ch=childItems(i);if(ch.length>1||Number(i?.media_type)===8||/sidecar/i.test(String(i?.__typename||'')))return'carousel';return isVideo(i)?'video':'photo'}
function dash(i){return i?.video_dash_manifest||i?.dash_info?.video_dash_manifest||''}
function dashAudio(xml){if(!xml)return'';try{const doc=new DOMParser().parseFromString(xml,'application/xml'),xs=[...doc.querySelectorAll('Representation')].map(rep=>{const a=rep.closest('AdaptationSet'),mime=rep.getAttribute('mimeType')||a?.getAttribute('mimeType')||'',type=a?.getAttribute('contentType')||'',bw=+(rep.getAttribute('bandwidth')||0),url=rep.querySelector('BaseURL')?.textContent?.trim()||'';return{mime,type,bw,url}}).filter(x=>x.url&&(x.mime.startsWith('audio')||x.type==='audio'));return xs.sort((a,b)=>b.bw-a.bw)[0]?.url||''}catch{return''}}
async function resolve(code,kind='p',force=false){
 if(!code)throw Error('shortcode 없음');if(!force&&cache.has(code))return cache.get(code);let item=null,last=null;
 try{const vars=encodeURIComponent(JSON.stringify({shortcode:code,__relay_internal__pv__PolarisFeedShareMenurelayprovider:true,__relay_internal__pv__PolarisIsLoggedInrelayprovider:true}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_id=9496392173716084&variables=${vars}`))?.data)}catch(e){last=e}
 if(!item)try{const vars=encodeURIComponent(JSON.stringify({shortcode:code}));item=normalizeItem((await sameOriginJson(`/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=${vars}`))?.data)}catch(e){last=e}
 if(!item)try{const j=await sameOriginJson(`/${kind==='reel'?'reel':'p'}/${encodeURIComponent(code)}/?__a=1&__d=dis`);item=normalizeItem(j?.graphql||j)}catch(e){last=e}
 if(!item)throw last||Error('콘텐츠 원본 정보 없음');
 const m={code:item?.code||item?.shortcode||code,kind,item,username:usernameOf(item),type:mediaType(item),children:childItems(item)};cache.set(code,m);return m
}
async function resolveCurrent(force=false){const id=currentId();if(!id?.code)throw Error('현재 콘텐츠 shortcode를 찾지 못함');set('현재 콘텐츠','PASS',`${id.kind}/${id.code}`);set('미디어 정보','WAIT','Instagram 원본 정보 확인 중');current=await resolve(id.code,id.kind,force);set('미디어 정보','PASS',`${current.type} · @${current.username} · ${current.children.length||1}개`);return current}
function base(m){return`IG_${safe(m?.code)}`}
function ext(type,url=''){type=String(type||'').toLowerCase();if(type.includes('png')||/\.png(?:[?#]|$)/i.test(url))return'png';if(type.includes('webp')||/\.webp(?:[?#]|$)/i.test(url))return'webp';if(type.includes('avif')||/\.avif(?:[?#]|$)/i.test(url))return'avif';return'jpg'}
function names(m){return{video:`${base(m)}.mp4`,audio:`${base(m)}_a.m4a`,frame:`${base(m)}_f.jpg`}}
async function fetchMedia(url,min=3000){if(!url)throw Error('원본 URL 없음');const r=await fetch(url,{credentials:'omit',mode:'cors',cache:'force-cache'});if(!r.ok)throw Error(`미디어 HTTP ${r.status}`);const blob=await r.blob();if(blob.size<min)throw Error(`파일이 너무 작음 ${blob.size}B`);return{blob,type:blob.type||r.headers.get('content-type')||'',url}}
function openDb(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function idbPut(k,v){const db=await openDb();try{await new Promise((ok,no)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);q.onsuccess=ok;q.onerror=()=>no(q.error)})}finally{db.close()}}
async function idbGet(k){const db=await openDb();try{return await new Promise((ok,no)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(k);q.onsuccess=()=>ok(q.result||null);q.onerror=()=>no(q.error)})}finally{db.close()}}
async function restoreDir(){try{dirHandle=await idbGet(DIRKEY);if(saveMode==='folder')set('저장 위치',dirHandle?'PARTIAL':'FAIL',dirHandle?`지정 폴더 기억됨 · 저장 시 권한 확인`:'지정 폴더 없음')}catch{}}
async function chooseDir(){if(typeof showDirectoryPicker!=='function')throw Error('지정 폴더 저장 미지원');dirHandle=await showDirectoryPicker({mode:'readwrite'});await idbPut(DIRKEY,dirHandle);saveMode='folder';localStorage.setItem(MODEKEY,saveMode);set('저장 위치','PASS',`지정 폴더 · ${dirHandle.name||'선택됨'}`)}
function setMode(mode){if(mode==='prompt'&&typeof showSaveFilePicker!=='function')throw Error('매번 선택 저장 미지원');saveMode=mode;localStorage.setItem(MODEKEY,mode);set('저장 위치','PASS',mode==='default'?'기본 다운로드':mode==='prompt'?'매번 저장 위치 선택':`지정 폴더 · ${dirHandle?.name||'미선택'}`)}
async function writableDir(){if(!dirHandle)throw Error('저장 폴더를 먼저 지정하세요');let p=typeof dirHandle.queryPermission==='function'?await dirHandle.queryPermission({mode:'readwrite'}):'granted';if(p!=='granted'&&typeof dirHandle.requestPermission==='function')p=await dirHandle.requestPermission({mode:'readwrite'});if(p!=='granted')throw Error('폴더 쓰기 권한 필요');return dirHandle}
async function destination(name){if(saveMode==='folder'){const h=await writableDir();return{kind:'folder',handle:h,label:`지정 폴더/${h.name||''}`}}if(saveMode==='prompt'){const h=await showSaveFilePicker({suggestedName:name});return{kind:'file',handle:h,label:'직접 선택'}}return{kind:'default',label:'기본 다운로드'}}
async function saveBlob(blob,name,dest){dest=dest||await destination(name);if(dest.kind==='folder'){const f=await dest.handle.getFileHandle(name,{create:true}),w=await f.createWritable();await w.write(blob);await w.close();return dest.label}if(dest.kind==='file'){const w=await dest.handle.createWritable();await w.write(blob);await w.close();return dest.label}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),12000);return dest.label}
async function firstFrame(url){const x=await fetchMedia(url,50000),u=URL.createObjectURL(x.blob),v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.src=u;v.style='position:fixed;left:-9999px;top:-9999px;width:2px;height:2px';document.body.appendChild(v);try{await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('첫 프레임 로드 시간초과')),12000);v.addEventListener('loadeddata',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('영상 로드 실패'))},{once:true})});v.pause();if((v.currentTime||0)!==0){v.currentTime=0;await new Promise((ok,no)=>{const to=setTimeout(()=>no(Error('0초 이동 시간초과')),4000);v.addEventListener('seeked',()=>{clearTimeout(to);ok()},{once:true});v.addEventListener('error',()=>{clearTimeout(to);no(Error('0초 이동 실패'))},{once:true})})}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error('JPG 생성 실패')),'image/jpeg',.95))}finally{v.remove();URL.revokeObjectURL(u)}}
async function model(m){return m||current||resolveCurrent()}
async function saveVideo(m){const t=performance.now();set('영상 저장','WAIT','소리 포함 원본 영상 받는 중');try{m=await model(m);const url=videoUrl(m.item);if(!url)throw Error('소리 포함 원본 영상 URL 없음');const name=names(m).video,dest=await destination(name),x=await fetchMedia(url,50000),where=await saveBlob(x.blob,name,dest),sec=(performance.now()-t)/1000;set('영상 저장','PASS',`${name} · ${(x.blob.size/1048576).toFixed(1)}MB · ${sec.toFixed(1)}초 · ${where}`);return name}catch(e){set('영상 저장','FAIL',err(e));throw e}}
async function saveAudio(m){const t=performance.now();set('음원 저장','WAIT','원본 음원 받는 중');try{m=await model(m);const url=dashAudio(dash(m.item));if(!url)throw Error('별도 음원 URL 없음');const name=names(m).audio,dest=await destination(name),x=await fetchMedia(url,4000),where=await saveBlob(x.blob,name,dest),sec=(performance.now()-t)/1000;set('음원 저장','PASS',`${name} · ${Math.round(x.blob.size/1024)}KB · ${sec.toFixed(1)}초 · ${where}`);return name}catch(e){set('음원 저장','FAIL',err(e));throw e}}
async function saveImage(m){const t=performance.now();set('이미지 저장','WAIT','표지/첫 프레임 확인 중');try{m=await model(m);const cover=explicitCover(m.item);if(cover){const name=`${base(m)}_c.${ext('',cover)}`,dest=await destination(name),x=await fetchMedia(cover,3000),where=await saveBlob(x.blob,name,dest),sec=(performance.now()-t)/1000;set('이미지 저장','PASS',`${name} · 실제 표지 · ${sec.toFixed(1)}초 · ${where}`);return name}const url=videoUrl(m.item);if(!url)throw Error('영상 URL 없음');const name=names(m).frame,dest=await destination(name),blob=await firstFrame(url),where=await saveBlob(blob,name,dest),sec=(performance.now()-t)/1000;set('이미지 저장','PASS',`${name} · 0.000초 · ${sec.toFixed(1)}초 · ${where}`);return name}catch(e){set('이미지 저장','FAIL',err(e));throw e}}
async function savePhoto(m){const t=performance.now();set('사진 저장','WAIT','원본 사진 받는 중');try{m=await model(m);const url=imageUrl(m.item);if(!url)throw Error('원본 사진 URL 없음');const x=await fetchMedia(url,3000),name=`${base(m)}.${ext(x.type,url)}`,dest=await destination(name),where=await saveBlob(x.blob,name,dest),sec=(performance.now()-t)/1000;set('사진 저장','PASS',`${name} · ${Math.round(x.blob.size/1024)}KB · ${sec.toFixed(1)}초 · ${where}`);return name}catch(e){set('사진 저장','FAIL',err(e));throw e}}
async function saveCarousel(m){const t=performance.now();set('전체 저장','WAIT','슬라이드 원본 확인 중');try{m=await model(m);const ch=m.children?.length?m.children:childItems(m.item);if(!ch.length)throw Error('슬라이드 항목 없음');if(saveMode==='prompt')throw Error('캐러셀 전체 저장은 기본 다운로드 또는 지정 폴더를 사용하세요');const dest=saveMode==='folder'?await destination(`${base(m)}_01.jpg`):{kind:'default',label:'기본 다운로드'};let done=0,failed=0,cursor=0;async function worker(){while(true){const i=cursor++;if(i>=ch.length)return;const item=ch[i],n=String(i+1).padStart(2,'0'),vid=isVideo(item),url=vid?videoUrl(item):imageUrl(item);try{const x=await fetchMedia(url,vid?50000:3000),name=vid?`${base(m)}_${n}.mp4`:`${base(m)}_${n}.${ext(x.type,url)}`;await saveBlob(x.blob,name,dest);done++;set('전체 저장','WAIT',`${done}/${ch.length} 저장 · ${name}`)}catch{failed++;set('전체 저장','WAIT',`${done}/${ch.length} 저장 · 실패 ${failed}`)}}}await Promise.all(Array.from({length:Math.min(3,ch.length)},worker));const sec=(performance.now()-t)/1000;set('전체 저장',failed?'PARTIAL':'PASS',failed?`${done}/${ch.length} 성공 · ${failed} 실패 · ${sec.toFixed(1)}초`:`${done}/${ch.length} 전체 저장 완료 · ${sec.toFixed(1)}초`);return{done,failed}}catch(e){set('전체 저장','FAIL',err(e));throw e}}
async function savePrimary(m){m=await model(m);return m.type==='carousel'?saveCarousel(m):m.type==='video'?saveVideo(m):savePhoto(m)}
async function scan(force=true){current=null;const id=currentId();set('현재 콘텐츠',id?'PASS':'PARTIAL',id?`${id.kind}/${id.code}`:'shortcode 미확정');set('대상 선택','PASS',routeId()?'현재 게시물':'그리드 중앙 행 · 완전히 보이는 가장 왼쪽 카드 우선');set('저장 엔진','PASS','영상·음원·이미지·사진·캐러셀 통합');set('저장 위치','PASS',saveMode==='default'?'기본 다운로드':saveMode==='prompt'?'매번 저장 위치 선택':`지정 폴더 · ${dirHandle?.name||'복원 중'}`);try{return await resolveCurrent(force)}catch(e){set('미디어 정보','PARTIAL',err(e));return null}}
async function selectGrid(id){set('현재 콘텐츠','PASS',`${id.kind}/${id.code}`);set('대상 선택','PASS','그리드에서 직접 선택');set('미디어 정보','WAIT','선택 카드 원본 정보 확인 중');try{current=await resolve(id.code,id.kind,true);set('미디어 정보','PASS',`${current.type} · @${current.username} · ${current.children.length||1}개`);render();expand()}catch(e){current=null;set('미디어 정보','PARTIAL',err(e));expand()}}
function buttonHtml(){const type=current?.type||'',known=!!current;return `<button data-a="video"${known&&type!=='video'?' disabled':''}>영상 저장</button><button data-a="audio"${known&&type!=='video'?' disabled':''}>음원 저장</button><button data-a="image"${known&&type!=='video'?' disabled':''}>이미지 저장</button><button data-a="photo"${known&&type!=='photo'?' disabled':''}>사진 저장</button><button data-a="all"${known&&type!=='carousel'?' disabled':''}>캐러셀 전체 저장</button><button data-a="scan">현재 콘텐츠 재탐지</button>`}
function render(){if(statusEl)statusEl.innerHTML=Object.entries(S).map(([k,v])=>`<div style="border-top:1px solid #292929;padding:5px 0"><b style="display:inline-block;width:70px;color:${v.status==='PASS'?'#8ee6a8':v.status==='FAIL'?'#ff9b9b':v.status==='WAIT'?'#ddd':'#ffd979'}">${v.status}</b><b>${esc(k)}</b><div style="margin-left:70px;word-break:break-word;opacity:.9">${esc(v.detail)}</div></div>`).join('');if(buttonsEl)buttonsEl.innerHTML=buttonHtml();if(mini)mini.textContent=`RI ${V} · ${(current?.code||currentId()?.code||'-').slice(-8)}`}
function collapse(){panel.style.display='none';mini.style.display='block'}function expand(){panel.style.display='flex';mini.style.display='none'}
async function act(a){try{if(a==='collapse')collapse();else if(a==='scan')await scan(true);else if(a==='video')await saveVideo();else if(a==='audio')await saveAudio();else if(a==='image')await saveImage();else if(a==='photo')await savePhoto();else if(a==='all')await saveCarousel();else if(a==='folder')await chooseDir();else if(a==='default')setMode('default');else if(a==='prompt')setMode('prompt');else if(a==='more')moreEl.hidden=!moreEl.hidden;else if(a==='copy')await navigator.clipboard.writeText(JSON.stringify({version:V,status:S,current:current?{code:current.code,type:current.type,username:current.username,count:current.children.length||1}:null,url:location.href},null,2));else if(a==='destroy')destroy()}catch(e){if(e?.name!=='AbortError')console.warn('[RI save]',e)}}
function cards(){for(const x of gridAnchors()){const a=x.a;if(a.querySelector(':scope > .ri84-save'))continue;const b=document.createElement('button');b.className='ri84-save';b.textContent='저장';b.style='position:absolute;left:4px;bottom:4px;z-index:7;border:0;border-radius:10px;padding:4px 7px;background:#000b;color:#fff;font:11px system-ui';if(getComputedStyle(a).position==='static')a.style.position='relative';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const old=b.textContent;b.textContent='선택';b.disabled=true;await selectGrid(x.id);b.textContent='✓';setTimeout(()=>{b.textContent=old;b.disabled=false},900)};a.appendChild(b)}}
function destroy(){try{obs?.disconnect();panel?.remove();mini?.remove();document.querySelectorAll('.ri84-save').forEach(x=>x.remove())}catch{}delete window[K]}
function ui(){mini=document.createElement('button');mini.style='display:none;position:fixed;z-index:2147483647;right:10px;bottom:86px;background:#111;color:#fff;border:1px solid #666;border-radius:18px;padding:8px 11px;font:12px system-ui';mini.onclick=()=>{scan(true);expand()};document.documentElement.appendChild(mini);
 panel=document.createElement('div');panel.style='position:fixed;z-index:2147483647;left:8px;right:8px;bottom:72px;max-height:55vh;background:#111;color:#eee;border:1px solid #555;border-radius:14px;font:12px/1.45 system-ui;box-shadow:0 8px 30px #0009;display:flex;flex-direction:column;overflow:hidden';
 panel.innerHTML=`<div style="flex:0 0 auto;padding:10px 10px 6px;border-bottom:1px solid #333;display:flex;justify-content:space-between;align-items:center"><b>RI 저장 v${V}</b><button data-a="collapse">작게</button></div><div id="ri84status" style="flex:1 1 auto;overflow:auto;padding:0 10px;min-height:0"></div><div style="flex:0 0 auto;background:#111;border-top:1px solid #444;padding:8px"><div id="ri84buttons" style="display:grid;grid-template-columns:1fr 1fr;gap:6px"></div><button data-a="more" style="width:100%;margin-top:6px">저장 위치 · 기타</button><div id="ri84more" hidden style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px"><button data-a="folder">저장 폴더 지정</button><button data-a="default">기본 다운로드</button>${typeof showSaveFilePicker==='function'?'<button data-a="prompt">매번 선택</button>':''}<button data-a="copy">결과 복사</button><button data-a="destroy">종료</button></div></div>`;
 panel.addEventListener('click',e=>{const a=e.target?.dataset?.a;if(a)act(a)});document.documentElement.appendChild(panel);statusEl=panel.querySelector('#ri84status');buttonsEl=panel.querySelector('#ri84buttons');moreEl=panel.querySelector('#ri84more');render()}
ui();restoreDir();scan(true);cards();obs=new MutationObserver(()=>{clearTimeout(cards.t);cards.t=setTimeout(cards,250)});obs.observe(document.documentElement,{subtree:true,childList:true});window[K]={version:V,scan,expand,collapse,destroy,saveVideo,saveAudio,saveImage,savePhoto,saveCarousel};
})();