(()=>{
  const KEY='__RISAVEUI081',CORE='__RISAVECORE081';
  try{window.__RIMEDIA080?.destroy?.()}catch{};try{window.__RIMEDIA074?.destroy?.()}catch{};try{window[KEY]?.destroy?.()}catch{}
  const C=window[CORE];if(!C){alert('RI 저장 코어 로딩 실패');return}
  let panel,mini,body,buttons,obs,off;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function render(st){if(!body)return;body.innerHTML=Object.entries(st).map(([k,v])=>`<div style="border-top:1px solid #292929;padding:5px 0"><b style="display:inline-block;width:70px;color:${v.status==='PASS'?'#8ee6a8':v.status==='FAIL'?'#ff9b9b':v.status==='WAIT'?'#ddd':'#ffd979'}">${v.status}</b><b>${esc(k)}</b><div style="margin-left:70px;word-break:break-word;opacity:.9">${esc(v.detail)}</div></div>`).join('');renderButtons();updateMini()}
  function renderButtons(){if(!buttons)return;const m=C.current,type=m?.type||'';let h='<button data-a="scan">현재 콘텐츠 재탐지</button>';if(type==='video')h+='<button data-a="video">영상 저장</button><button data-a="audio">음원 저장</button><button data-a="image">이미지 저장</button>';else if(type==='photo')h+='<button data-a="photo">사진 저장</button>';else if(type==='carousel')h+='<button data-a="all">전체 저장</button>';h+='<button data-a="folder">저장 폴더 지정</button><button data-a="default">기본 다운로드</button>';if(typeof showSaveFilePicker==='function')h+='<button data-a="prompt">매번 선택</button>';h+='<button data-a="copy">결과 복사</button><button data-a="destroy">종료</button>';buttons.innerHTML=h}
  function updateMini(){if(mini)mini.textContent=`RI ${C.version} · ${(C.currentId()?.code||'-').slice(-8)}`}
  function collapse(){panel.style.display='none';mini.style.display='block'}function expand(){panel.style.display='block';mini.style.display='none'}
  async function act(a){try{if(a==='collapse')collapse();else if(a==='scan')await C.scan(true);else if(a==='video')await C.saveVideo();else if(a==='audio')await C.saveAudio();else if(a==='image')await C.saveImage();else if(a==='photo')await C.savePhoto();else if(a==='all')await C.saveCarousel();else if(a==='folder')await C.chooseDir();else if(a==='default')C.setMode('default');else if(a==='prompt')C.setMode('prompt');else if(a==='copy')await navigator.clipboard.writeText(JSON.stringify({...C.snapshot(),url:location.href},null,2));else if(a==='destroy')destroy()}catch(e){if(e?.name!=='AbortError')console.warn('[RI save]',e)}}
  function cards(){for(const a of document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"]')){if(a.querySelector(':scope > .ri81-save'))continue;const r=a.getBoundingClientRect();if(r.width<50||r.height<50||r.width>innerWidth*.48||r.height>innerHeight*.5||!a.querySelector('img'))continue;const m=(a.getAttribute('href')||'').match(/\/(reels?|p)\/([^/?#]+)/i);if(!m)continue;const b=document.createElement('button');b.className='ri81-save';b.textContent='저장';b.style='position:absolute;left:4px;bottom:4px;z-index:7;border:0;border-radius:10px;padding:4px 7px;background:#000b;color:#fff;font:11px system-ui';if(getComputedStyle(a).position==='static')a.style.position='relative';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const old=b.textContent;b.textContent='…';b.disabled=true;try{if(C.saveMode==='prompt')throw Error('빠른 저장은 기본/지정 폴더 모드 사용');const model=await C.resolve(m[2],/reels?/i.test(m[1])?'reel':'p');await C.savePrimary(model);b.textContent='✓'}catch{b.textContent='!'}setTimeout(()=>{b.textContent=old;b.disabled=false},1300)};a.appendChild(b)}}
  function destroy(){try{off?.();obs?.disconnect();panel?.remove();mini?.remove();document.querySelectorAll('.ri81-save').forEach(x=>x.remove())}catch{}delete window[KEY]}
  function ui(){mini=document.createElement('button');mini.style='display:none;position:fixed;z-index:2147483647;right:10px;bottom:86px;background:#111;color:#fff;border:1px solid #666;border-radius:18px;padding:8px 11px;font:12px system-ui';mini.onclick=()=>{C.scan(true);expand()};document.documentElement.appendChild(mini);panel=document.createElement('div');panel.style='position:fixed;z-index:2147483647;left:8px;right:8px;bottom:72px;max-height:42vh;overflow:auto;background:#111;color:#eee;border:1px solid #555;border-radius:14px;padding:10px;font:12px/1.45 system-ui;box-shadow:0 8px 30px #0009';panel.innerHTML=`<div style="position:sticky;top:-10px;background:#111;padding:4px 0 7px;z-index:2;display:flex;justify-content:space-between;align-items:center"><b>RI 저장 v${C.version}</b><button data-a="collapse">작게</button></div><div style="opacity:.75;margin:2px 0 6px">콘텐츠 유형 자동 판별 · 원본 직접 저장</div><div id="ri81body"></div><div id="ri81buttons" style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px"></div>`;panel.onclick=e=>{const a=e.target?.dataset?.a;if(a)act(a)};document.documentElement.appendChild(panel);body=panel.querySelector('#ri81body');buttons=panel.querySelector('#ri81buttons');renderButtons()}
  ui();off=C.subscribe(render);cards();obs=new MutationObserver(()=>{clearTimeout(cards.t);cards.t=setTimeout(cards,250)});obs.observe(document.documentElement,{subtree:true,childList:true});C.scan(true);window[KEY]={destroy,expand,collapse};
})();
