javascript:(async()=>{
const U='https://script.google.com/macros/s/AKfycbxj-jUt6mYeQMKqIR5d0hloyP7NqbBlZUwjbmctPovwxmApqWuius0WGpdsn21aMuOx/exec';
try{window.__YTDL__?.close?.()}catch{}
const T=[...crypto.getRandomValues(new Uint32Array(4))].map(n=>n.toString(36).padStart(7,'0')).join(''),N='ytGas_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8),B=document.createElement('iframe');B.name=N;B.style.display='none';document.documentElement.append(B);
let nonce='',seq=0,UI=null,FALL=null;const pending=new Map(),rid=p=>p+Date.now().toString(36)+(++seq).toString(36)+Math.random().toString(36).slice(2,9),err=r=>new Error(r?.error?.message||'Google 연결 요청 실패');
const onMsg=e=>{const d=e.data||{};if(d.type!=='YT_GAS_RESPONSE'||d.token!==T)return;const x=pending.get(d.requestId);if(!x)return;clearTimeout(x.timer);pending.delete(d.requestId);x.resolve(d.result||{ok:false,error:{message:'응답 형식 오류'}})};addEventListener('message',onMsg);
function post(o){const f=document.createElement('form');f.method='POST';f.action=U;f.target=N;f.style.display='none';for(const[k,v]of Object.entries(o)){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=String(v??'');f.append(i)}document.body.append(f);f.submit();f.remove()}
function send(o,id){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Google 연결 응답 없음'))},15000);pending.set(id,{resolve,reject,timer});post(o)})}
async function init(){const id=rid('i'),r=await send({mode:'init',origin:location.origin,token:T,requestId:id},id);if(!r.ok)throw err(r);nonce=String(r.data?.bridgeNonce||'');if(!nonce)throw new Error('Google 연결 정보 없음')}
async function call(action,payload={}){if(!nonce)await init();for(let k=0;k<2;k++){const id=rid('r'),r=await send({mode:'request',origin:location.origin,token:T,requestId:id,bridgeNonce:nonce,request:JSON.stringify({action,payload})},id);if(r?.ok)return r.data;if(k===0&&r?.error?.code==='BRIDGE_EXPIRED'){nonce='';await init();continue}throw err(r)}}
function close(){try{delete window.__YTDL_TOKEN;delete window.__YTDL_CALL;delete window.__YTDL_WEBAPP_URL;delete window.__YTDL_CLOSE;delete window.__YTDL__}catch{}removeEventListener('message',onMsg);for(const x of pending.values()){clearTimeout(x.timer);x.reject(new Error('종료'))}pending.clear();B.remove();UI?.remove();FALL?.remove()}
function fallback(m){FALL?.remove();const d=document.createElement('div');d.style.cssText='position:fixed;inset:0;background:#111;color:#fff;z-index:2147483647;padding:24px;font:15px system-ui';d.innerHTML='<div style="max-width:420px;margin:auto"><h2>유튜브다운로드 설정</h2><p style="color:#bbb">'+String(m||'Google 승인이 필요합니다.')+'</p><button id="ya" style="width:100%;padding:14px;margin:8px 0">Google 승인 창 열기</button><button id="yr" style="width:100%;padding:14px;margin:8px 0">승인 후 다시 연결</button><button id="yc" style="width:100%;padding:14px;margin:8px 0">닫기</button></div>';document.documentElement.append(d);FALL=d;d.querySelector('#ya').onclick=()=>open(U+'?origin='+encodeURIComponent(location.origin)+'&token='+encodeURIComponent(T),'ytGasAuth');d.querySelector('#yr').onclick=()=>{nonce='';load()};d.querySelector('#yc').onclick=close}
async function load(){try{FALL?.remove();FALL=null;const u=await call('get-ui',{}),h=String(u?.html||'');if(!h)throw new Error('Apps Script의 ui.html을 불러오지 못했습니다.');UI?.remove();UI=document.createElement('iframe');UI.style.cssText='position:fixed;inset:0;width:100%;height:100%;border:0;background:#111;z-index:2147483647';UI.srcdoc=h;document.documentElement.append(UI)}catch(e){fallback(e?.message||String(e))}}
window.__YTDL_TOKEN=T;window.__YTDL_CALL=call;window.__YTDL_WEBAPP_URL=U;window.__YTDL_CLOSE=close;window.__YTDL__={close,token:T};await load();
})()
