javascript:(async()=>{
const U='https://script.google.com/macros/s/AKfycbxj-jUt6mYeQMKqIR5d0hloyP7NqbBlZUwjbmctPovwxmApqWuius0WGpdsn21aMuOx/exec';
const FILE='유튜브다운로드sheet_v1',SHEET='수집',CAT='기본';
try{window.__YTDL__?.close?.()}catch{}
const T=[...crypto.getRandomValues(new Uint32Array(4))].map(n=>n.toString(36).padStart(7,'0')).join('');
const N='ytGas_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8),B=document.createElement('iframe');B.name=N;B.style.display='none';document.documentElement.append(B);
let nonce='',seq=0,UI=null,playerP=null,state=null,sheets=[],cats=[],dup=null,busyInit=false;const pending=new Map(),media={video:new Map(),audio:new Map()};
const rid=p=>p+Date.now().toString(36)+(++seq).toString(36)+Math.random().toString(36).slice(2,9),err=r=>new Error(r?.error?.message||'Google 연결 요청 실패');
const onMsg=e=>{const d=e.data||{};if(d.type!=='YT_GAS_RESPONSE'||d.token!==T)return;const x=pending.get(d.requestId);if(!x)return;clearTimeout(x.timer);pending.delete(d.requestId);x.resolve(d.result||{ok:false,error:{message:'응답 형식 오류'}})};addEventListener('message',onMsg);
function post(o){const f=document.createElement('form');f.method='POST';f.action=U;f.target=N;f.style.display='none';for(const[k,v]of Object.entries(o)){const i=document.createElement('input');i.type='hidden';i.name=k;i.value=String(v??'');f.append(i)}document.body.append(f);f.submit();f.remove()}
function send(o,id){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Google 연결 응답 없음'))},25000);pending.set(id,{resolve,reject,timer});post(o)})}
async function initBridge(){const id=rid('i'),r=await send({mode:'init',origin:location.origin,token:T,requestId:id},id);if(!r.ok)throw err(r);nonce=String(r.data?.bridgeNonce||'');if(!nonce)throw new Error('Google 연결 정보 없음')}
async function call(action,payload={}){if(!nonce)await initBridge();for(let k=0;k<2;k++){const id=rid('r'),r=await send({mode:'request',origin:location.origin,token:T,requestId:id,bridgeNonce:nonce,request:JSON.stringify({action,payload})},id);if(r?.ok)return r.data;if(k===0&&r?.error?.code==='BRIDGE_EXPIRED'){nonce='';await initBridge();continue}throw err(r)}}
const vid=()=>new URLSearchParams(location.search).get('v')||(location.pathname.match(/^\/shorts\/([A-Za-z0-9_-]+)/)||[])[1]||'';
const meta=s=>document.querySelector(s)?.content||'';
function fmtSec(v){let n=+v||0,h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return(h?h+':':'')+String(m).padStart(h?2:1,'0')+':'+String(s).padStart(2,'0')}
async function player(){if(playerP)return playerP;const id=vid();if(!id)throw new Error('YouTube 영상 페이지에서 실행해 주세요.');playerP=fetch('https://www.youtube.com/youtubei/v1/player',{method:'POST',credentials:'omit',headers:{'content-type':'application/json','x-youtube-client-name':'3','x-youtube-client-version':'20.10.38'},body:JSON.stringify({videoId:id,context:{client:{clientName:'ANDROID',clientVersion:'20.10.38',androidSdkVersion:30,hl:'ko',gl:'KR'}}})}).then(r=>{if(!r.ok)throw new Error('영상 정보를 가져오지 못했습니다.');return r.json()});return playerP}
function videoInfo(p){const d=p?.videoDetails||{},th=d.thumbnail?.thumbnails||[];return{id:vid(),title:d.title||meta('meta[property="og:title"]')||document.title.replace(/\s*-\s*YouTube\s*$/,''),channel:d.author||'',channelId:d.channelId||'',publishedAt:meta('meta[itemprop="datePublished"]')||p?.microformat?.playerMicroformatRenderer?.publishDate||'',duration:d.lengthSeconds?fmtSec(d.lengthSeconds):'',views:d.viewCount||'',thumbnail:th.at(-1)?.url||meta('meta[property="og:image"]')||''}}
function buildMedia(p){media.video.clear();media.audio.clear();const v=[],a=[];let n=0;const seen=new Set();for(const f of p?.streamingData?.formats||[]){if(!f.url||!String(f.mimeType||'').startsWith('video/mp4'))continue;const label=f.qualityLabel||((f.height||'')+'p');if(seen.has(label))continue;seen.add(label);const id='v'+n++;media.video.set(id,f);v.push({value:id,label})}n=0;for(const f of [...(p?.streamingData?.adaptiveFormats||[])].filter(x=>x.url&&String(x.mimeType||'').startsWith('audio/mp4')).sort((x,y)=>(y.bitrate||0)-(x.bitrate||0))){const id='a'+n++,label=Math.round((f.bitrate||0)/1000)+' kbps';media.audio.set(id,f);a.push({value:id,label})}return{video:v,audio:a}}
function categoryOptions(a){return(a||[]).map(x=>({value:String(x),label:String(x)}))}
function sendUI(o){try{UI?.contentWindow?.postMessage({...o,token:T},'*')}catch{}}
function fileList(){return(state?.files||[]).map(x=>({...x,value:x.id,label:x.name}))}
function sheetList(){return(sheets||[]).filter(x=>x.selectable!==false).map(x=>({...x,value:x.name,label:x.name}))}
async function selectFile(fileId,preferred=''){const r=await call('list-sheets',{fileId});sheets=r.sheets||[];const s=sheets.find(x=>x.selectable!==false&&x.name===preferred)||sheets.find(x=>x.selectable!==false);cats=s?((await call('list-categories',{fileId,sheetName:s.name})).categories||[]):[];return{s}}
async function sync(preferredSheet=SHEET){state=await call('get-state',{});if(!state.files?.length){await call('create-storage',{fileName:FILE,sheetName:SHEET,category:CAT});state=await call('get-state',{}) }const fileId=state.defaultFileId||state.files?.[0]?.id;if(!fileId)throw new Error('Google Sheets 저장공간을 만들지 못했습니다.');let q=await selectFile(fileId,preferredSheet);if(!q.s){await call('create-sheet',{fileId,sheetName:SHEET});q=await selectFile(fileId,SHEET)}if(!cats.length){await call('add-category',{fileId,sheetName:q.s.name,category:CAT});cats=(await call('list-categories',{fileId,sheetName:q.s.name})).categories||[]}dup=null;try{const d=await call('check-duplicate',{fileId,sheetName:q.s.name,videoId:vid()});if(d.found)dup={rows:d.rows||[]}}catch{}return{fileId,sheet:q.s}}
function drivePayload(fileId,sheetName){return{files:fileList(),sheets:sheetList(),categories:categoryOptions(cats),selectedFileId:fileId,selectedSheetName:sheetName,selectedCategory:cats[0]||''}}
async function bootstrap(){if(busyInit)return;busyInit=true;sendUI({type:'YT_TOOL_STATUS',state:'working',message:'준비 중…'});try{const [p,g]=await Promise.all([player(),sync()]);const m=buildMedia(p),fileId=g.fileId,sheetName=g.sheet.name;sendUI({type:'YT_TOOL_INIT',configured:true,video:videoInfo(p),media:m,drive:drivePayload(fileId,sheetName),duplicate:dup});sendUI({type:'YT_TOOL_STATUS',state:'ready',message:'준비됨'})}catch(e){sendUI({type:'YT_TOOL_STATUS',state:'error',message:e?.message||String(e),setup:true})}finally{busyInit=false}}
function collected(p,fields){const d=p?.videoDetails||{},v=videoInfo(p),r={},errors={};for(const k of fields||[]){if(k==='thumbnail')r.thumbnail=v.thumbnail;else if(k==='title')r.title=v.title;else if(k==='url')r.url='https://www.youtube.com/watch?v='+v.id;else if(k==='channel')r.channel=v.channel;else if(k==='publishedAt')r.publishedAt=v.publishedAt;else if(k==='duration')r.duration=v.duration;else if(k==='views')r.views=v.views;else if(k==='description')r.description=d.shortDescription||meta('meta[name="description"]')||'';else if(k==='tags')r.tags=d.keywords||[];else if(k==='videoId')r.videoId=v.id;else if(k==='channelId')r.channelId=v.channelId;else if(k==='rawMetadata')r.rawMetadata={videoDetails:{videoId:d.videoId,title:d.title,author:d.author,channelId:d.channelId,lengthSeconds:d.lengthSeconds,viewCount:d.viewCount,keywords:d.keywords,shortDescription:d.shortDescription},microformat:p?.microformat?.playerMicroformatRenderer||{}};else if(k==='likes')errors[k]='좋아요 수를 확인하지 못했습니다.';else if(k==='transcript')errors[k]='대본을 확인하지 못했습니다.';else if(k==='comments')errors[k]='댓글을 확인하지 못했습니다.';else if(k==='rawCaptions')errors[k]='자막 원본을 확인하지 못했습니다.'}return{videoId:v.id,requested:fields||[],result:r,errors,complete:true}}
function safeName(s){return String(s||'유튜브다운로드').replace(/[\\/:*?"<>|]/g,' ').replace(/\s+/g,' ').trim().slice(0,120)||'유튜브다운로드'}
function fileSpec(kind,p,fmt){const base=safeName(videoInfo(p).title);if(kind==='video')return{name:base+'.mp4',picker:{suggestedName:base+'.mp4',types:[{description:'MP4 영상',accept:{'video/mp4':['.mp4']}}]}};if(kind==='audio')return{name:base+'.m4a',picker:{suggestedName:base+'.m4a',types:[{description:'M4A 음성',accept:{'audio/mp4':['.m4a']}}]}};const json=fmt==='json',ext=json?'.json':'.txt',name=base+'_'+(fmt==='original'?'원문':'데이터')+ext;return{name,picker:{suggestedName:name,types:[{description:json?'JSON':'텍스트',accept:{[json?'application/json':'text/plain']:[ext]}}]}}}
async function writeMedia(h,f){const r=await fetch(f.url,{headers:{Range:'bytes=0-'}});if(!r.ok&&r.status!==206)throw new Error('미디어 다운로드 실패');const w=await h.createWritable();if(!r.body){await w.abort();throw new Error('미디어 응답 없음')}await r.body.pipeTo(w)}
async function writeText(h,t){const w=await h.createWritable();await w.write(t);await w.close()}
async function saveLocal(p){const pl=await player(),outs=[];if(p.types?.includes('video')){const f=media.video.get(p.video?.id);if(!f)throw new Error('저장 가능한 영상이 없습니다.');outs.push({kind:'video',f,...fileSpec('video',pl)})}if(p.types?.includes('audio')){const f=media.audio.get(p.audio?.id);if(!f)throw new Error('저장 가능한 음성이 없습니다.');outs.push({kind:'audio',f,...fileSpec('audio',pl)})}if(p.types?.includes('data'))outs.push({kind:'data',...fileSpec('data',pl,p.data?.format||'original')});if(!outs.length)throw new Error('저장할 항목이 없습니다.');let handles={};if(outs.length===1){if(typeof showSaveFilePicker!=='function')throw new Error('이 브라우저에서는 파일 저장 선택창을 사용할 수 없습니다.');handles[outs[0].kind]=await showSaveFilePicker(outs[0].picker)}else{if(typeof showDirectoryPicker!=='function')throw new Error('복수 저장은 폴더 선택을 지원하는 브라우저가 필요합니다.');const dir=await showDirectoryPicker();for(const o of outs)handles[o.kind]=await dir.getFileHandle(o.name,{create:true})}let packet=null;for(const o of outs){if(o.kind==='video'||o.kind==='audio')await writeMedia(handles[o.kind],o.f);else{packet=collected(pl,p.data?.fields||[]);let text='';try{text=UI.contentWindow.YTToolUI.formatData(packet,p.data?.format||'original')}catch{text=JSON.stringify(packet,null,2)}await writeText(handles.data,text)}}if(packet)sendUI({type:'YT_TOOL_DATA_RESULT',...packet});sendUI({type:'YT_TOOL_STATUS',state:'success',message:'로컬 저장 완료'})}
async function saveDrive(p){const pl=await player();let dataSaved=false;if(p.types?.includes('data')){const fileId=p.drive?.fileId,sheetName=p.drive?.sheetName;if(!fileId||!sheetName)throw new Error('저장할 파일과 시트를 선택하세요.');const packet=collected(pl,p.data?.fields||[]),management={...(p.management||{}),category:p.drive?.category||''};const sr=await call('save-record',{fileId,sheetName,videoId:vid(),record:packet.result,management,duplicateMode:p.duplicateMode||''});if(sr.status==='duplicate'){dup={rows:sr.duplicates||[]};sendUI({type:'YT_TOOL_DUPLICATE',duplicate:dup});sendUI({type:'YT_TOOL_STATUS',state:'ready',message:'이미 저장된 영상입니다. 업데이트 또는 새 기록 추가를 선택하세요.'});return}dup=null;sendUI({type:'YT_TOOL_DUPLICATE',duplicate:null});dataSaved=true}if(p.types?.includes('video')){const f=media.video.get(p.video?.id);if(!f)throw new Error('저장 가능한 영상이 없습니다.');sendUI({type:'YT_TOOL_DRIVE_MEDIA',kind:'video',src:f.url,filename:fileSpec('video',pl).name})}if(p.types?.includes('audio')){const f=media.audio.get(p.audio?.id);if(!f)throw new Error('저장 가능한 음성이 없습니다.');sendUI({type:'YT_TOOL_DRIVE_MEDIA',kind:'audio',src:f.url,filename:fileSpec('audio',pl).name})}sendUI({type:'YT_TOOL_STATUS',state:'success',message:dataSaved?'Sheets 저장 완료':'Drive 저장 버튼 준비 중…'})}
async function action(d){const a=d.action;try{if(a==='google-connect'){open(U+'?origin='+encodeURIComponent(location.origin)+'&token='+encodeURIComponent(T),'ytGasAuth');return}if(a==='create-storage'){await call('create-storage',{fileName:FILE,sheetName:SHEET,category:CAT});await bootstrap();return}if(a==='connect-file'){await call('connect-file',{sheetUrl:d.sheetUrl});const g=await sync();sendUI({type:'YT_TOOL_OPTIONS',...drivePayload(g.fileId,g.sheet.name)});return}if(a==='select-file'){const q=await selectFile(d.fileId);sendUI({type:'YT_TOOL_OPTIONS',...drivePayload(d.fileId,q.s?.name||'')});return}if(a==='select-sheet'){cats=(await call('list-categories',{fileId:d.fileId,sheetName:d.sheetName})).categories||[];sendUI({type:'YT_TOOL_OPTIONS',categories:categoryOptions(cats),selectedFileId:d.fileId,selectedSheetName:d.sheetName,selectedCategory:cats[0]||''});return}if(a==='create-sheet'){await call('create-sheet',{fileId:d.fileId,sheetName:d.sheetName});const q=await selectFile(d.fileId,d.sheetName);sendUI({type:'YT_TOOL_OPTIONS',...drivePayload(d.fileId,q.s?.name||d.sheetName)});return}if(a==='add-category'){cats=(await call('add-category',{fileId:d.fileId,sheetName:d.sheetName,category:d.category})).categories||[];sendUI({type:'YT_TOOL_OPTIONS',categories:categoryOptions(cats),selectedCategory:d.category});return}if(a==='setup-complete'){sendUI({type:'YT_TOOL_SETUP',configured:true,message:'설정 완료'});return}if(a==='open-file'){const f=state?.files?.find(x=>x.id===d.fileId);if(f?.url)open(f.url,'_blank');return}if(a==='open-sheet'){const s=sheets.find(x=>x.name===d.sheetName);if(s?.url)open(s.url,'_blank');return}if(a==='open-existing'){const u=d.duplicate?.rows?.[0]?.url||dup?.rows?.[0]?.url;if(u)open(u,'_blank');return}if(a==='sheets-new'){open('https://sheets.new','_blank');return}if(a==='sheets-open'){open('https://docs.google.com/spreadsheets/','_blank');return}if(a==='save-local'){sendUI({type:'YT_TOOL_STATUS',state:'working',message:'로컬 저장 중…'});await saveLocal(d);return}if(a==='save-drive'){sendUI({type:'YT_TOOL_STATUS',state:'working',message:'저장 중…'});await saveDrive(d);return}if(a==='close'){close();return}}catch(e){if(e?.name==='AbortError')sendUI({type:'YT_TOOL_STATUS',state:'ready',message:'저장 취소됨'});else sendUI({type:'YT_TOOL_STATUS',state:'error',message:e?.message||String(e)})}}
function recv(d){if(!d||d.token!==T)return;if(d.type==='YT_TOOL_READY'){bootstrap();return}if(d.type==='YT_TOOL_ACTION')action(d)}
function close(){try{delete window.__YTDL_RECV;delete window.__YTDL__}catch{}removeEventListener('message',onMsg);for(const x of pending.values()){clearTimeout(x.timer);x.reject(new Error('종료'))}pending.clear();B.remove();UI?.remove()}
window.__YTDL_RECV=recv;window.__YTDL__={close};
try{const u=await call('get-ui',{});let h=String(u?.html||'');if(!h)throw new Error('UI를 불러오지 못했습니다.');h=h.replaceAll('YouTube 수집도구 설정','유튜브다운로드 설정').replaceAll('YouTube 수집','유튜브다운로드').replaceAll('YouTube_수집','유튜브다운로드');h=h.replace(/token=new URLSearchParams\(location\.hash\.slice\(1\)\)\.get\('token'\)\|\|''/,"token='"+T+"'");h=h.replace(/const post=o=>\{.*?\};\n  const action=/s,"const post=o=>{o={...o,token};try{if(parent&&parent.__YTDL_RECV)return parent.__YTDL_RECV(o)}catch{}try{parent&&parent!==self&&parent.postMessage(o,'*')}catch{}};\n  const action=");h=h.replace(/q\('#saveBtn'\)\.onclick=async\(\)=>\{.*?\};\n  addEventListener/s,"q('#saveBtn').onclick=()=>{if(!S.types.size)return status('가져올 항목을 선택하세요.');if(!S.target)return status('저장 위치를 선택하세요.');const p=payload();if(S.types.has('video')&&!p.video.id)return status('저장 가능한 영상이 없습니다.');if(S.types.has('audio')&&!p.audio.id)return status('저장 가능한 음성이 없습니다.');if(S.target==='drive'&&S.types.has('data')&&(!p.drive.fileId||!p.drive.sheetName))return status('저장할 파일과 시트를 선택하세요.');S.busy=true;S.dataResult=null;clearDriveMedia();render();status(S.target==='local'?'로컬 저장 준비 중…':'저장 준비 중…');action(S.target==='local'?'save-local':'save-drive',p)};\n  addEventListener");UI=document.createElement('iframe');UI.style.cssText='position:fixed;inset:0;width:100%;height:100%;border:0;background:#111;z-index:2147483647';UI.srcdoc=h;document.documentElement.append(UI)}catch(e){close();alert('유튜브다운로드 실행 실패 · '+(e?.message||e))}
})()
